[tool]

[tool.ruff]
line-length = 119
target-version = "py311"
extend-include = ["*.ipynb"]
extend-exclude = [
    "migrations",
    "__pycache__",
    "frontend",
    "docs",
    "fixtures",
    "clevercloud",
]

[tool.ruff.lint]
ignore = ["E501"]

[tool.ruff.lint.per-file-ignores]
# pas d'auto sorting sur ces fichiers pour éviter les imports circulaires
"__init__.py" = ["I", "F401"]

[tool.ruff.lint.mccabe]
max-complexity = 10

[tool.ruff.lint.isort]
section-order = [
    "future",
    "standard-library",
    "django",
    "third-party",
    "first-party",
    "local-folder",
]

[tool.ruff.lint.isort.sections]
"django" = ["django"]


[tool.ruff.format]
docstring-code-format = true
