# Generated by Django 4.2.7 on 2023-11-14 13:27

# import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0002_ingredient_microorganism_plant_substance_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("modification_date", models.DateTimeField(auto_now=True)),
                ("title", models.TextField(verbose_name="titre")),
                (
                    "tagline",
                    models.TextField(
                        blank=True, null=True, verbose_name="description courte"
                    ),
                ),
                (
                    "display_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="date affichée"
                    ),
                ),
                # (
                #     "body",
                #     ckeditor_uploader.fields.RichTextUploadingField(
                #         blank=True, null=True, verbose_name="contenu"
                #     ),
                # ),
                (
                    "published",
                    models.BooleanField(default=False, verbose_name="publié"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blog_posts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="auteur",
                    ),
                ),
            ],
            options={
                "verbose_name": "article de blog",
                "verbose_name_plural": "articles de blog",
                "ordering": ["-display_date"],
            },
        ),
    ]
