# Generated by Django 4.2.7 on 2023-12-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0006_rename_substance_ingredient_substances_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="substance",
            name="must_specify_quantity",
            field=models.BooleanField(
                default=False, verbose_name="spécification de quantité obligatoire"
            ),
        ),
    ]
