# Generated by Django 4.2.7 on 2023-12-13 23:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0006_rename_substance_ingredient_substances_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Webinar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("modification_date", models.DateTimeField(auto_now=True)),
                ("title", models.TextField(verbose_name="titre")),
                ("start_date", models.DateTimeField(verbose_name="date de début")),
                ("end_date", models.DateTimeField(verbose_name="date de fin")),
                (
                    "tagline",
                    models.TextField(
                        blank=True, default="", verbose_name="description courte"
                    ),
                ),
                ("link", models.TextField(verbose_name="lien pour s'inscrire")),
            ],
            options={
                "verbose_name": "webinaire",
                "ordering": ["start_date"],
            },
        ),
    ]
