# Generated by Django 4.2.7 on 2023-12-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0007_alter_plantfamily_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalpopulation",
            name="name_en",
        ),
        migrations.RemoveField(
            model_name="population",
            name="name_en",
        ),
        migrations.AddField(
            model_name="historicalpopulation",
            name="is_defined_by_anses",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalpopulation",
            name="max_age",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="historicalpopulation",
            name="min_age",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="population",
            name="is_defined_by_anses",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="population",
            name="max_age",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="population",
            name="min_age",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
