# Generated by Django 5.0 on 2023-12-25 17:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0007_alter_substance_must_specify_quantity"),
        ("data", "0007_webinar"),
    ]

    operations = []
