# Generated by Django 4.2.7 on 2023-12-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0007_plantfamily_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalingredient",
            name="private_comments",
            field=models.TextField(
                blank=True, null=True, verbose_name="commentaires privés"
            ),
        ),
        migrations.AlterField(
            model_name="historicalingredient",
            name="public_comments",
            field=models.TextField(
                blank=True, null=True, verbose_name="commentaires publics"
            ),
        ),
        migrations.AlterField(
            model_name="historicalmicroorganism",
            name="private_comments",
            field=models.TextField(
                blank=True, null=True, verbose_name="commentaires privés"
            ),
        ),
        migrations.AlterField(
            model_name="historicalmicroorganism",
            name="public_comments",
            field=models.TextField(
                blank=True, null=True, verbose_name="commentaires publics"
            ),
        ),
        migrations.AlterField(
            model_name="historicalplant",
            name="private_comments",
            field=models.TextField(
                blank=True, null=True, verbose_name="commentaires privés"
            ),
        ),
        migrations.AlterField(
            model_name="historicalplant",
            name="public_comments",
            field=models.TextField(
                blank=True, null=True, verbose_name="commentaires publics"
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubstance",
            name="einec_number",
            field=models.CharField(
                blank=True, max_length=7, null=True, verbose_name="numéro EINECS"
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubstance",
            name="private_comments",
            field=models.TextField(
                blank=True, null=True, verbose_name="commentaires privés"
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubstance",
            name="public_comments",
            field=models.TextField(
                blank=True, null=True, verbose_name="commentaires publics"
            ),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="private_comments",
            field=models.TextField(
                blank=True, null=True, verbose_name="commentaires privés"
            ),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="public_comments",
            field=models.TextField(
                blank=True, null=True, verbose_name="commentaires publics"
            ),
        ),
        migrations.AlterField(
            model_name="microorganism",
            name="private_comments",
            field=models.TextField(
                blank=True, null=True, verbose_name="commentaires privés"
            ),
        ),
        migrations.AlterField(
            model_name="microorganism",
            name="public_comments",
            field=models.TextField(
                blank=True, null=True, verbose_name="commentaires publics"
            ),
        ),
        migrations.AlterField(
            model_name="plant",
            name="private_comments",
            field=models.TextField(
                blank=True, null=True, verbose_name="commentaires privés"
            ),
        ),
        migrations.AlterField(
            model_name="plant",
            name="public_comments",
            field=models.TextField(
                blank=True, null=True, verbose_name="commentaires publics"
            ),
        ),
        migrations.AlterField(
            model_name="substance",
            name="einec_number",
            field=models.CharField(
                blank=True, max_length=7, null=True, verbose_name="numéro EINECS"
            ),
        ),
        migrations.AlterField(
            model_name="substance",
            name="private_comments",
            field=models.TextField(
                blank=True, null=True, verbose_name="commentaires privés"
            ),
        ),
        migrations.AlterField(
            model_name="substance",
            name="public_comments",
            field=models.TextField(
                blank=True, null=True, verbose_name="commentaires publics"
            ),
        ),
    ]
