# Generated by Django 4.2.7 on 2023-12-27 09:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0008_merge_20231225_1858"),
        ("data", "0008_remove_historicalpopulation_name_en_and_more"),
    ]

    operations = []
