# Generated by Django 4.2.7 on 2023-12-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0009_merge_20231227_1050"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalingredient",
            name="siccrf_id",
            field=models.IntegerField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalmicroorganism",
            name="siccrf_id",
            field=models.IntegerField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalplant",
            name="siccrf_id",
            field=models.IntegerField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalplantfamily",
            name="siccrf_id",
            field=models.IntegerField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalplantpart",
            name="siccrf_id",
            field=models.IntegerField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalpopulation",
            name="siccrf_id",
            field=models.IntegerField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalsubstance",
            name="siccrf_id",
            field=models.IntegerField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="siccrf_id",
            field=models.IntegerField(
                blank=True, db_index=True, editable=False, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="microorganism",
            name="siccrf_id",
            field=models.IntegerField(
                blank=True, db_index=True, editable=False, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="plant",
            name="siccrf_id",
            field=models.IntegerField(
                blank=True, db_index=True, editable=False, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="plantfamily",
            name="siccrf_id",
            field=models.IntegerField(
                blank=True, db_index=True, editable=False, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="plantpart",
            name="siccrf_id",
            field=models.IntegerField(
                blank=True, db_index=True, editable=False, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="population",
            name="siccrf_id",
            field=models.IntegerField(
                blank=True, db_index=True, editable=False, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="substance",
            name="siccrf_id",
            field=models.IntegerField(
                blank=True, db_index=True, editable=False, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubstance",
            name="must_specify_quantity",
            field=models.BooleanField(
                default=False, verbose_name="spécification de quantité obligatoire"
            ),
        ),
    ]
