# Generated by Django 4.2.7 on 2024-01-09 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0010_historicalingredient_siccrf_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalsubstancesynonym",
            name="substance",
        ),
        migrations.RemoveField(
            model_name="substancesynonym",
            name="substance",
        ),
        migrations.AddField(
            model_name="condition",
            name="siccrf_id",
            field=models.IntegerField(
                blank=True, db_index=True, editable=False, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="historicalcondition",
            name="siccrf_id",
            field=models.IntegerField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalingredientsynonym",
            name="siccrf_id",
            field=models.IntegerField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalmicroorganismsynonym",
            name="siccrf_id",
            field=models.IntegerField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalplantsynonym",
            name="siccrf_id",
            field=models.IntegerField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalsubstancesynonym",
            name="siccrf_id",
            field=models.IntegerField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalsubstancesynonym",
            name="standard_name",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="data.substance",
                verbose_name="nom de référence",
            ),
        ),
        migrations.AddField(
            model_name="ingredientsynonym",
            name="siccrf_id",
            field=models.IntegerField(
                blank=True, db_index=True, editable=False, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="microorganismsynonym",
            name="siccrf_id",
            field=models.IntegerField(
                blank=True, db_index=True, editable=False, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="plantsynonym",
            name="siccrf_id",
            field=models.IntegerField(
                blank=True, db_index=True, editable=False, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="substancesynonym",
            name="siccrf_id",
            field=models.IntegerField(
                blank=True, db_index=True, editable=False, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="substancesynonym",
            name="standard_name",
            field=models.ForeignKey(
                default="",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="data.substance",
                verbose_name="nom de référence",
            ),
            preserve_default=False,
        ),
    ]
