# Generated by Django 4.2.7 on 2023-12-29 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0011_remove_historicalsubstancesynonym_substance_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsefulPartRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("must_be_monitored", models.BooleanField(default=False)),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("modification_date", models.DateTimeField(auto_now=True)),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="data.plant"
                    ),
                ),
                (
                    "plantpart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="data.plantpart"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalUsefulPartRelation",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("must_be_monitored", models.BooleanField(default=False)),
                ("creation_date", models.DateTimeField(blank=True, editable=False)),
                ("modification_date", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="data.plant",
                    ),
                ),
                (
                    "plantpart",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="data.plantpart",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical useful part relation",
                "verbose_name_plural": "historical useful part relations",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.RemoveField(
            model_name='plant',
            name='useful_parts',
        ),
        migrations.AddField(
            model_name='plant',
            name='useful_parts',
            field=models.ManyToManyField(
                through="data.UsefulPartRelation",
                to="data.plantpart",
                verbose_name="partie utile",
            ),
        ),
    ]
