# Generated by Django 4.2.7 on 2024-01-10 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0012_alter_substancesynonym_standard_name_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="HistoricalUsefulPartRelation",
            new_name="HistoricalUsefulPart",
        ),
        migrations.RenameModel(
            old_name="UsefulPartRelation",
            new_name="UsefulPart",
        ),
        migrations.AlterModelOptions(
            name="historicalusefulpart",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical useful part",
                "verbose_name_plural": "historical useful parts",
            },
        ),
        migrations.AlterField(
            model_name="substancesynonym",
            name="standard_name",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="data.substance",
                verbose_name="nom de référence",
            ),
            preserve_default=False,
        ),
    ]
