# Generated by Django 5.0.2 on 2024-02-13 16:39

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0016_alter_historicalpart_is_useful_alter_part_is_useful"),
    ]

    operations = [UnaccentExtension()]
