# Generated by Django 5.0.2 on 2024-02-20 09:08
# Modifié manuellement pour
# * RenameField les champs modifiés plutôt que les RemoveField + AddField
# * AlterTable <ingr>_substances en <Ingr>SubstanceRelation avec ajout des champs modification_date, creation_date, siccrf_is_related, CA_is_related
# * set_default à True pour les champs siccrf_is_related dans les tables <Ingr>SubstanceRelation

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0017_auto_20240213_1739"),
    ]

    def set_default(apps, schema_editor):
        IngredientSubstanceRelation = apps.get_model("data", "IngredientSubstanceRelation")
        MicroorganismSubstanceRelation = apps.get_model("data", "MicroorganismSubstanceRelation")
        PlantSubstanceRelation = apps.get_model("data", "PlantSubstanceRelation")
        for relation in [IngredientSubstanceRelation, MicroorganismSubstanceRelation, PlantSubstanceRelation]:
            for ingr_subst_rel in relation.objects.all().iterator():
                ingr_subst_rel.siccrf_is_related = True
                ingr_subst_rel.save()

    def reverse_set_default(apps, schema_editor):
        pass

    ingredient_substance_state_operations = [
        migrations.CreateModel(
            name="IngredientSubstanceRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data.ingredient",
                    ),
                ),
                (
                    "substance",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="data.substance"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="substances",
            field=models.ManyToManyField(through="data.IngredientSubstanceRelation", to="data.substance"),
        ),
        migrations.AlterModelTable(
            name="IngredientSubstanceRelation",
            table="data_ingredient_substances",
        ),
    ]
    microorganism_substance_state_operations = [
        migrations.CreateModel(
            name="MicroorganismSubstanceRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "microorganism",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data.microorganism",
                    ),
                ),
                (
                    "substance",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="data.substance"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="microorganism",
            name="substances",
            field=models.ManyToManyField(through="data.MicroorganismSubstanceRelation", to="data.substance"),
        ),
        migrations.AlterModelTable(
            name="MicroorganismSubstanceRelation",
            table="data_microorganism_substances",
        ),
    ]
    plant_substance_state_operations = [
        migrations.CreateModel(
            name="PlantSubstanceRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data.plant",
                    ),
                ),
                (
                    "substance",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="data.substance"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="plant",
            name="substances",
            field=models.ManyToManyField(through="data.PlantSubstanceRelation", to="data.substance"),
        ),
        migrations.AlterModelTable(
            name="PlantSubstanceRelation",
            table="data_plant_substances",
        ),
    ]
    operations = [
        # historicalmicroorganism
        migrations.RenameField(
            model_name="historicalmicroorganism",
            old_name="genre",
            new_name="siccrf_genre",
        ),
        migrations.RenameField(
            model_name="historicalmicroorganism",
            old_name="name",
            new_name="siccrf_name",
        ),
        migrations.RenameField(
            model_name="historicalmicroorganism",
            old_name="name_en",
            new_name="siccrf_name_en",
        ),
        migrations.RenameField(
            model_name="historicalmicroorganism",
            old_name="is_obsolete",
            new_name="siccrf_is_obsolete",
        ),
        migrations.RenameField(
            model_name="historicalmicroorganism",
            old_name="private_comments",
            new_name="siccrf_private_comments",
        ),
        migrations.RenameField(
            model_name="historicalmicroorganism",
            old_name="public_comments",
            new_name="siccrf_public_comments",
        ),
        migrations.AddField(
            model_name="historicalmicroorganism",
            name="CA_genre",
            field=models.TextField(default="", verbose_name="genre de micro-organisme"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalmicroorganism",
            name="CA_is_obsolete",
            field=models.BooleanField(default=None, null=True, verbose_name="objet obsolète selon CA"),
        ),
        migrations.AddField(
            model_name="historicalmicroorganism",
            name="CA_name",
            field=models.TextField(default="", verbose_name="nom CA"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalmicroorganism",
            name="CA_private_comments",
            field=models.TextField(blank=True, verbose_name="commentaires privés SICCRF"),
        ),
        migrations.AddField(
            model_name="historicalmicroorganism",
            name="CA_public_comments",
            field=models.TextField(blank=True, verbose_name="commentaires publics SICCRF"),
        ),
        migrations.AddField(
            model_name="historicalmicroorganism",
            name="siccrf_private_comments_en",
            field=models.TextField(
                blank=True,
                editable=False,
                verbose_name="commentaires privés en anglais SICCRF",
            ),
        ),
        migrations.AddField(
            model_name="historicalmicroorganism",
            name="siccrf_public_comments_en",
            field=models.TextField(
                blank=True,
                editable=False,
                verbose_name="commentaires publics en anglais SICCRF",
            ),
        ),
        # historicalpart
        migrations.RenameField(
            model_name="historicalpart",
            old_name="is_useful",
            new_name="siccrf_is_useful",
        ),
        migrations.RenameField(
            model_name="historicalpart",
            old_name="must_be_monitored",
            new_name="siccrf_must_be_monitored",
        ),
        migrations.AddField(
            model_name="historicalpart",
            name="CA_is_useful",
            field=models.BooleanField(default=None, null=True, verbose_name="🍵 utile ?"),
        ),
        migrations.AddField(
            model_name="historicalpart",
            name="CA_must_be_monitored",
            field=models.BooleanField(default=None, null=True, verbose_name="⚠️ à surveiller ?"),
        ),
        # historicalplantfamily
        migrations.RenameField(
            model_name="historicalplantfamily",
            old_name="name_en",
            new_name="siccrf_name_en",
        ),
        migrations.RenameField(
            model_name="historicalplantfamily",
            old_name="is_obsolete",
            new_name="siccrf_is_obsolete",
        ),
        migrations.RenameField(
            model_name="historicalplantfamily",
            old_name="name",
            new_name="siccrf_name",
        ),
        migrations.AddField(
            model_name="historicalplantfamily",
            name="CA_is_obsolete",
            field=models.BooleanField(default=None, null=True, verbose_name="objet obsolète selon CA"),
        ),
        migrations.AddField(
            model_name="historicalplantfamily",
            name="CA_name",
            field=models.TextField(default="", verbose_name="nom CA"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="historicalplantfamily",
            name="siccrf_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                editable=False,
                null=True,
                verbose_name="id dans les tables et tables relationnelles SICCRF",
            ),
        ),
        # historicalplantpart
        migrations.RenameField(
            model_name="historicalplantpart",
            old_name="name_en",
            new_name="siccrf_name_en",
        ),
        migrations.RenameField(
            model_name="historicalplantpart",
            old_name="is_obsolete",
            new_name="siccrf_is_obsolete",
        ),
        migrations.RenameField(
            model_name="historicalplantpart",
            old_name="name",
            new_name="siccrf_name",
        ),
        migrations.AddField(
            model_name="historicalplantpart",
            name="CA_is_obsolete",
            field=models.BooleanField(default=None, null=True, verbose_name="objet obsolète selon CA"),
        ),
        migrations.AddField(
            model_name="historicalplantpart",
            name="CA_name",
            field=models.TextField(default="", verbose_name="nom CA"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="historicalplantpart",
            name="siccrf_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                editable=False,
                null=True,
                verbose_name="id dans les tables et tables relationnelles SICCRF",
            ),
        ),
        # historicalsubstance
        migrations.RenameField(
            model_name="historicalsubstance",
            old_name="cas_number",
            new_name="siccrf_cas_number",
        ),
        migrations.RenameField(
            model_name="historicalsubstance",
            old_name="einec_number",
            new_name="siccrf_einec_number",
        ),
        migrations.RenameField(
            model_name="historicalsubstance",
            old_name="max_quantity",
            new_name="siccrf_max_quantity",
        ),
        migrations.RenameField(
            model_name="historicalsubstance",
            old_name="must_specify_quantity",
            new_name="siccrf_must_specify_quantity",
        ),
        migrations.RenameField(
            model_name="historicalsubstance",
            old_name="name_en",
            new_name="siccrf_name_en",
        ),
        migrations.RenameField(
            model_name="historicalsubstance",
            old_name="name",
            new_name="siccrf_name",
        ),
        migrations.RenameField(
            model_name="historicalsubstance",
            old_name="nutritional_reference",
            new_name="siccrf_nutritional_reference",
        ),
        migrations.RenameField(
            model_name="historicalsubstance",
            old_name="source",
            new_name="siccrf_source",
        ),
        migrations.RenameField(
            model_name="historicalsubstance",
            old_name="is_obsolete",
            new_name="siccrf_is_obsolete",
        ),
        migrations.RenameField(
            model_name="historicalsubstance",
            old_name="private_comments",
            new_name="siccrf_private_comments",
        ),
        migrations.RenameField(
            model_name="historicalsubstance",
            old_name="public_comments",
            new_name="siccrf_public_comments",
        ),
        migrations.RemoveField(
            model_name="historicalsubstance",
            name="min_quantity",
        ),
        migrations.AddField(
            model_name="historicalsubstance",
            name="CA_cas_number",
            field=models.CharField(blank=True, max_length=10, verbose_name="numéro CAS"),
        ),
        migrations.AddField(
            model_name="historicalsubstance",
            name="CA_einec_number",
            field=models.CharField(blank=True, max_length=7, verbose_name="numéro EINECS"),
        ),
        migrations.AddField(
            model_name="historicalsubstance",
            name="CA_is_obsolete",
            field=models.BooleanField(default=None, null=True, verbose_name="objet obsolète selon CA"),
        ),
        migrations.AddField(
            model_name="historicalsubstance",
            name="CA_max_quantity",
            field=models.FloatField(blank=True, null=True, verbose_name="quantité maximale autorisée"),
        ),
        migrations.AddField(
            model_name="historicalsubstance",
            name="CA_must_specify_quantity",
            field=models.BooleanField(default=None, null=True, verbose_name="spécification de quantité obligatoire"),
        ),
        migrations.AddField(
            model_name="historicalsubstance",
            name="CA_name",
            field=models.TextField(default="", verbose_name="nom CA"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalsubstance",
            name="CA_nutritional_reference",
            field=models.FloatField(blank=True, null=True, verbose_name="apport nutritionnel conseillé"),
        ),
        migrations.AddField(
            model_name="historicalsubstance",
            name="CA_private_comments",
            field=models.TextField(blank=True, verbose_name="commentaires privés SICCRF"),
        ),
        migrations.AddField(
            model_name="historicalsubstance",
            name="CA_public_comments",
            field=models.TextField(blank=True, verbose_name="commentaires publics SICCRF"),
        ),
        migrations.AddField(
            model_name="historicalsubstance",
            name="CA_source",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="historicalsubstance",
            name="siccrf_private_comments_en",
            field=models.TextField(
                blank=True,
                editable=False,
                verbose_name="commentaires privés en anglais SICCRF",
            ),
        ),
        migrations.AddField(
            model_name="historicalsubstance",
            name="siccrf_public_comments_en",
            field=models.TextField(
                blank=True,
                editable=False,
                verbose_name="commentaires publics en anglais SICCRF",
            ),
        ),
        # condition
        migrations.RenameField(
            model_name="condition",
            old_name="name",
            new_name="siccrf_name",
        ),
        migrations.RenameField(
            model_name="condition",
            old_name="name_en",
            new_name="siccrf_name_en",
        ),
        migrations.RenameField(
            model_name="condition",
            old_name="is_obsolete",
            new_name="siccrf_is_obsolete",
        ),
        migrations.AddField(
            model_name="condition",
            name="CA_is_obsolete",
            field=models.BooleanField(default=None, null=True, verbose_name="objet obsolète selon CA"),
        ),
        migrations.AddField(
            model_name="condition",
            name="CA_name",
            field=models.TextField(default="", verbose_name="nom CA"),
            preserve_default=False,
        ),
        # ingredient
        migrations.RenameField(
            model_name="ingredient",
            old_name="description",
            new_name="siccrf_description",
        ),
        migrations.RenameField(
            model_name="ingredient",
            old_name="name_en",
            new_name="siccrf_name_en",
        ),
        migrations.RenameField(
            model_name="ingredient",
            old_name="is_obsolete",
            new_name="siccrf_is_obsolete",
        ),
        migrations.RenameField(
            model_name="ingredient",
            old_name="name",
            new_name="siccrf_name",
        ),
        migrations.RenameField(
            model_name="ingredient",
            old_name="private_comments",
            new_name="siccrf_private_comments",
        ),
        migrations.RenameField(
            model_name="ingredient",
            old_name="public_comments",
            new_name="siccrf_public_comments",
        ),
        migrations.RemoveField(
            model_name="ingredient",
            name="observation",
        ),
        migrations.AddField(
            model_name="ingredient",
            name="CA_is_obsolete",
            field=models.BooleanField(default=None, null=True, verbose_name="objet obsolète selon CA"),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="CA_name",
            field=models.TextField(default="", verbose_name="nom CA"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ingredient",
            name="CA_private_comments",
            field=models.TextField(blank=True, verbose_name="commentaires privés SICCRF"),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="CA_public_comments",
            field=models.TextField(blank=True, verbose_name="commentaires publics SICCRF"),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="siccrf_private_comments_en",
            field=models.TextField(
                blank=True,
                editable=False,
                verbose_name="commentaires privés en anglais SICCRF",
            ),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="siccrf_public_comments_en",
            field=models.TextField(
                blank=True,
                editable=False,
                verbose_name="commentaires publics en anglais SICCRF",
            ),
        ),
        # microorganism
        migrations.RenameField(
            model_name="microorganism",
            old_name="genre",
            new_name="siccrf_genre",
        ),
        migrations.RenameField(
            model_name="microorganism",
            old_name="name_en",
            new_name="siccrf_name_en",
        ),
        migrations.RenameField(
            model_name="microorganism",
            old_name="is_obsolete",
            new_name="siccrf_is_obsolete",
        ),
        migrations.RenameField(
            model_name="microorganism",
            old_name="name",
            new_name="siccrf_name",
        ),
        migrations.RenameField(
            model_name="microorganism",
            old_name="private_comments",
            new_name="siccrf_private_comments",
        ),
        migrations.RenameField(
            model_name="microorganism",
            old_name="public_comments",
            new_name="siccrf_public_comments",
        ),
        migrations.AddField(
            model_name="microorganism",
            name="CA_genre",
            field=models.TextField(default="", verbose_name="genre de micro-organisme"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="microorganism",
            name="CA_is_obsolete",
            field=models.BooleanField(default=None, null=True, verbose_name="objet obsolète selon CA"),
        ),
        migrations.AddField(
            model_name="microorganism",
            name="CA_name",
            field=models.TextField(default="", verbose_name="nom CA"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="microorganism",
            name="CA_private_comments",
            field=models.TextField(blank=True, verbose_name="commentaires privés SICCRF"),
        ),
        migrations.AddField(
            model_name="microorganism",
            name="CA_public_comments",
            field=models.TextField(blank=True, verbose_name="commentaires publics SICCRF"),
        ),
        migrations.AddField(
            model_name="microorganism",
            name="siccrf_private_comments_en",
            field=models.TextField(
                blank=True,
                editable=False,
                verbose_name="commentaires privés en anglais SICCRF",
            ),
        ),
        migrations.AddField(
            model_name="microorganism",
            name="siccrf_public_comments_en",
            field=models.TextField(
                blank=True,
                editable=False,
                verbose_name="commentaires publics en anglais SICCRF",
            ),
        ),
        # part
        migrations.RenameField(
            model_name="part",
            old_name="is_useful",
            new_name="siccrf_is_useful",
        ),
        migrations.RenameField(
            model_name="part",
            old_name="must_be_monitored",
            new_name="siccrf_must_be_monitored",
        ),
        migrations.AddField(
            model_name="part",
            name="CA_is_useful",
            field=models.BooleanField(default=None, null=True, verbose_name="🍵 utile ?"),
        ),
        migrations.AddField(
            model_name="part",
            name="CA_must_be_monitored",
            field=models.BooleanField(default=None, null=True, verbose_name="⚠️ à surveiller ?"),
        ),
        # plantfamily
        migrations.RenameField(
            model_name="plantfamily",
            old_name="name_en",
            new_name="siccrf_name_en",
        ),
        migrations.RenameField(
            model_name="plantfamily",
            old_name="is_obsolete",
            new_name="siccrf_is_obsolete",
        ),
        migrations.RenameField(
            model_name="plantfamily",
            old_name="name",
            new_name="siccrf_name",
        ),
        migrations.AddField(
            model_name="plantfamily",
            name="CA_is_obsolete",
            field=models.BooleanField(default=None, null=True, verbose_name="objet obsolète selon CA"),
        ),
        migrations.AddField(
            model_name="plantfamily",
            name="CA_name",
            field=models.TextField(default="", verbose_name="nom CA"),
            preserve_default=False,
        ),
        # plantpart
        migrations.RenameField(
            model_name="plantpart",
            old_name="name_en",
            new_name="siccrf_name_en",
        ),
        migrations.RenameField(
            model_name="plantpart",
            old_name="name",
            new_name="siccrf_name",
        ),
        migrations.RenameField(
            model_name="plantpart",
            old_name="is_obsolete",
            new_name="siccrf_is_obsolete",
        ),
        migrations.AddField(
            model_name="plantpart",
            name="CA_is_obsolete",
            field=models.BooleanField(default=None, null=True, verbose_name="objet obsolète selon CA"),
        ),
        migrations.AddField(
            model_name="plantpart",
            name="CA_name",
            field=models.TextField(default="", verbose_name="nom CA"),
            preserve_default=False,
        ),
        # substance
        migrations.RenameField(
            model_name="substance",
            old_name="cas_number",
            new_name="siccrf_cas_number",
        ),
        migrations.RenameField(
            model_name="substance",
            old_name="einec_number",
            new_name="siccrf_einec_number",
        ),
        migrations.RenameField(
            model_name="substance",
            old_name="max_quantity",
            new_name="siccrf_max_quantity",
        ),
        migrations.RenameField(
            model_name="substance",
            old_name="must_specify_quantity",
            new_name="siccrf_must_specify_quantity",
        ),
        migrations.RenameField(
            model_name="substance",
            old_name="name_en",
            new_name="siccrf_name_en",
        ),
        migrations.RenameField(
            model_name="substance",
            old_name="name",
            new_name="siccrf_name",
        ),
        migrations.RenameField(
            model_name="substance",
            old_name="is_obsolete",
            new_name="siccrf_is_obsolete",
        ),
        migrations.RenameField(
            model_name="substance",
            old_name="nutritional_reference",
            new_name="siccrf_nutritional_reference",
        ),
        migrations.RenameField(
            model_name="substance",
            old_name="source",
            new_name="siccrf_source",
        ),
        migrations.RenameField(
            model_name="substance",
            old_name="public_comments",
            new_name="siccrf_public_comments",
        ),
        migrations.RenameField(
            model_name="substance",
            old_name="private_comments",
            new_name="siccrf_private_comments",
        ),
        migrations.RemoveField(
            model_name="substance",
            name="min_quantity",
        ),
        migrations.AddField(
            model_name="substance",
            name="CA_cas_number",
            field=models.CharField(blank=True, max_length=10, verbose_name="numéro CAS"),
        ),
        migrations.AddField(
            model_name="substance",
            name="CA_einec_number",
            field=models.CharField(blank=True, max_length=7, verbose_name="numéro EINECS"),
        ),
        migrations.AddField(
            model_name="substance",
            name="CA_is_obsolete",
            field=models.BooleanField(default=None, null=True, verbose_name="objet obsolète selon CA"),
        ),
        migrations.AddField(
            model_name="substance",
            name="CA_max_quantity",
            field=models.FloatField(blank=True, null=True, verbose_name="quantité maximale autorisée"),
        ),
        migrations.AddField(
            model_name="substance",
            name="CA_must_specify_quantity",
            field=models.BooleanField(default=None, null=True, verbose_name="spécification de quantité obligatoire"),
        ),
        migrations.AddField(
            model_name="substance",
            name="CA_name",
            field=models.TextField(default="", verbose_name="nom CA"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="substance",
            name="CA_nutritional_reference",
            field=models.FloatField(blank=True, null=True, verbose_name="apport nutritionnel conseillé"),
        ),
        migrations.AddField(
            model_name="substance",
            name="CA_private_comments",
            field=models.TextField(blank=True, verbose_name="commentaires privés SICCRF"),
        ),
        migrations.AddField(
            model_name="substance",
            name="CA_public_comments",
            field=models.TextField(blank=True, verbose_name="commentaires publics SICCRF"),
        ),
        migrations.AddField(
            model_name="substance",
            name="CA_source",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="substance",
            name="siccrf_private_comments_en",
            field=models.TextField(
                blank=True,
                editable=False,
                verbose_name="commentaires privés en anglais SICCRF",
            ),
        ),
        migrations.AddField(
            model_name="substance",
            name="siccrf_public_comments_en",
            field=models.TextField(
                blank=True,
                editable=False,
                verbose_name="commentaires publics en anglais SICCRF",
            ),
        ),
        # historicalcondition
        migrations.RenameField(
            model_name="historicalcondition",
            old_name="is_obsolete",
            new_name="siccrf_is_obsolete",
        ),
        migrations.RenameField(
            model_name="historicalcondition",
            old_name="name",
            new_name="siccrf_name",
        ),
        migrations.RenameField(
            model_name="historicalcondition",
            old_name="name_en",
            new_name="siccrf_name_en",
        ),
        migrations.AddField(
            model_name="historicalcondition",
            name="CA_is_obsolete",
            field=models.BooleanField(default=None, null=True, verbose_name="objet obsolète selon CA"),
        ),
        migrations.AddField(
            model_name="historicalcondition",
            name="CA_name",
            field=models.TextField(default="", verbose_name="nom CA"),
            preserve_default=False,
        ),
        # historicalingredient
        migrations.RenameField(
            model_name="historicalingredient",
            old_name="description",
            new_name="siccrf_description",
        ),
        migrations.RenameField(
            model_name="historicalingredient",
            old_name="is_obsolete",
            new_name="siccrf_is_obsolete",
        ),
        migrations.RenameField(
            model_name="historicalingredient",
            old_name="name",
            new_name="siccrf_name",
        ),
        migrations.RenameField(
            model_name="historicalingredient",
            old_name="name_en",
            new_name="siccrf_name_en",
        ),
        migrations.RenameField(
            model_name="historicalingredient",
            old_name="private_comments",
            new_name="siccrf_private_comments",
        ),
        migrations.RenameField(
            model_name="historicalingredient",
            old_name="public_comments",
            new_name="siccrf_public_comments",
        ),
        migrations.RemoveField(
            model_name="historicalingredient",
            name="observation",
        ),
        migrations.AddField(
            model_name="historicalingredient",
            name="CA_is_obsolete",
            field=models.BooleanField(default=None, null=True, verbose_name="objet obsolète selon CA"),
        ),
        migrations.AddField(
            model_name="historicalingredient",
            name="CA_name",
            field=models.TextField(default="", verbose_name="nom CA"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalingredient",
            name="CA_private_comments",
            field=models.TextField(blank=True, verbose_name="commentaires privés SICCRF"),
        ),
        migrations.AddField(
            model_name="historicalingredient",
            name="CA_public_comments",
            field=models.TextField(blank=True, verbose_name="commentaires publics SICCRF"),
        ),
        migrations.AddField(
            model_name="historicalingredient",
            name="siccrf_private_comments_en",
            field=models.TextField(
                blank=True,
                editable=False,
                verbose_name="commentaires privés en anglais SICCRF",
            ),
        ),
        migrations.AddField(
            model_name="historicalingredient",
            name="siccrf_public_comments_en",
            field=models.TextField(
                blank=True,
                editable=False,
                verbose_name="commentaires publics en anglais SICCRF",
            ),
        ),
        # historicalingredientsynonym
        migrations.RenameField(
            model_name="historicalingredientsynonym",
            old_name="is_obsolete",
            new_name="siccrf_is_obsolete",
        ),
        migrations.RenameField(
            model_name="historicalingredientsynonym",
            old_name="name",
            new_name="siccrf_name",
        ),
        migrations.AddField(
            model_name="historicalingredientsynonym",
            name="CA_is_obsolete",
            field=models.BooleanField(default=None, null=True, verbose_name="objet obsolète selon CA"),
        ),
        migrations.AddField(
            model_name="historicalingredientsynonym",
            name="CA_name",
            field=models.TextField(default="", verbose_name="nom CA"),
            preserve_default=False,
        ),
        # historicalmicroorganismsynonym
        migrations.RenameField(
            model_name="historicalmicroorganismsynonym",
            old_name="is_obsolete",
            new_name="siccrf_is_obsolete",
        ),
        migrations.RenameField(
            model_name="historicalmicroorganismsynonym",
            old_name="name",
            new_name="siccrf_name",
        ),
        migrations.AddField(
            model_name="historicalmicroorganismsynonym",
            name="CA_is_obsolete",
            field=models.BooleanField(default=None, null=True, verbose_name="objet obsolète selon CA"),
        ),
        migrations.AddField(
            model_name="historicalmicroorganismsynonym",
            name="CA_name",
            field=models.TextField(default="", verbose_name="nom CA"),
            preserve_default=False,
        ),
        # historicalplant
        migrations.RenameField(
            model_name="historicalplant",
            old_name="family",
            new_name="siccrf_family",
        ),
        migrations.RenameField(
            model_name="historicalplant",
            old_name="is_obsolete",
            new_name="siccrf_is_obsolete",
        ),
        migrations.RenameField(
            model_name="historicalplant",
            old_name="name",
            new_name="siccrf_name",
        ),
        migrations.RenameField(
            model_name="historicalplant",
            old_name="private_comments",
            new_name="siccrf_private_comments",
        ),
        migrations.RenameField(
            model_name="historicalplant",
            old_name="public_comments",
            new_name="siccrf_public_comments",
        ),
        migrations.AddField(
            model_name="historicalplant",
            name="CA_is_obsolete",
            field=models.BooleanField(default=None, null=True, verbose_name="objet obsolète selon CA"),
        ),
        migrations.AddField(
            model_name="historicalplant",
            name="CA_name",
            field=models.TextField(default="", verbose_name="nom CA"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalplant",
            name="CA_private_comments",
            field=models.TextField(blank=True, verbose_name="commentaires privés SICCRF"),
        ),
        migrations.AddField(
            model_name="historicalplant",
            name="CA_public_comments",
            field=models.TextField(blank=True, verbose_name="commentaires publics SICCRF"),
        ),
        # TODO rien ne change
        # migrations.AddField(
        #     model_name="historicalplant",
        #     name="siccrf_family",
        #     field=models.ForeignKey(
        #         blank=True,
        #         db_constraint=False,
        #         null=True,
        #         on_delete=django.db.models.deletion.DO_NOTHING,
        #         related_name="+",
        #         to="data.plantfamily",
        #         verbose_name="famille de plante (selon la base SICCRF)",
        #     ),
        # ),
        migrations.AddField(
            model_name="historicalplant",
            name="siccrf_private_comments_en",
            field=models.TextField(
                blank=True,
                editable=False,
                verbose_name="commentaires privés en anglais SICCRF",
            ),
        ),
        migrations.AddField(
            model_name="historicalplant",
            name="siccrf_public_comments_en",
            field=models.TextField(
                blank=True,
                editable=False,
                verbose_name="commentaires publics en anglais SICCRF",
            ),
        ),
        migrations.AddField(
            model_name="historicalplant",
            name="CA_family",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="data.plantfamily",
                verbose_name="famille de plante",
            ),
        ),
        # historicalplantsynonym
        migrations.RenameField(
            model_name="historicalplantsynonym",
            old_name="is_obsolete",
            new_name="siccrf_is_obsolete",
        ),
        migrations.RenameField(
            model_name="historicalplantsynonym",
            old_name="name",
            new_name="siccrf_name",
        ),
        migrations.AddField(
            model_name="historicalplantsynonym",
            name="CA_is_obsolete",
            field=models.BooleanField(default=None, null=True, verbose_name="objet obsolète selon CA"),
        ),
        migrations.AddField(
            model_name="historicalplantsynonym",
            name="CA_name",
            field=models.TextField(default="", verbose_name="nom CA"),
            preserve_default=False,
        ),
        # historicalpopulation
        migrations.RenameField(
            model_name="historicalpopulation",
            old_name="is_obsolete",
            new_name="siccrf_is_obsolete",
        ),
        migrations.RenameField(
            model_name="historicalpopulation",
            old_name="name",
            new_name="siccrf_name",
        ),
        migrations.AddField(
            model_name="historicalpopulation",
            name="CA_is_obsolete",
            field=models.BooleanField(default=None, null=True, verbose_name="objet obsolète selon CA"),
        ),
        migrations.AddField(
            model_name="historicalpopulation",
            name="CA_name",
            field=models.TextField(default="", verbose_name="nom CA"),
            preserve_default=False,
        ),
        # historicalsubstancesynonym
        migrations.RenameField(
            model_name="historicalsubstancesynonym", old_name="is_obsolete", new_name="siccrf_is_obsolete"
        ),
        migrations.RenameField(model_name="historicalsubstancesynonym", old_name="name", new_name="siccrf_name"),
        migrations.AddField(
            model_name="historicalsubstancesynonym",
            name="CA_is_obsolete",
            field=models.BooleanField(default=None, null=True, verbose_name="objet obsolète selon CA"),
        ),
        migrations.AddField(
            model_name="historicalsubstancesynonym",
            name="CA_name",
            field=models.TextField(default="", verbose_name="nom CA"),
            preserve_default=False,
        ),
        # ingredientsynonym
        migrations.RenameField(model_name="ingredientsynonym", old_name="is_obsolete", new_name="siccrf_is_obsolete"),
        migrations.RenameField(model_name="ingredientsynonym", old_name="name", new_name="siccrf_name"),
        migrations.AddField(
            model_name="ingredientsynonym",
            name="CA_is_obsolete",
            field=models.BooleanField(default=None, null=True, verbose_name="objet obsolète selon CA"),
        ),
        migrations.AddField(
            model_name="ingredientsynonym",
            name="CA_name",
            field=models.TextField(default="", verbose_name="nom CA"),
            preserve_default=False,
        ),
        # microorganismsynonym
        migrations.RenameField(
            model_name="microorganismsynonym", old_name="is_obsolete", new_name="siccrf_is_obsolete"
        ),
        migrations.RenameField(model_name="microorganismsynonym", old_name="name", new_name="siccrf_name"),
        migrations.AddField(
            model_name="microorganismsynonym",
            name="CA_is_obsolete",
            field=models.BooleanField(default=None, null=True, verbose_name="objet obsolète selon CA"),
        ),
        migrations.AddField(
            model_name="microorganismsynonym",
            name="CA_name",
            field=models.TextField(default="", verbose_name="nom CA"),
            preserve_default=False,
        ),
        # plant
        migrations.RenameField(model_name="plant", old_name="family", new_name="siccrf_family"),
        migrations.RenameField(model_name="plant", old_name="is_obsolete", new_name="siccrf_is_obsolete"),
        migrations.RenameField(model_name="plant", old_name="name", new_name="siccrf_name"),
        migrations.RenameField(model_name="plant", old_name="private_comments", new_name="siccrf_private_comments"),
        migrations.RenameField(model_name="plant", old_name="public_comments", new_name="siccrf_public_comments"),
        migrations.AddField(
            model_name="plant",
            name="CA_is_obsolete",
            field=models.BooleanField(default=None, null=True, verbose_name="objet obsolète selon CA"),
        ),
        migrations.AddField(
            model_name="plant",
            name="CA_name",
            field=models.TextField(default="", verbose_name="nom CA"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="plant",
            name="CA_private_comments",
            field=models.TextField(blank=True, verbose_name="commentaires privés SICCRF"),
        ),
        migrations.AddField(
            model_name="plant",
            name="CA_public_comments",
            field=models.TextField(blank=True, verbose_name="commentaires publics SICCRF"),
        ),
        # TODO
        migrations.AlterField(
            model_name="plant",
            name="siccrf_family",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="siccrf_plant_set",
                to="data.plantfamily",
                verbose_name="famille de plante (selon la base SICCRF)",
            ),
        ),
        migrations.AddField(
            model_name="plant",
            name="siccrf_private_comments_en",
            field=models.TextField(
                blank=True,
                editable=False,
                verbose_name="commentaires privés en anglais SICCRF",
            ),
        ),
        migrations.AddField(
            model_name="plant",
            name="siccrf_public_comments_en",
            field=models.TextField(
                blank=True,
                editable=False,
                verbose_name="commentaires publics en anglais SICCRF",
            ),
        ),
        migrations.AddField(
            model_name="plant",
            name="CA_family",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="plant_set",
                to="data.plantfamily",
                verbose_name="famille de plante",
            ),
        ),
        # plantsynonym
        migrations.RenameField(model_name="plantsynonym", old_name="is_obsolete", new_name="siccrf_is_obsolete"),
        migrations.RenameField(model_name="plantsynonym", old_name="name", new_name="siccrf_name"),
        migrations.AddField(
            model_name="plantsynonym",
            name="CA_name",
            field=models.TextField(default="", verbose_name="nom CA"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="plantsynonym",
            name="CA_is_obsolete",
            field=models.BooleanField(default=None, null=True, verbose_name="objet obsolète selon CA"),
        ),
        # population
        migrations.RenameField(model_name="population", old_name="is_obsolete", new_name="siccrf_is_obsolete"),
        migrations.RenameField(model_name="population", old_name="name", new_name="siccrf_name"),
        migrations.AddField(
            model_name="population",
            name="CA_is_obsolete",
            field=models.BooleanField(default=None, null=True, verbose_name="objet obsolète selon CA"),
        ),
        migrations.AddField(
            model_name="population",
            name="CA_name",
            field=models.TextField(default="", verbose_name="nom CA"),
            preserve_default=False,
        ),
        # substancesynonym
        migrations.RenameField(model_name="substancesynonym", old_name="is_obsolete", new_name="siccrf_is_obsolete"),
        migrations.RenameField(model_name="substancesynonym", old_name="name", new_name="siccrf_name"),
        migrations.AddField(
            model_name="substancesynonym",
            name="CA_is_obsolete",
            field=models.BooleanField(default=None, null=True, verbose_name="objet obsolète selon CA"),
        ),
        migrations.AddField(
            model_name="substancesynonym",
            name="CA_name",
            field=models.TextField(default="", verbose_name="nom CA"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="condition",
            name="siccrf_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                editable=False,
                null=True,
                unique=True,
                verbose_name="id dans les tables et tables relationnelles SICCRF",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcondition",
            name="siccrf_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                editable=False,
                null=True,
                verbose_name="id dans les tables et tables relationnelles SICCRF",
            ),
        ),
        migrations.AlterField(
            model_name="historicalingredient",
            name="siccrf_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                editable=False,
                null=True,
                verbose_name="id dans les tables et tables relationnelles SICCRF",
            ),
        ),
        migrations.AlterField(
            model_name="historicalingredientsynonym",
            name="siccrf_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                editable=False,
                null=True,
                verbose_name="id dans les tables et tables relationnelles SICCRF",
            ),
        ),
        migrations.AlterField(
            model_name="historicalmicroorganism",
            name="siccrf_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                editable=False,
                null=True,
                verbose_name="id dans les tables et tables relationnelles SICCRF",
            ),
        ),
        migrations.AlterField(
            model_name="historicalmicroorganismsynonym",
            name="siccrf_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                editable=False,
                null=True,
                verbose_name="id dans les tables et tables relationnelles SICCRF",
            ),
        ),
        migrations.AlterField(
            model_name="historicalplant",
            name="siccrf_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                editable=False,
                null=True,
                verbose_name="id dans les tables et tables relationnelles SICCRF",
            ),
        ),
        migrations.AlterField(
            model_name="historicalplantsynonym",
            name="siccrf_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                editable=False,
                null=True,
                verbose_name="id dans les tables et tables relationnelles SICCRF",
            ),
        ),
        migrations.AlterField(
            model_name="historicalpopulation",
            name="siccrf_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                editable=False,
                null=True,
                verbose_name="id dans les tables et tables relationnelles SICCRF",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubstance",
            name="siccrf_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                editable=False,
                null=True,
                verbose_name="id dans les tables et tables relationnelles SICCRF",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubstancesynonym",
            name="siccrf_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                editable=False,
                null=True,
                verbose_name="id dans les tables et tables relationnelles SICCRF",
            ),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="siccrf_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                editable=False,
                null=True,
                unique=True,
                verbose_name="id dans les tables et tables relationnelles SICCRF",
            ),
        ),
        migrations.AlterField(
            model_name="ingredientsynonym",
            name="siccrf_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                editable=False,
                null=True,
                unique=True,
                verbose_name="id dans les tables et tables relationnelles SICCRF",
            ),
        ),
        migrations.AlterField(
            model_name="microorganism",
            name="siccrf_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                editable=False,
                null=True,
                unique=True,
                verbose_name="id dans les tables et tables relationnelles SICCRF",
            ),
        ),
        migrations.AlterField(
            model_name="microorganismsynonym",
            name="siccrf_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                editable=False,
                null=True,
                unique=True,
                verbose_name="id dans les tables et tables relationnelles SICCRF",
            ),
        ),
        migrations.AlterField(
            model_name="plant",
            name="siccrf_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                editable=False,
                null=True,
                unique=True,
                verbose_name="id dans les tables et tables relationnelles SICCRF",
            ),
        ),
        migrations.AlterField(
            model_name="plantfamily",
            name="siccrf_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                editable=False,
                null=True,
                unique=True,
                verbose_name="id dans les tables et tables relationnelles SICCRF",
            ),
        ),
        migrations.AlterField(
            model_name="plantpart",
            name="siccrf_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                editable=False,
                null=True,
                unique=True,
                verbose_name="id dans les tables et tables relationnelles SICCRF",
            ),
        ),
        migrations.AlterField(
            model_name="plantsynonym",
            name="siccrf_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                editable=False,
                null=True,
                unique=True,
                verbose_name="id dans les tables et tables relationnelles SICCRF",
            ),
        ),
        migrations.AlterField(
            model_name="population",
            name="siccrf_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                editable=False,
                null=True,
                unique=True,
                verbose_name="id dans les tables et tables relationnelles SICCRF",
            ),
        ),
        migrations.AlterField(
            model_name="substance",
            name="siccrf_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                editable=False,
                null=True,
                unique=True,
                verbose_name="id dans les tables et tables relationnelles SICCRF",
            ),
        ),
        migrations.AlterField(
            model_name="substancesynonym",
            name="siccrf_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                editable=False,
                null=True,
                unique=True,
                verbose_name="id dans les tables et tables relationnelles SICCRF",
            ),
        ),
        # transform already existing <ingr>_substances relation tables to add columns
        migrations.SeparateDatabaseAndState(state_operations=ingredient_substance_state_operations),
        migrations.AddField(
            model_name="IngredientSubstanceRelation",
            name="siccrf_is_related",
            field=models.BooleanField(
                default=False,
                verbose_name="substance associée à l'ingrédient (selon la base SICCRF)",
            ),
        ),
        migrations.AddField(
            model_name="IngredientSubstanceRelation",
            name="CA_is_related",
            field=models.BooleanField(default=None, null=True, verbose_name="substance associée à l'ingrédient"),
        ),
        migrations.AddField(
            model_name="IngredientSubstanceRelation",
            name="creation_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name="IngredientSubstanceRelation",
            name="modification_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name="ingredientSubstanceRelation",
            table=None,
        ),
        migrations.SeparateDatabaseAndState(state_operations=microorganism_substance_state_operations),
        migrations.AddField(
            model_name="MicroorganismSubstanceRelation",
            name="siccrf_is_related",
            field=models.BooleanField(
                default=False,
                verbose_name="substance associée à l'ingrédient (selon la base SICCRF)",
            ),
        ),
        migrations.AddField(
            model_name="MicroorganismSubstanceRelation",
            name="CA_is_related",
            field=models.BooleanField(default=None, null=True, verbose_name="substance associée à l'ingrédient"),
        ),
        migrations.AddField(
            model_name="MicroorganismSubstanceRelation",
            name="creation_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name="MicroorganismSubstanceRelation",
            name="modification_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name="microorganismSubstanceRelation",
            table=None,
        ),
        migrations.SeparateDatabaseAndState(state_operations=plant_substance_state_operations),
        migrations.AddField(
            model_name="PlantSubstanceRelation",
            name="siccrf_is_related",
            field=models.BooleanField(
                default=False,
                verbose_name="substance associée à l'ingrédient (selon la base SICCRF)",
            ),
        ),
        migrations.AddField(
            model_name="PlantSubstanceRelation",
            name="CA_is_related",
            field=models.BooleanField(default=None, null=True, verbose_name="substance associée à l'ingrédient"),
        ),
        migrations.AddField(
            model_name="PlantSubstanceRelation",
            name="creation_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name="PlantSubstanceRelation",
            name="modification_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name="PlantSubstanceRelation",
            table=None,
        ),
        migrations.RunPython(set_default, reverse_set_default),
    ]
