# Generated by Django 5.0.2 on 2024-03-05 10:46

# import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0017_auto_20240213_1739"),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name="blogpost",
        #     name="body",
        #     field=django_ckeditor_5.fields.CKEditor5Field(
        #         blank=True, null=True, verbose_name="contenu"
        #     ),
        # ),
    ]
