# Generated by Django 5.0.2 on 2024-03-05 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0017_auto_20240213_1739"),
    ]

    # L'opération précédente (depuis supprimée) concernait django-ckeditor, qui a
    # depuis été remplacé par django-prose
    operations = []
