# Generated by Django 5.0.2 on 2024-02-19 11:20

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0017_auto_20240213_1739"),
    ]

    operations = [
        migrations.RenameField(
            model_name="condition",
            old_name="name_en",
            new_name="siccrf_name_en",
        ),
        migrations.RenameField(
            model_name="historicalcondition",
            old_name="name_en",
            new_name="siccrf_name_en",
        ),
        migrations.RenameField(
            model_name="historicalingredient",
            old_name="description",
            new_name="siccrf_description",
        ),
        migrations.RenameField(
            model_name="historicalingredient",
            old_name="name_en",
            new_name="siccrf_name_en",
        ),
        migrations.RenameField(
            model_name="historicalmicroorganism",
            old_name="genre",
            new_name="siccrf_genre",
        ),
        migrations.RenameField(
            model_name="historicalmicroorganism",
            old_name="name_en",
            new_name="siccrf_name_en",
        ),
        migrations.RemoveField(
            model_name="condition",
            name="is_obsolete",
        ),
        migrations.RemoveField(
            model_name="condition",
            name="name",
        ),
        migrations.RemoveField(
            model_name="historicalcondition",
            name="is_obsolete",
        ),
        migrations.RemoveField(
            model_name="historicalcondition",
            name="name",
        ),
        migrations.RemoveField(
            model_name="historicalingredient",
            name="is_obsolete",
        ),
        migrations.RemoveField(
            model_name="historicalingredient",
            name="name",
        ),
        migrations.RemoveField(
            model_name="historicalingredient",
            name="observation",
        ),
        migrations.RemoveField(
            model_name="historicalingredient",
            name="private_comments",
        ),
        migrations.RemoveField(
            model_name="historicalingredient",
            name="public_comments",
        ),
        migrations.RemoveField(
            model_name="historicalingredientsynonym",
            name="is_obsolete",
        ),
        migrations.RemoveField(
            model_name="historicalingredientsynonym",
            name="name",
        ),
        migrations.RemoveField(
            model_name="historicalmicroorganism",
            name="is_obsolete",
        ),
        migrations.RemoveField(
            model_name="historicalmicroorganism",
            name="name",
        ),
        migrations.RemoveField(
            model_name="historicalmicroorganism",
            name="private_comments",
        ),
        migrations.RemoveField(
            model_name="historicalmicroorganism",
            name="public_comments",
        ),
        migrations.RemoveField(
            model_name="historicalmicroorganismsynonym",
            name="is_obsolete",
        ),
        migrations.RemoveField(
            model_name="historicalmicroorganismsynonym",
            name="name",
        ),
        migrations.RemoveField(
            model_name="historicalpart",
            name="is_useful",
        ),
        migrations.RemoveField(
            model_name="historicalpart",
            name="must_be_monitored",
        ),
        migrations.RemoveField(
            model_name="historicalplant",
            name="family",
        ),
        migrations.RemoveField(
            model_name="historicalplant",
            name="is_obsolete",
        ),
        migrations.RemoveField(
            model_name="historicalplant",
            name="name",
        ),
        migrations.RemoveField(
            model_name="historicalplant",
            name="private_comments",
        ),
        migrations.RemoveField(
            model_name="historicalplant",
            name="public_comments",
        ),
        migrations.RemoveField(
            model_name="historicalplantfamily",
            name="is_obsolete",
        ),
        migrations.RemoveField(
            model_name="historicalplantfamily",
            name="name",
        ),
        migrations.RemoveField(
            model_name="historicalplantfamily",
            name="name_en",
        ),
        migrations.RemoveField(
            model_name="historicalplantpart",
            name="is_obsolete",
        ),
        migrations.RemoveField(
            model_name="historicalplantpart",
            name="name",
        ),
        migrations.RemoveField(
            model_name="historicalplantpart",
            name="name_en",
        ),
        migrations.RemoveField(
            model_name="historicalplantsynonym",
            name="is_obsolete",
        ),
        migrations.RemoveField(
            model_name="historicalplantsynonym",
            name="name",
        ),
        migrations.RemoveField(
            model_name="historicalpopulation",
            name="is_obsolete",
        ),
        migrations.RemoveField(
            model_name="historicalpopulation",
            name="name",
        ),
        migrations.RemoveField(
            model_name="historicalsubstance",
            name="cas_number",
        ),
        migrations.RemoveField(
            model_name="historicalsubstance",
            name="einec_number",
        ),
        migrations.RemoveField(
            model_name="historicalsubstance",
            name="is_obsolete",
        ),
        migrations.RemoveField(
            model_name="historicalsubstance",
            name="max_quantity",
        ),
        migrations.RemoveField(
            model_name="historicalsubstance",
            name="min_quantity",
        ),
        migrations.RemoveField(
            model_name="historicalsubstance",
            name="must_specify_quantity",
        ),
        migrations.RemoveField(
            model_name="historicalsubstance",
            name="name",
        ),
        migrations.RemoveField(
            model_name="historicalsubstance",
            name="name_en",
        ),
        migrations.RemoveField(
            model_name="historicalsubstance",
            name="nutritional_reference",
        ),
        migrations.RemoveField(
            model_name="historicalsubstance",
            name="private_comments",
        ),
        migrations.RemoveField(
            model_name="historicalsubstance",
            name="public_comments",
        ),
        migrations.RemoveField(
            model_name="historicalsubstance",
            name="source",
        ),
        migrations.RemoveField(
            model_name="historicalsubstancesynonym",
            name="is_obsolete",
        ),
        migrations.RemoveField(
            model_name="historicalsubstancesynonym",
            name="name",
        ),
        migrations.RemoveField(
            model_name="ingredient",
            name="description",
        ),
        migrations.RemoveField(
            model_name="ingredient",
            name="is_obsolete",
        ),
        migrations.RemoveField(
            model_name="ingredient",
            name="name",
        ),
        migrations.RemoveField(
            model_name="ingredient",
            name="name_en",
        ),
        migrations.RemoveField(
            model_name="ingredient",
            name="observation",
        ),
        migrations.RemoveField(
            model_name="ingredient",
            name="private_comments",
        ),
        migrations.RemoveField(
            model_name="ingredient",
            name="public_comments",
        ),
        migrations.RemoveField(
            model_name="ingredientsynonym",
            name="is_obsolete",
        ),
        migrations.RemoveField(
            model_name="ingredientsynonym",
            name="name",
        ),
        migrations.RemoveField(
            model_name="microorganism",
            name="genre",
        ),
        migrations.RemoveField(
            model_name="microorganism",
            name="is_obsolete",
        ),
        migrations.RemoveField(
            model_name="microorganism",
            name="name",
        ),
        migrations.RemoveField(
            model_name="microorganism",
            name="name_en",
        ),
        migrations.RemoveField(
            model_name="microorganism",
            name="private_comments",
        ),
        migrations.RemoveField(
            model_name="microorganism",
            name="public_comments",
        ),
        migrations.RemoveField(
            model_name="microorganismsynonym",
            name="is_obsolete",
        ),
        migrations.RemoveField(
            model_name="microorganismsynonym",
            name="name",
        ),
        migrations.RemoveField(
            model_name="part",
            name="is_useful",
        ),
        migrations.RemoveField(
            model_name="part",
            name="must_be_monitored",
        ),
        migrations.RemoveField(
            model_name="plant",
            name="family",
        ),
        migrations.RemoveField(
            model_name="plant",
            name="is_obsolete",
        ),
        migrations.RemoveField(
            model_name="plant",
            name="name",
        ),
        migrations.RemoveField(
            model_name="plant",
            name="private_comments",
        ),
        migrations.RemoveField(
            model_name="plant",
            name="public_comments",
        ),
        migrations.RemoveField(
            model_name="plantfamily",
            name="is_obsolete",
        ),
        migrations.RemoveField(
            model_name="plantfamily",
            name="name",
        ),
        migrations.RemoveField(
            model_name="plantfamily",
            name="name_en",
        ),
        migrations.RemoveField(
            model_name="plantpart",
            name="is_obsolete",
        ),
        migrations.RemoveField(
            model_name="plantpart",
            name="name",
        ),
        migrations.RemoveField(
            model_name="plantpart",
            name="name_en",
        ),
        migrations.RemoveField(
            model_name="plantsynonym",
            name="is_obsolete",
        ),
        migrations.RemoveField(
            model_name="plantsynonym",
            name="name",
        ),
        migrations.RemoveField(
            model_name="population",
            name="is_obsolete",
        ),
        migrations.RemoveField(
            model_name="population",
            name="name",
        ),
        migrations.RemoveField(
            model_name="substance",
            name="cas_number",
        ),
        migrations.RemoveField(
            model_name="substance",
            name="einec_number",
        ),
        migrations.RemoveField(
            model_name="substance",
            name="is_obsolete",
        ),
        migrations.RemoveField(
            model_name="substance",
            name="max_quantity",
        ),
        migrations.RemoveField(
            model_name="substance",
            name="min_quantity",
        ),
        migrations.RemoveField(
            model_name="substance",
            name="must_specify_quantity",
        ),
        migrations.RemoveField(
            model_name="substance",
            name="name",
        ),
        migrations.RemoveField(
            model_name="substance",
            name="name_en",
        ),
        migrations.RemoveField(
            model_name="substance",
            name="nutritional_reference",
        ),
        migrations.RemoveField(
            model_name="substance",
            name="private_comments",
        ),
        migrations.RemoveField(
            model_name="substance",
            name="public_comments",
        ),
        migrations.RemoveField(
            model_name="substance",
            name="source",
        ),
        migrations.RemoveField(
            model_name="substancesynonym",
            name="is_obsolete",
        ),
        migrations.RemoveField(
            model_name="substancesynonym",
            name="name",
        ),
        migrations.AddField(
            model_name="condition",
            name="siccrf_is_obsolete",
            field=models.BooleanField(
                default=False, verbose_name="objet obsolète selon SICCRF"
            ),
        ),
        migrations.AddField(
            model_name="condition",
            name="siccrf_name",
            field=models.TextField(default="", verbose_name="nom SICCRF"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalcondition",
            name="siccrf_is_obsolete",
            field=models.BooleanField(
                default=False, verbose_name="objet obsolète selon SICCRF"
            ),
        ),
        migrations.AddField(
            model_name="historicalcondition",
            name="siccrf_name",
            field=models.TextField(default="", verbose_name="nom SICCRF"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalingredient",
            name="siccrf_is_obsolete",
            field=models.BooleanField(
                default=False, verbose_name="objet obsolète selon SICCRF"
            ),
        ),
        migrations.AddField(
            model_name="historicalingredient",
            name="siccrf_name",
            field=models.TextField(default="", verbose_name="nom SICCRF"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalingredient",
            name="siccrf_private_comments",
            field=models.TextField(
                blank=True, editable=False, verbose_name="commentaires privés SICCRF"
            ),
        ),
        migrations.AddField(
            model_name="historicalingredient",
            name="siccrf_private_comments_en",
            field=models.TextField(
                blank=True,
                editable=False,
                verbose_name="commentaires privés en anglais SICCRF",
            ),
        ),
        migrations.AddField(
            model_name="historicalingredient",
            name="siccrf_public_comments",
            field=models.TextField(
                blank=True, editable=False, verbose_name="commentaires publics SICCRF"
            ),
        ),
        migrations.AddField(
            model_name="historicalingredient",
            name="siccrf_public_comments_en",
            field=models.TextField(
                blank=True,
                editable=False,
                verbose_name="commentaires publics en anglais SICCRF",
            ),
        ),
        migrations.AddField(
            model_name="historicalingredientsynonym",
            name="siccrf_is_obsolete",
            field=models.BooleanField(
                default=False, verbose_name="objet obsolète selon SICCRF"
            ),
        ),
        migrations.AddField(
            model_name="historicalingredientsynonym",
            name="siccrf_name",
            field=models.TextField(default="", verbose_name="nom SICCRF"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalmicroorganism",
            name="siccrf_is_obsolete",
            field=models.BooleanField(
                default=False, verbose_name="objet obsolète selon SICCRF"
            ),
        ),
        migrations.AddField(
            model_name="historicalmicroorganism",
            name="siccrf_name",
            field=models.TextField(default="", verbose_name="nom SICCRF"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalmicroorganism",
            name="siccrf_private_comments",
            field=models.TextField(
                blank=True, editable=False, verbose_name="commentaires privés SICCRF"
            ),
        ),
        migrations.AddField(
            model_name="historicalmicroorganism",
            name="siccrf_private_comments_en",
            field=models.TextField(
                blank=True,
                editable=False,
                verbose_name="commentaires privés en anglais SICCRF",
            ),
        ),
        migrations.AddField(
            model_name="historicalmicroorganism",
            name="siccrf_public_comments",
            field=models.TextField(
                blank=True, editable=False, verbose_name="commentaires publics SICCRF"
            ),
        ),
        migrations.AddField(
            model_name="historicalmicroorganism",
            name="siccrf_public_comments_en",
            field=models.TextField(
                blank=True,
                editable=False,
                verbose_name="commentaires publics en anglais SICCRF",
            ),
        ),
        migrations.AddField(
            model_name="historicalmicroorganismsynonym",
            name="siccrf_is_obsolete",
            field=models.BooleanField(
                default=False, verbose_name="objet obsolète selon SICCRF"
            ),
        ),
        migrations.AddField(
            model_name="historicalmicroorganismsynonym",
            name="siccrf_name",
            field=models.TextField(default="", verbose_name="nom SICCRF"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalpart",
            name="CA_is_useful",
            field=models.BooleanField(default=False, verbose_name="🍵 utile ?"),
        ),
        migrations.AddField(
            model_name="historicalpart",
            name="CA_must_be_monitored",
            field=models.BooleanField(default=False, verbose_name="⚠️ à surveiller ?"),
        ),
        migrations.AddField(
            model_name="historicalpart",
            name="siccrf_is_useful",
            field=models.BooleanField(
                default=False, verbose_name="🍵 utile (selon la base SICCRF) ?"
            ),
        ),
        migrations.AddField(
            model_name="historicalpart",
            name="siccrf_must_be_monitored",
            field=models.BooleanField(
                default=False, verbose_name="⚠️ à surveiller (selon la base SICCRF) ?"
            ),
        ),
        migrations.AddField(
            model_name="historicalplant",
            name="siccrf_family",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="data.plantfamily",
                verbose_name="famille de plante",
            ),
        ),
        migrations.AddField(
            model_name="historicalplant",
            name="siccrf_is_obsolete",
            field=models.BooleanField(
                default=False, verbose_name="objet obsolète selon SICCRF"
            ),
        ),
        migrations.AddField(
            model_name="historicalplant",
            name="siccrf_name",
            field=models.TextField(default="", verbose_name="nom SICCRF"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalplant",
            name="siccrf_private_comments",
            field=models.TextField(
                blank=True, editable=False, verbose_name="commentaires privés SICCRF"
            ),
        ),
        migrations.AddField(
            model_name="historicalplant",
            name="siccrf_private_comments_en",
            field=models.TextField(
                blank=True,
                editable=False,
                verbose_name="commentaires privés en anglais SICCRF",
            ),
        ),
        migrations.AddField(
            model_name="historicalplant",
            name="siccrf_public_comments",
            field=models.TextField(
                blank=True, editable=False, verbose_name="commentaires publics SICCRF"
            ),
        ),
        migrations.AddField(
            model_name="historicalplant",
            name="siccrf_public_comments_en",
            field=models.TextField(
                blank=True,
                editable=False,
                verbose_name="commentaires publics en anglais SICCRF",
            ),
        ),
        migrations.AddField(
            model_name="historicalplantfamily",
            name="siccrf_is_obsolete",
            field=models.BooleanField(
                default=False, verbose_name="objet obsolète selon SICCRF"
            ),
        ),
        migrations.AddField(
            model_name="historicalplantfamily",
            name="siccrf_name",
            field=models.TextField(default="", verbose_name="nom SICCRF"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalplantfamily",
            name="siccrf_name_en",
            field=models.TextField(blank=True, verbose_name="nom en anglais"),
        ),
        migrations.AddField(
            model_name="historicalplantpart",
            name="siccrf_is_obsolete",
            field=models.BooleanField(
                default=False, verbose_name="objet obsolète selon SICCRF"
            ),
        ),
        migrations.AddField(
            model_name="historicalplantpart",
            name="siccrf_name",
            field=models.TextField(default="", verbose_name="nom SICCRF"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalplantpart",
            name="siccrf_name_en",
            field=models.TextField(blank=True, verbose_name="nom en anglais"),
        ),
        migrations.AddField(
            model_name="historicalplantsynonym",
            name="siccrf_is_obsolete",
            field=models.BooleanField(
                default=False, verbose_name="objet obsolète selon SICCRF"
            ),
        ),
        migrations.AddField(
            model_name="historicalplantsynonym",
            name="siccrf_name",
            field=models.TextField(default="", verbose_name="nom SICCRF"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalpopulation",
            name="siccrf_is_obsolete",
            field=models.BooleanField(
                default=False, verbose_name="objet obsolète selon SICCRF"
            ),
        ),
        migrations.AddField(
            model_name="historicalpopulation",
            name="siccrf_name",
            field=models.TextField(default="", verbose_name="nom SICCRF"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalsubstance",
            name="siccrf_cas_number",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="numéro CAS"
            ),
        ),
        migrations.AddField(
            model_name="historicalsubstance",
            name="siccrf_einec_number",
            field=models.CharField(
                blank=True, max_length=7, verbose_name="numéro EINECS"
            ),
        ),
        migrations.AddField(
            model_name="historicalsubstance",
            name="siccrf_is_obsolete",
            field=models.BooleanField(
                default=False, verbose_name="objet obsolète selon SICCRF"
            ),
        ),
        migrations.AddField(
            model_name="historicalsubstance",
            name="siccrf_max_quantity",
            field=models.FloatField(
                blank=True, null=True, verbose_name="quantité maximale autorisée"
            ),
        ),
        migrations.AddField(
            model_name="historicalsubstance",
            name="siccrf_must_specify_quantity",
            field=models.BooleanField(
                default=False, verbose_name="spécification de quantité obligatoire"
            ),
        ),
        migrations.AddField(
            model_name="historicalsubstance",
            name="siccrf_name",
            field=models.TextField(default="", verbose_name="nom SICCRF"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalsubstance",
            name="siccrf_name_en",
            field=models.TextField(blank=True, verbose_name="nom en anglais"),
        ),
        migrations.AddField(
            model_name="historicalsubstance",
            name="siccrf_nutritional_reference",
            field=models.FloatField(
                blank=True, null=True, verbose_name="apport nutritionnel conseillé"
            ),
        ),
        migrations.AddField(
            model_name="historicalsubstance",
            name="siccrf_private_comments",
            field=models.TextField(
                blank=True, editable=False, verbose_name="commentaires privés SICCRF"
            ),
        ),
        migrations.AddField(
            model_name="historicalsubstance",
            name="siccrf_private_comments_en",
            field=models.TextField(
                blank=True,
                editable=False,
                verbose_name="commentaires privés en anglais SICCRF",
            ),
        ),
        migrations.AddField(
            model_name="historicalsubstance",
            name="siccrf_public_comments",
            field=models.TextField(
                blank=True, editable=False, verbose_name="commentaires publics SICCRF"
            ),
        ),
        migrations.AddField(
            model_name="historicalsubstance",
            name="siccrf_public_comments_en",
            field=models.TextField(
                blank=True,
                editable=False,
                verbose_name="commentaires publics en anglais SICCRF",
            ),
        ),
        migrations.AddField(
            model_name="historicalsubstance",
            name="siccrf_source",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="historicalsubstancesynonym",
            name="siccrf_is_obsolete",
            field=models.BooleanField(
                default=False, verbose_name="objet obsolète selon SICCRF"
            ),
        ),
        migrations.AddField(
            model_name="historicalsubstancesynonym",
            name="siccrf_name",
            field=models.TextField(default="", verbose_name="nom SICCRF"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ingredient",
            name="siccrf_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="siccrf_is_obsolete",
            field=models.BooleanField(
                default=False, verbose_name="objet obsolète selon SICCRF"
            ),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="siccrf_name",
            field=models.TextField(default="", verbose_name="nom SICCRF"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ingredient",
            name="siccrf_name_en",
            field=models.TextField(blank=True, verbose_name="nom en anglais"),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="siccrf_private_comments",
            field=models.TextField(
                blank=True, editable=False, verbose_name="commentaires privés SICCRF"
            ),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="siccrf_private_comments_en",
            field=models.TextField(
                blank=True,
                editable=False,
                verbose_name="commentaires privés en anglais SICCRF",
            ),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="siccrf_public_comments",
            field=models.TextField(
                blank=True, editable=False, verbose_name="commentaires publics SICCRF"
            ),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="siccrf_public_comments_en",
            field=models.TextField(
                blank=True,
                editable=False,
                verbose_name="commentaires publics en anglais SICCRF",
            ),
        ),
        migrations.AddField(
            model_name="ingredientsynonym",
            name="siccrf_is_obsolete",
            field=models.BooleanField(
                default=False, verbose_name="objet obsolète selon SICCRF"
            ),
        ),
        migrations.AddField(
            model_name="ingredientsynonym",
            name="siccrf_name",
            field=models.TextField(default="", verbose_name="nom SICCRF"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="microorganism",
            name="siccrf_genre",
            field=models.TextField(default="", verbose_name="genre de micro-organisme"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="microorganism",
            name="siccrf_is_obsolete",
            field=models.BooleanField(
                default=False, verbose_name="objet obsolète selon SICCRF"
            ),
        ),
        migrations.AddField(
            model_name="microorganism",
            name="siccrf_name",
            field=models.TextField(default="", verbose_name="nom SICCRF"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="microorganism",
            name="siccrf_name_en",
            field=models.TextField(blank=True, verbose_name="nom en anglais"),
        ),
        migrations.AddField(
            model_name="microorganism",
            name="siccrf_private_comments",
            field=models.TextField(
                blank=True, editable=False, verbose_name="commentaires privés SICCRF"
            ),
        ),
        migrations.AddField(
            model_name="microorganism",
            name="siccrf_private_comments_en",
            field=models.TextField(
                blank=True,
                editable=False,
                verbose_name="commentaires privés en anglais SICCRF",
            ),
        ),
        migrations.AddField(
            model_name="microorganism",
            name="siccrf_public_comments",
            field=models.TextField(
                blank=True, editable=False, verbose_name="commentaires publics SICCRF"
            ),
        ),
        migrations.AddField(
            model_name="microorganism",
            name="siccrf_public_comments_en",
            field=models.TextField(
                blank=True,
                editable=False,
                verbose_name="commentaires publics en anglais SICCRF",
            ),
        ),
        migrations.AddField(
            model_name="microorganismsynonym",
            name="siccrf_is_obsolete",
            field=models.BooleanField(
                default=False, verbose_name="objet obsolète selon SICCRF"
            ),
        ),
        migrations.AddField(
            model_name="microorganismsynonym",
            name="siccrf_name",
            field=models.TextField(default="", verbose_name="nom SICCRF"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="part",
            name="CA_is_useful",
            field=models.BooleanField(default=False, verbose_name="🍵 utile ?"),
        ),
        migrations.AddField(
            model_name="part",
            name="CA_must_be_monitored",
            field=models.BooleanField(default=False, verbose_name="⚠️ à surveiller ?"),
        ),
        migrations.AddField(
            model_name="part",
            name="siccrf_is_useful",
            field=models.BooleanField(
                default=False, verbose_name="🍵 utile (selon la base SICCRF) ?"
            ),
        ),
        migrations.AddField(
            model_name="part",
            name="siccrf_must_be_monitored",
            field=models.BooleanField(
                default=False, verbose_name="⚠️ à surveiller (selon la base SICCRF) ?"
            ),
        ),
        migrations.AddField(
            model_name="plant",
            name="siccrf_family",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="data.plantfamily",
                verbose_name="famille de plante",
            ),
        ),
        migrations.AddField(
            model_name="plant",
            name="siccrf_is_obsolete",
            field=models.BooleanField(
                default=False, verbose_name="objet obsolète selon SICCRF"
            ),
        ),
        migrations.AddField(
            model_name="plant",
            name="siccrf_name",
            field=models.TextField(default="", verbose_name="nom SICCRF"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="plant",
            name="siccrf_private_comments",
            field=models.TextField(
                blank=True, editable=False, verbose_name="commentaires privés SICCRF"
            ),
        ),
        migrations.AddField(
            model_name="plant",
            name="siccrf_private_comments_en",
            field=models.TextField(
                blank=True,
                editable=False,
                verbose_name="commentaires privés en anglais SICCRF",
            ),
        ),
        migrations.AddField(
            model_name="plant",
            name="siccrf_public_comments",
            field=models.TextField(
                blank=True, editable=False, verbose_name="commentaires publics SICCRF"
            ),
        ),
        migrations.AddField(
            model_name="plant",
            name="siccrf_public_comments_en",
            field=models.TextField(
                blank=True,
                editable=False,
                verbose_name="commentaires publics en anglais SICCRF",
            ),
        ),
        migrations.AddField(
            model_name="plantfamily",
            name="siccrf_is_obsolete",
            field=models.BooleanField(
                default=False, verbose_name="objet obsolète selon SICCRF"
            ),
        ),
        migrations.AddField(
            model_name="plantfamily",
            name="siccrf_name",
            field=models.TextField(default="", verbose_name="nom SICCRF"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="plantfamily",
            name="siccrf_name_en",
            field=models.TextField(blank=True, verbose_name="nom en anglais"),
        ),
        migrations.AddField(
            model_name="plantpart",
            name="siccrf_is_obsolete",
            field=models.BooleanField(
                default=False, verbose_name="objet obsolète selon SICCRF"
            ),
        ),
        migrations.AddField(
            model_name="plantpart",
            name="siccrf_name",
            field=models.TextField(default="", verbose_name="nom SICCRF"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="plantpart",
            name="siccrf_name_en",
            field=models.TextField(blank=True, verbose_name="nom en anglais"),
        ),
        migrations.AddField(
            model_name="plantsynonym",
            name="siccrf_is_obsolete",
            field=models.BooleanField(
                default=False, verbose_name="objet obsolète selon SICCRF"
            ),
        ),
        migrations.AddField(
            model_name="plantsynonym",
            name="siccrf_name",
            field=models.TextField(default="", verbose_name="nom SICCRF"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="population",
            name="siccrf_is_obsolete",
            field=models.BooleanField(
                default=False, verbose_name="objet obsolète selon SICCRF"
            ),
        ),
        migrations.AddField(
            model_name="population",
            name="siccrf_name",
            field=models.TextField(default="", verbose_name="nom SICCRF"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="substance",
            name="siccrf_cas_number",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="numéro CAS"
            ),
        ),
        migrations.AddField(
            model_name="substance",
            name="siccrf_einec_number",
            field=models.CharField(
                blank=True, max_length=7, verbose_name="numéro EINECS"
            ),
        ),
        migrations.AddField(
            model_name="substance",
            name="siccrf_is_obsolete",
            field=models.BooleanField(
                default=False, verbose_name="objet obsolète selon SICCRF"
            ),
        ),
        migrations.AddField(
            model_name="substance",
            name="siccrf_max_quantity",
            field=models.FloatField(
                blank=True, null=True, verbose_name="quantité maximale autorisée"
            ),
        ),
        migrations.AddField(
            model_name="substance",
            name="siccrf_must_specify_quantity",
            field=models.BooleanField(
                default=False, verbose_name="spécification de quantité obligatoire"
            ),
        ),
        migrations.AddField(
            model_name="substance",
            name="siccrf_name",
            field=models.TextField(default="", verbose_name="nom SICCRF"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="substance",
            name="siccrf_name_en",
            field=models.TextField(blank=True, verbose_name="nom en anglais"),
        ),
        migrations.AddField(
            model_name="substance",
            name="siccrf_nutritional_reference",
            field=models.FloatField(
                blank=True, null=True, verbose_name="apport nutritionnel conseillé"
            ),
        ),
        migrations.AddField(
            model_name="substance",
            name="siccrf_private_comments",
            field=models.TextField(
                blank=True, editable=False, verbose_name="commentaires privés SICCRF"
            ),
        ),
        migrations.AddField(
            model_name="substance",
            name="siccrf_private_comments_en",
            field=models.TextField(
                blank=True,
                editable=False,
                verbose_name="commentaires privés en anglais SICCRF",
            ),
        ),
        migrations.AddField(
            model_name="substance",
            name="siccrf_public_comments",
            field=models.TextField(
                blank=True, editable=False, verbose_name="commentaires publics SICCRF"
            ),
        ),
        migrations.AddField(
            model_name="substance",
            name="siccrf_public_comments_en",
            field=models.TextField(
                blank=True,
                editable=False,
                verbose_name="commentaires publics en anglais SICCRF",
            ),
        ),
        migrations.AddField(
            model_name="substance",
            name="siccrf_source",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="substancesynonym",
            name="siccrf_is_obsolete",
            field=models.BooleanField(
                default=False, verbose_name="objet obsolète selon SICCRF"
            ),
        ),
        migrations.AddField(
            model_name="substancesynonym",
            name="siccrf_name",
            field=models.TextField(default="", verbose_name="nom SICCRF"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="condition",
            name="siccrf_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                editable=False,
                null=True,
                unique=True,
                verbose_name="id dans les tables et tables relationnelles SICCRF",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcondition",
            name="siccrf_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                editable=False,
                null=True,
                verbose_name="id dans les tables et tables relationnelles SICCRF",
            ),
        ),
        migrations.AlterField(
            model_name="historicalingredient",
            name="siccrf_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                editable=False,
                null=True,
                verbose_name="id dans les tables et tables relationnelles SICCRF",
            ),
        ),
        migrations.AlterField(
            model_name="historicalingredientsynonym",
            name="siccrf_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                editable=False,
                null=True,
                verbose_name="id dans les tables et tables relationnelles SICCRF",
            ),
        ),
        migrations.AlterField(
            model_name="historicalmicroorganism",
            name="siccrf_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                editable=False,
                null=True,
                verbose_name="id dans les tables et tables relationnelles SICCRF",
            ),
        ),
        migrations.AlterField(
            model_name="historicalmicroorganismsynonym",
            name="siccrf_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                editable=False,
                null=True,
                verbose_name="id dans les tables et tables relationnelles SICCRF",
            ),
        ),
        migrations.AlterField(
            model_name="historicalplant",
            name="siccrf_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                editable=False,
                null=True,
                verbose_name="id dans les tables et tables relationnelles SICCRF",
            ),
        ),
        migrations.AlterField(
            model_name="historicalplantfamily",
            name="siccrf_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                editable=False,
                null=True,
                verbose_name="id dans les tables et tables relationnelles SICCRF",
            ),
        ),
        migrations.AlterField(
            model_name="historicalplantpart",
            name="siccrf_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                editable=False,
                null=True,
                verbose_name="id dans les tables et tables relationnelles SICCRF",
            ),
        ),
        migrations.AlterField(
            model_name="historicalplantsynonym",
            name="siccrf_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                editable=False,
                null=True,
                verbose_name="id dans les tables et tables relationnelles SICCRF",
            ),
        ),
        migrations.AlterField(
            model_name="historicalpopulation",
            name="siccrf_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                editable=False,
                null=True,
                verbose_name="id dans les tables et tables relationnelles SICCRF",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubstance",
            name="siccrf_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                editable=False,
                null=True,
                verbose_name="id dans les tables et tables relationnelles SICCRF",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubstancesynonym",
            name="siccrf_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                editable=False,
                null=True,
                verbose_name="id dans les tables et tables relationnelles SICCRF",
            ),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="siccrf_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                editable=False,
                null=True,
                unique=True,
                verbose_name="id dans les tables et tables relationnelles SICCRF",
            ),
        ),
        migrations.AlterField(
            model_name="ingredientsynonym",
            name="siccrf_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                editable=False,
                null=True,
                unique=True,
                verbose_name="id dans les tables et tables relationnelles SICCRF",
            ),
        ),
        migrations.AlterField(
            model_name="microorganism",
            name="siccrf_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                editable=False,
                null=True,
                unique=True,
                verbose_name="id dans les tables et tables relationnelles SICCRF",
            ),
        ),
        migrations.AlterField(
            model_name="microorganismsynonym",
            name="siccrf_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                editable=False,
                null=True,
                unique=True,
                verbose_name="id dans les tables et tables relationnelles SICCRF",
            ),
        ),
        migrations.AlterField(
            model_name="plant",
            name="siccrf_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                editable=False,
                null=True,
                unique=True,
                verbose_name="id dans les tables et tables relationnelles SICCRF",
            ),
        ),
        migrations.AlterField(
            model_name="plantfamily",
            name="siccrf_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                editable=False,
                null=True,
                unique=True,
                verbose_name="id dans les tables et tables relationnelles SICCRF",
            ),
        ),
        migrations.AlterField(
            model_name="plantpart",
            name="siccrf_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                editable=False,
                null=True,
                unique=True,
                verbose_name="id dans les tables et tables relationnelles SICCRF",
            ),
        ),
        migrations.AlterField(
            model_name="plantsynonym",
            name="siccrf_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                editable=False,
                null=True,
                unique=True,
                verbose_name="id dans les tables et tables relationnelles SICCRF",
            ),
        ),
        migrations.AlterField(
            model_name="population",
            name="siccrf_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                editable=False,
                null=True,
                unique=True,
                verbose_name="id dans les tables et tables relationnelles SICCRF",
            ),
        ),
        migrations.AlterField(
            model_name="substance",
            name="siccrf_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                editable=False,
                null=True,
                unique=True,
                verbose_name="id dans les tables et tables relationnelles SICCRF",
            ),
        ),
        migrations.AlterField(
            model_name="substancesynonym",
            name="siccrf_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                editable=False,
                null=True,
                unique=True,
                verbose_name="id dans les tables et tables relationnelles SICCRF",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalIngredientSubstanceRelation",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("creation_date", models.DateTimeField(blank=True, editable=False)),
                ("modification_date", models.DateTimeField(blank=True, editable=False)),
                (
                    "siccrf_is_related",
                    models.BooleanField(
                        default=False,
                        verbose_name="substance associée à l'ingrédient (selon la base SICCRF)",
                    ),
                ),
                (
                    "CA_is_related",
                    models.BooleanField(
                        default=False, verbose_name="substance associée à l'ingrédient"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="data.ingredient",
                    ),
                ),
                (
                    "substance",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="data.substance",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical ingredient substance relation",
                "verbose_name_plural": "historical ingredient substance relations",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalMicroorganismSubstanceRelation",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("creation_date", models.DateTimeField(blank=True, editable=False)),
                ("modification_date", models.DateTimeField(blank=True, editable=False)),
                (
                    "siccrf_is_related",
                    models.BooleanField(
                        default=False,
                        verbose_name="substance associée au micro-organisme (selon la base SICCRF)",
                    ),
                ),
                (
                    "CA_is_related",
                    models.BooleanField(
                        default=False,
                        verbose_name="substance associée au micro-organisme",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "microorganism",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="data.microorganism",
                    ),
                ),
                (
                    "substance",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="data.substance",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical microorganism substance relation",
                "verbose_name_plural": "historical microorganism substance relations",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalPlantSubstanceRelation",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("creation_date", models.DateTimeField(blank=True, editable=False)),
                ("modification_date", models.DateTimeField(blank=True, editable=False)),
                (
                    "siccrf_is_related",
                    models.BooleanField(
                        default=False,
                        verbose_name="substance associée à la plante (selon la base SICCRF)",
                    ),
                ),
                (
                    "CA_is_related",
                    models.BooleanField(
                        default=False, verbose_name="substance associée à la plante"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="data.plant",
                    ),
                ),
                (
                    "substance",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="data.substance",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical plant substance relation",
                "verbose_name_plural": "historical plant substance relations",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="IngredientSubstanceRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("modification_date", models.DateTimeField(auto_now=True)),
                (
                    "siccrf_is_related",
                    models.BooleanField(
                        default=False,
                        verbose_name="substance associée à l'ingrédient (selon la base SICCRF)",
                    ),
                ),
                (
                    "CA_is_related",
                    models.BooleanField(
                        default=False, verbose_name="substance associée à l'ingrédient"
                    ),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data.ingredient",
                    ),
                ),
                (
                    "substance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="data.substance"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="ingredient",
            name="substances",
        ),
        migrations.AddField(
            model_name="ingredient",
            name="substances",
            field=models.ManyToManyField(
                through="data.IngredientSubstanceRelation", to="data.substance"
            ),
        ),
        migrations.CreateModel(
            name="MicroorganismSubstanceRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("modification_date", models.DateTimeField(auto_now=True)),
                (
                    "siccrf_is_related",
                    models.BooleanField(
                        default=False,
                        verbose_name="substance associée au micro-organisme (selon la base SICCRF)",
                    ),
                ),
                (
                    "CA_is_related",
                    models.BooleanField(
                        default=False,
                        verbose_name="substance associée au micro-organisme",
                    ),
                ),
                (
                    "microorganism",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data.microorganism",
                    ),
                ),
                (
                    "substance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="data.substance"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="microorganism",
            name="substances",
        ),
        migrations.AddField(
            model_name="microorganism",
            name="substances",
            field=models.ManyToManyField(
                through="data.MicroorganismSubstanceRelation", to="data.substance"
            ),
        ),
        migrations.CreateModel(
            name="PlantSubstanceRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("modification_date", models.DateTimeField(auto_now=True)),
                (
                    "siccrf_is_related",
                    models.BooleanField(
                        default=False,
                        verbose_name="substance associée à la plante (selon la base SICCRF)",
                    ),
                ),
                (
                    "CA_is_related",
                    models.BooleanField(
                        default=False, verbose_name="substance associée à la plante"
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="data.plant"
                    ),
                ),
                (
                    "substance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="data.substance"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="plant",
            name="substances",
        ),
        migrations.AddField(
            model_name="plant",
            name="substances",
            field=models.ManyToManyField(
                through="data.PlantSubstanceRelation", to="data.substance"
            ),
        ),
    ]
