# Generated by Django 5.0.2 on 2024-02-21 16:37

import django.db.models.deletion
import django.db.models.functions.comparison
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0018_rename_name_en_condition_siccrf_name_en_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalingredientsynonym",
            old_name="siccrf_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="historicalmicroorganismsynonym",
            old_name="siccrf_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="historicalplantsynonym",
            old_name="siccrf_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="historicalsubstancesynonym",
            old_name="siccrf_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="ingredientsynonym",
            old_name="siccrf_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="microorganismsynonym",
            old_name="siccrf_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="plantsynonym",
            old_name="siccrf_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="substancesynonym",
            old_name="siccrf_name",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="historicalingredientsynonym",
            name="CA_is_obsolete",
        ),
        migrations.RemoveField(
            model_name="historicalingredientsynonym",
            name="CA_name",
        ),
        migrations.RemoveField(
            model_name="historicalmicroorganismsynonym",
            name="CA_is_obsolete",
        ),
        migrations.RemoveField(
            model_name="historicalmicroorganismsynonym",
            name="CA_name",
        ),
        migrations.RemoveField(
            model_name="historicalplantsynonym",
            name="CA_is_obsolete",
        ),
        migrations.RemoveField(
            model_name="historicalplantsynonym",
            name="CA_name",
        ),
        migrations.RemoveField(
            model_name="historicalsubstancesynonym",
            name="CA_is_obsolete",
        ),
        migrations.RemoveField(
            model_name="historicalsubstancesynonym",
            name="CA_name",
        ),
        migrations.RemoveField(
            model_name="ingredientsynonym",
            name="CA_is_obsolete",
        ),
        migrations.RemoveField(
            model_name="ingredientsynonym",
            name="CA_name",
        ),
        migrations.RemoveField(
            model_name="microorganismsynonym",
            name="CA_is_obsolete",
        ),
        migrations.RemoveField(
            model_name="microorganismsynonym",
            name="CA_name",
        ),
        migrations.RemoveField(
            model_name="plantsynonym",
            name="CA_is_obsolete",
        ),
        migrations.RemoveField(
            model_name="plantsynonym",
            name="CA_name",
        ),
        migrations.RemoveField(
            model_name="substancesynonym",
            name="CA_is_obsolete",
        ),
        migrations.RemoveField(
            model_name="substancesynonym",
            name="CA_name",
        ),
        migrations.AddField(
            model_name="condition",
            name="is_obsolete",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.functions.comparison.Coalesce(
                    models.F("CA_is_obsolete"), models.F("siccrf_is_obsolete")
                ),
                output_field=models.BooleanField(verbose_name="objet obsolète"),
            ),
        ),
        migrations.AddField(
            model_name="condition",
            name="name",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.functions.comparison.Coalesce(
                    django.db.models.functions.comparison.NullIf(
                        models.F("CA_name"), models.Value("")
                    ),
                    models.F("siccrf_name"),
                ),
                output_field=models.TextField(verbose_name="nom"),
            ),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="is_obsolete",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.functions.comparison.Coalesce(
                    models.F("CA_is_obsolete"), models.F("siccrf_is_obsolete")
                ),
                output_field=models.BooleanField(verbose_name="objet obsolète"),
            ),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="name",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.functions.comparison.Coalesce(
                    django.db.models.functions.comparison.NullIf(
                        models.F("CA_name"), models.Value("")
                    ),
                    models.F("siccrf_name"),
                ),
                output_field=models.TextField(verbose_name="nom"),
            ),
        ),
        migrations.AddField(
            model_name="microorganism",
            name="genre",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.functions.comparison.Coalesce(
                    models.F("CA_genre"), models.F("siccrf_genre")
                ),
                output_field=models.TextField(verbose_name="genre de micro-organisme"),
            ),
        ),
        migrations.AddField(
            model_name="microorganism",
            name="is_obsolete",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.functions.comparison.Coalesce(
                    models.F("CA_is_obsolete"), models.F("siccrf_is_obsolete")
                ),
                output_field=models.BooleanField(verbose_name="objet obsolète"),
            ),
        ),
        migrations.AddField(
            model_name="microorganism",
            name="name",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.functions.comparison.Coalesce(
                    django.db.models.functions.comparison.NullIf(
                        models.F("CA_name"), models.Value("")
                    ),
                    models.F("siccrf_name"),
                ),
                output_field=models.TextField(verbose_name="nom"),
            ),
        ),
        migrations.AddField(
            model_name="part",
            name="is_useful",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.functions.comparison.Coalesce(
                    models.F("CA_is_useful"), models.F("siccrf_is_useful")
                ),
                output_field=models.BooleanField(verbose_name="🍵 utile ?"),
            ),
        ),
        migrations.AddField(
            model_name="part",
            name="must_be_monitored",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.functions.comparison.Coalesce(
                    models.F("CA_must_be_monitored"),
                    models.F("siccrf_must_be_monitored"),
                ),
                output_field=models.BooleanField(verbose_name="⚠️ à surveiller ?"),
            ),
        ),
        migrations.AddField(
            model_name="plant",
            name="family",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.functions.comparison.Coalesce(
                    models.F("CA_family"), models.F("siccrf_family")
                ),
                output_field=models.BigIntegerField(verbose_name="famille de plante"),
            ),
        ),
        migrations.AddField(
            model_name="plant",
            name="is_obsolete",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.functions.comparison.Coalesce(
                    models.F("CA_is_obsolete"), models.F("siccrf_is_obsolete")
                ),
                output_field=models.BooleanField(verbose_name="objet obsolète"),
            ),
        ),
        migrations.AddField(
            model_name="plant",
            name="name",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.functions.comparison.Coalesce(
                    django.db.models.functions.comparison.NullIf(
                        models.F("CA_name"), models.Value("")
                    ),
                    models.F("siccrf_name"),
                ),
                output_field=models.TextField(verbose_name="nom"),
            ),
        ),
        migrations.AddField(
            model_name="plantfamily",
            name="is_obsolete",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.functions.comparison.Coalesce(
                    models.F("CA_is_obsolete"), models.F("siccrf_is_obsolete")
                ),
                output_field=models.BooleanField(verbose_name="objet obsolète"),
            ),
        ),
        migrations.AddField(
            model_name="plantfamily",
            name="name",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.functions.comparison.Coalesce(
                    django.db.models.functions.comparison.NullIf(
                        models.F("CA_name"), models.Value("")
                    ),
                    models.F("siccrf_name"),
                ),
                output_field=models.TextField(verbose_name="nom"),
            ),
        ),
        migrations.AddField(
            model_name="plantpart",
            name="is_obsolete",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.functions.comparison.Coalesce(
                    models.F("CA_is_obsolete"), models.F("siccrf_is_obsolete")
                ),
                output_field=models.BooleanField(verbose_name="objet obsolète"),
            ),
        ),
        migrations.AddField(
            model_name="plantpart",
            name="name",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.functions.comparison.Coalesce(
                    django.db.models.functions.comparison.NullIf(
                        models.F("CA_name"), models.Value("")
                    ),
                    models.F("siccrf_name"),
                ),
                output_field=models.TextField(verbose_name="nom"),
            ),
        ),
        migrations.AddField(
            model_name="population",
            name="is_obsolete",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.functions.comparison.Coalesce(
                    models.F("CA_is_obsolete"), models.F("siccrf_is_obsolete")
                ),
                output_field=models.BooleanField(verbose_name="objet obsolète"),
            ),
        ),
        migrations.AddField(
            model_name="population",
            name="name",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.functions.comparison.Coalesce(
                    django.db.models.functions.comparison.NullIf(
                        models.F("CA_name"), models.Value("")
                    ),
                    models.F("siccrf_name"),
                ),
                output_field=models.TextField(verbose_name="nom"),
            ),
        ),
        migrations.AddField(
            model_name="substance",
            name="cas_number",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.functions.comparison.Coalesce(
                    django.db.models.functions.comparison.NullIf(
                        models.F("CA_cas_number"), models.Value("")
                    ),
                    models.F("siccrf_cas_number"),
                ),
                output_field=models.CharField(
                    blank=True, max_length=10, verbose_name="numéro CAS"
                ),
            ),
        ),
        migrations.AddField(
            model_name="substance",
            name="einec_number",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.functions.comparison.Coalesce(
                    django.db.models.functions.comparison.NullIf(
                        models.F("CA_einec_number"), models.Value("")
                    ),
                    models.F("siccrf_einec_number"),
                ),
                output_field=models.CharField(
                    blank=True, max_length=7, verbose_name="numéro EINECS"
                ),
            ),
        ),
        migrations.AddField(
            model_name="substance",
            name="is_obsolete",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.functions.comparison.Coalesce(
                    models.F("CA_is_obsolete"), models.F("siccrf_is_obsolete")
                ),
                output_field=models.BooleanField(verbose_name="objet obsolète"),
            ),
        ),
        migrations.AddField(
            model_name="substance",
            name="max_quantity",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.functions.comparison.Coalesce(
                    models.F("CA_nutritional_reference"),
                    models.F("siccrf_nutritional_reference"),
                ),
                output_field=models.FloatField(
                    blank=True,
                    null=True,
                    verbose_name="spécification de quantité obligatoire",
                ),
            ),
        ),
        migrations.AddField(
            model_name="substance",
            name="must_specify_quantity",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.functions.comparison.Coalesce(
                    models.F("CA_must_specify_quantity"),
                    models.F("siccrf_must_specify_quantity"),
                ),
                output_field=models.BooleanField(
                    default=False, verbose_name="spécification de quantité obligatoire"
                ),
            ),
        ),
        migrations.AddField(
            model_name="substance",
            name="name",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.functions.comparison.Coalesce(
                    django.db.models.functions.comparison.NullIf(
                        models.F("CA_name"), models.Value("")
                    ),
                    models.F("siccrf_name"),
                ),
                output_field=models.TextField(verbose_name="nom"),
            ),
        ),
        migrations.AddField(
            model_name="substance",
            name="nutritional_reference",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.functions.comparison.Coalesce(
                    "CA_nutritional_reference", "siccrf_nutritional_reference"
                ),
                output_field=models.FloatField(
                    blank=True, null=True, verbose_name="apport nutritionnel conseillé"
                ),
            ),
        ),
        migrations.AddField(
            model_name="substance",
            name="source",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.functions.comparison.Coalesce(
                    django.db.models.functions.comparison.NullIf(
                        models.F("CA_source"), models.Value("")
                    ),
                    models.F("siccrf_source"),
                ),
                output_field=models.TextField(),
            ),
        ),
        migrations.AlterField(
            model_name="condition",
            name="siccrf_is_obsolete",
            field=models.BooleanField(
                default=False,
                editable=False,
                verbose_name="objet obsolète selon SICCRF",
            ),
        ),
        migrations.AlterField(
            model_name="condition",
            name="siccrf_name",
            field=models.TextField(editable=False, verbose_name="nom SICCRF"),
        ),
        migrations.AlterField(
            model_name="historicalcondition",
            name="siccrf_is_obsolete",
            field=models.BooleanField(
                default=False,
                editable=False,
                verbose_name="objet obsolète selon SICCRF",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcondition",
            name="siccrf_name",
            field=models.TextField(editable=False, verbose_name="nom SICCRF"),
        ),
        migrations.AlterField(
            model_name="historicalingredient",
            name="siccrf_is_obsolete",
            field=models.BooleanField(
                default=False,
                editable=False,
                verbose_name="objet obsolète selon SICCRF",
            ),
        ),
        migrations.AlterField(
            model_name="historicalingredient",
            name="siccrf_name",
            field=models.TextField(editable=False, verbose_name="nom SICCRF"),
        ),
        migrations.AlterField(
            model_name="historicalingredient",
            name="siccrf_private_comments",
            field=models.TextField(
                blank=True, editable=False, verbose_name="commentaires privés SICCRF"
            ),
        ),
        migrations.AlterField(
            model_name="historicalingredient",
            name="siccrf_public_comments",
            field=models.TextField(
                blank=True, editable=False, verbose_name="commentaires publics SICCRF"
            ),
        ),
        migrations.AlterField(
            model_name="historicalingredientsynonym",
            name="siccrf_is_obsolete",
            field=models.BooleanField(
                default=False, verbose_name="objet obsolète selon SICCRF"
            ),
        ),
        migrations.AlterField(
            model_name="historicalmicroorganism",
            name="siccrf_genre",
            field=models.TextField(
                verbose_name="genre de micro-organisme (selon la base SICCRF)"
            ),
        ),
        migrations.AlterField(
            model_name="historicalmicroorganism",
            name="siccrf_is_obsolete",
            field=models.BooleanField(
                default=False,
                editable=False,
                verbose_name="objet obsolète selon SICCRF",
            ),
        ),
        migrations.AlterField(
            model_name="historicalmicroorganism",
            name="siccrf_name",
            field=models.TextField(editable=False, verbose_name="nom SICCRF"),
        ),
        migrations.AlterField(
            model_name="historicalmicroorganism",
            name="siccrf_private_comments",
            field=models.TextField(
                blank=True, editable=False, verbose_name="commentaires privés SICCRF"
            ),
        ),
        migrations.AlterField(
            model_name="historicalmicroorganism",
            name="siccrf_public_comments",
            field=models.TextField(
                blank=True, editable=False, verbose_name="commentaires publics SICCRF"
            ),
        ),
        migrations.AlterField(
            model_name="historicalmicroorganismsynonym",
            name="siccrf_is_obsolete",
            field=models.BooleanField(
                default=False, verbose_name="objet obsolète selon SICCRF"
            ),
        ),
        migrations.AlterField(
            model_name="historicalpart",
            name="siccrf_must_be_monitored",
            field=models.BooleanField(
                default=False, verbose_name="⚠️ à surveiller (selon la base SICCRF) ?"
            ),
        ),
        migrations.AlterField(
            model_name="historicalplant",
            name="siccrf_family",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="data.plantfamily",
                verbose_name="famille de plante (selon la base SICCRF)",
            ),
        ),
        migrations.AlterField(
            model_name="historicalplant",
            name="siccrf_is_obsolete",
            field=models.BooleanField(
                default=False,
                editable=False,
                verbose_name="objet obsolète selon SICCRF",
            ),
        ),
        migrations.AlterField(
            model_name="historicalplant",
            name="siccrf_name",
            field=models.TextField(editable=False, verbose_name="nom SICCRF"),
        ),
        migrations.AlterField(
            model_name="historicalplant",
            name="siccrf_private_comments",
            field=models.TextField(
                blank=True, editable=False, verbose_name="commentaires privés SICCRF"
            ),
        ),
        migrations.AlterField(
            model_name="historicalplant",
            name="siccrf_public_comments",
            field=models.TextField(
                blank=True, editable=False, verbose_name="commentaires publics SICCRF"
            ),
        ),
        migrations.AlterField(
            model_name="historicalplantfamily",
            name="siccrf_is_obsolete",
            field=models.BooleanField(
                default=False,
                editable=False,
                verbose_name="objet obsolète selon SICCRF",
            ),
        ),
        migrations.AlterField(
            model_name="historicalplantfamily",
            name="siccrf_name",
            field=models.TextField(editable=False, verbose_name="nom SICCRF"),
        ),
        migrations.AlterField(
            model_name="historicalplantpart",
            name="siccrf_is_obsolete",
            field=models.BooleanField(
                default=False,
                editable=False,
                verbose_name="objet obsolète selon SICCRF",
            ),
        ),
        migrations.AlterField(
            model_name="historicalplantpart",
            name="siccrf_name",
            field=models.TextField(editable=False, verbose_name="nom SICCRF"),
        ),
        migrations.AlterField(
            model_name="historicalplantsynonym",
            name="siccrf_is_obsolete",
            field=models.BooleanField(
                default=False, verbose_name="objet obsolète selon SICCRF"
            ),
        ),
        migrations.AlterField(
            model_name="historicalpopulation",
            name="siccrf_is_obsolete",
            field=models.BooleanField(
                default=False,
                editable=False,
                verbose_name="objet obsolète selon SICCRF",
            ),
        ),
        migrations.AlterField(
            model_name="historicalpopulation",
            name="siccrf_name",
            field=models.TextField(editable=False, verbose_name="nom SICCRF"),
        ),
        migrations.AlterField(
            model_name="historicalsubstance",
            name="siccrf_cas_number",
            field=models.CharField(
                blank=True,
                max_length=10,
                verbose_name="numéro CAS (selon la base SICCRF)",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubstance",
            name="siccrf_einec_number",
            field=models.CharField(
                blank=True,
                max_length=7,
                verbose_name="numéro EINECS (selon la base SICCRF)",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubstance",
            name="siccrf_is_obsolete",
            field=models.BooleanField(
                default=False,
                editable=False,
                verbose_name="objet obsolète selon SICCRF",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubstance",
            name="siccrf_max_quantity",
            field=models.FloatField(
                blank=True,
                null=True,
                verbose_name="quantité maximale autorisée (selon la base SICCRF)",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubstance",
            name="siccrf_must_specify_quantity",
            field=models.BooleanField(
                default=False,
                verbose_name="spécification de quantité obligatoire (selon la base SICCRF)",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubstance",
            name="siccrf_name",
            field=models.TextField(editable=False, verbose_name="nom SICCRF"),
        ),
        migrations.AlterField(
            model_name="historicalsubstance",
            name="siccrf_private_comments",
            field=models.TextField(
                blank=True, editable=False, verbose_name="commentaires privés SICCRF"
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubstance",
            name="siccrf_public_comments",
            field=models.TextField(
                blank=True, editable=False, verbose_name="commentaires publics SICCRF"
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubstancesynonym",
            name="siccrf_is_obsolete",
            field=models.BooleanField(
                default=False, verbose_name="objet obsolète selon SICCRF"
            ),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="siccrf_is_obsolete",
            field=models.BooleanField(
                default=False,
                editable=False,
                verbose_name="objet obsolète selon SICCRF",
            ),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="siccrf_name",
            field=models.TextField(editable=False, verbose_name="nom SICCRF"),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="siccrf_private_comments",
            field=models.TextField(
                blank=True, editable=False, verbose_name="commentaires privés SICCRF"
            ),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="siccrf_public_comments",
            field=models.TextField(
                blank=True, editable=False, verbose_name="commentaires publics SICCRF"
            ),
        ),
        migrations.AlterField(
            model_name="ingredientsynonym",
            name="siccrf_is_obsolete",
            field=models.BooleanField(
                default=False, verbose_name="objet obsolète selon SICCRF"
            ),
        ),
        migrations.AlterField(
            model_name="microorganism",
            name="siccrf_genre",
            field=models.TextField(
                verbose_name="genre de micro-organisme (selon la base SICCRF)"
            ),
        ),
        migrations.AlterField(
            model_name="microorganism",
            name="siccrf_is_obsolete",
            field=models.BooleanField(
                default=False,
                editable=False,
                verbose_name="objet obsolète selon SICCRF",
            ),
        ),
        migrations.AlterField(
            model_name="microorganism",
            name="siccrf_name",
            field=models.TextField(editable=False, verbose_name="nom SICCRF"),
        ),
        migrations.AlterField(
            model_name="microorganism",
            name="siccrf_private_comments",
            field=models.TextField(
                blank=True, editable=False, verbose_name="commentaires privés SICCRF"
            ),
        ),
        migrations.AlterField(
            model_name="microorganism",
            name="siccrf_public_comments",
            field=models.TextField(
                blank=True, editable=False, verbose_name="commentaires publics SICCRF"
            ),
        ),
        migrations.AlterField(
            model_name="microorganismsubstancerelation",
            name="CA_is_related",
            field=models.BooleanField(
                default=None,
                null=True,
                verbose_name="substance associée au micro-organisme",
            ),
        ),
        migrations.AlterField(
            model_name="microorganismsubstancerelation",
            name="siccrf_is_related",
            field=models.BooleanField(
                default=False,
                verbose_name="substance associée au micro-organisme (selon la base SICCRF)",
            ),
        ),
        migrations.AlterField(
            model_name="microorganismsynonym",
            name="siccrf_is_obsolete",
            field=models.BooleanField(
                default=False, verbose_name="objet obsolète selon SICCRF"
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="siccrf_must_be_monitored",
            field=models.BooleanField(
                default=False, verbose_name="⚠️ à surveiller (selon la base SICCRF) ?"
            ),
        ),
        migrations.AlterField(
            model_name="plant",
            name="CA_family",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="CA_plant_set",
                to="data.plantfamily",
                verbose_name="famille de plante",
            ),
        ),
        migrations.AlterField(
            model_name="plant",
            name="siccrf_is_obsolete",
            field=models.BooleanField(
                default=False,
                editable=False,
                verbose_name="objet obsolète selon SICCRF",
            ),
        ),
        migrations.AlterField(
            model_name="plant",
            name="siccrf_name",
            field=models.TextField(editable=False, verbose_name="nom SICCRF"),
        ),
        migrations.AlterField(
            model_name="plant",
            name="siccrf_private_comments",
            field=models.TextField(
                blank=True, editable=False, verbose_name="commentaires privés SICCRF"
            ),
        ),
        migrations.AlterField(
            model_name="plant",
            name="siccrf_public_comments",
            field=models.TextField(
                blank=True, editable=False, verbose_name="commentaires publics SICCRF"
            ),
        ),
        migrations.AlterField(
            model_name="plantfamily",
            name="siccrf_is_obsolete",
            field=models.BooleanField(
                default=False,
                editable=False,
                verbose_name="objet obsolète selon SICCRF",
            ),
        ),
        migrations.AlterField(
            model_name="plantfamily",
            name="siccrf_name",
            field=models.TextField(editable=False, verbose_name="nom SICCRF"),
        ),
        migrations.AlterField(
            model_name="plantpart",
            name="siccrf_is_obsolete",
            field=models.BooleanField(
                default=False,
                editable=False,
                verbose_name="objet obsolète selon SICCRF",
            ),
        ),
        migrations.AlterField(
            model_name="plantpart",
            name="siccrf_name",
            field=models.TextField(editable=False, verbose_name="nom SICCRF"),
        ),
        migrations.AlterField(
            model_name="plantsubstancerelation",
            name="CA_is_related",
            field=models.BooleanField(
                default=None, null=True, verbose_name="substance associée à la plante"
            ),
        ),
        migrations.AlterField(
            model_name="plantsubstancerelation",
            name="siccrf_is_related",
            field=models.BooleanField(
                default=False,
                verbose_name="substance associée à la plante (selon la base SICCRF)",
            ),
        ),
        migrations.AlterField(
            model_name="plantsynonym",
            name="siccrf_is_obsolete",
            field=models.BooleanField(
                default=False, verbose_name="objet obsolète selon SICCRF"
            ),
        ),
        migrations.AlterField(
            model_name="population",
            name="siccrf_is_obsolete",
            field=models.BooleanField(
                default=False,
                editable=False,
                verbose_name="objet obsolète selon SICCRF",
            ),
        ),
        migrations.AlterField(
            model_name="population",
            name="siccrf_name",
            field=models.TextField(editable=False, verbose_name="nom SICCRF"),
        ),
        migrations.AlterField(
            model_name="substance",
            name="siccrf_cas_number",
            field=models.CharField(
                blank=True,
                max_length=10,
                verbose_name="numéro CAS (selon la base SICCRF)",
            ),
        ),
        migrations.AlterField(
            model_name="substance",
            name="siccrf_einec_number",
            field=models.CharField(
                blank=True,
                max_length=7,
                verbose_name="numéro EINECS (selon la base SICCRF)",
            ),
        ),
        migrations.AlterField(
            model_name="substance",
            name="siccrf_is_obsolete",
            field=models.BooleanField(
                default=False,
                editable=False,
                verbose_name="objet obsolète selon SICCRF",
            ),
        ),
        migrations.AlterField(
            model_name="substance",
            name="siccrf_max_quantity",
            field=models.FloatField(
                blank=True,
                null=True,
                verbose_name="quantité maximale autorisée (selon la base SICCRF)",
            ),
        ),
        migrations.AlterField(
            model_name="substance",
            name="siccrf_must_specify_quantity",
            field=models.BooleanField(
                default=False,
                verbose_name="spécification de quantité obligatoire (selon la base SICCRF)",
            ),
        ),
        migrations.AlterField(
            model_name="substance",
            name="siccrf_name",
            field=models.TextField(editable=False, verbose_name="nom SICCRF"),
        ),
        migrations.AlterField(
            model_name="substance",
            name="siccrf_private_comments",
            field=models.TextField(
                blank=True, editable=False, verbose_name="commentaires privés SICCRF"
            ),
        ),
        migrations.AlterField(
            model_name="substance",
            name="siccrf_public_comments",
            field=models.TextField(
                blank=True, editable=False, verbose_name="commentaires publics SICCRF"
            ),
        ),
        migrations.AlterField(
            model_name="substancesynonym",
            name="siccrf_is_obsolete",
            field=models.BooleanField(
                default=False, verbose_name="objet obsolète selon SICCRF"
            ),
        ),
        migrations.CreateModel(
            name="HistoricalIngredientSubstanceRelation",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("creation_date", models.DateTimeField(blank=True, editable=False)),
                ("modification_date", models.DateTimeField(blank=True, editable=False)),
                (
                    "siccrf_is_related",
                    models.BooleanField(
                        default=False,
                        verbose_name="substance associée à l'ingrédient (selon la base SICCRF)",
                    ),
                ),
                (
                    "CA_is_related",
                    models.BooleanField(
                        default=None,
                        null=True,
                        verbose_name="substance associée à l'ingrédient",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="data.ingredient",
                    ),
                ),
                (
                    "substance",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="data.substance",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical ingredient substance relation",
                "verbose_name_plural": "historical ingredient substance relations",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalMicroorganismSubstanceRelation",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("creation_date", models.DateTimeField(blank=True, editable=False)),
                ("modification_date", models.DateTimeField(blank=True, editable=False)),
                (
                    "siccrf_is_related",
                    models.BooleanField(
                        default=False,
                        verbose_name="substance associée au micro-organisme (selon la base SICCRF)",
                    ),
                ),
                (
                    "CA_is_related",
                    models.BooleanField(
                        default=None,
                        null=True,
                        verbose_name="substance associée au micro-organisme",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "microorganism",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="data.microorganism",
                    ),
                ),
                (
                    "substance",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="data.substance",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical microorganism substance relation",
                "verbose_name_plural": "historical microorganism substance relations",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalPlantSubstanceRelation",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("creation_date", models.DateTimeField(blank=True, editable=False)),
                ("modification_date", models.DateTimeField(blank=True, editable=False)),
                (
                    "siccrf_is_related",
                    models.BooleanField(
                        default=False,
                        verbose_name="substance associée à la plante (selon la base SICCRF)",
                    ),
                ),
                (
                    "CA_is_related",
                    models.BooleanField(
                        default=None,
                        null=True,
                        verbose_name="substance associée à la plante",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="data.plant",
                    ),
                ),
                (
                    "substance",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="data.substance",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical plant substance relation",
                "verbose_name_plural": "historical plant substance relations",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
