# Generated by Django 5.0.2 on 2024-02-20 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0019_condition_is_obsolete_condition_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalingredientsynonym",
            name="name",
        ),
        migrations.RemoveField(
            model_name="historicalmicroorganismsynonym",
            name="name",
        ),
        migrations.RemoveField(
            model_name="historicalplantsynonym",
            name="name",
        ),
        migrations.RemoveField(
            model_name="ingredientsynonym",
            name="name",
        ),
        migrations.RemoveField(
            model_name="microorganismsynonym",
            name="name",
        ),
        migrations.RemoveField(
            model_name="plantsynonym",
            name="name",
        ),
        migrations.RemoveField(
            model_name="substancesynonym",
            name="name",
        ),
        migrations.RemoveField(
            model_name="historicalsubstancesynonym",
            name="name",
        ),
        migrations.RenameField(model_name="historicalingredientsynonym", old_name="siccrf_name", new_name="name"),
        migrations.RenameField(model_name="historicalmicroorganismsynonym", old_name="siccrf_name", new_name="name"),
        migrations.RenameField(model_name="historicalplantsynonym", old_name="siccrf_name", new_name="name"),
        migrations.RenameField(model_name="ingredientsynonym", old_name="siccrf_name", new_name="name"),
        migrations.RenameField(model_name="microorganismsynonym", old_name="siccrf_name", new_name="name"),
        migrations.RenameField(model_name="plantsynonym", old_name="siccrf_name", new_name="name"),
        migrations.RenameField(model_name="substancesynonym", old_name="siccrf_name", new_name="name"),
        migrations.RenameField(model_name="historicalsubstancesynonym", old_name="siccrf_name", new_name="name"),
        migrations.RemoveField(
            model_name="historicalingredientsynonym",
            name="CA_is_obsolete",
        ),
        migrations.RemoveField(
            model_name="historicalingredientsynonym",
            name="CA_name",
        ),
        migrations.RemoveField(
            model_name="historicalmicroorganismsynonym",
            name="CA_is_obsolete",
        ),
        migrations.RemoveField(
            model_name="historicalmicroorganismsynonym",
            name="CA_name",
        ),
        migrations.RemoveField(
            model_name="historicalplantsynonym",
            name="CA_is_obsolete",
        ),
        migrations.RemoveField(
            model_name="historicalplantsynonym",
            name="CA_name",
        ),
        migrations.RemoveField(
            model_name="historicalsubstancesynonym",
            name="CA_is_obsolete",
        ),
        migrations.RemoveField(
            model_name="historicalsubstancesynonym",
            name="CA_name",
        ),
        migrations.RemoveField(
            model_name="ingredientsynonym",
            name="CA_is_obsolete",
        ),
        migrations.RemoveField(
            model_name="ingredientsynonym",
            name="CA_name",
        ),
        migrations.RemoveField(
            model_name="microorganismsynonym",
            name="CA_is_obsolete",
        ),
        migrations.RemoveField(
            model_name="microorganismsynonym",
            name="CA_name",
        ),
        migrations.RemoveField(
            model_name="plantsynonym",
            name="CA_is_obsolete",
        ),
        migrations.RemoveField(
            model_name="plantsynonym",
            name="CA_name",
        ),
        migrations.RemoveField(
            model_name="substancesynonym",
            name="CA_is_obsolete",
        ),
        migrations.RemoveField(
            model_name="substancesynonym",
            name="CA_name",
        ),
    ]
