# Generated by Django 5.0.2 on 2024-03-07 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0018_alter_blogpost_body"),
        ("data", "0021_alter_condition_is_obsolete_alter_condition_name_and_more"),
    ]

    operations = []
