# Generated by Django 5.0.2 on 2024-02-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0021_remove_historicalcondition_is_obsolete_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="condition",
            name="CA_is_obsolete",
            field=models.BooleanField(default=None, null=True, verbose_name="objet obsolète selon CA"),
        ),
        migrations.AlterField(
            model_name="historicalcondition",
            name="CA_is_obsolete",
            field=models.BooleanField(default=None, null=True, verbose_name="objet obsolète selon CA"),
        ),
        migrations.AlterField(
            model_name="historicalingredient",
            name="CA_is_obsolete",
            field=models.BooleanField(default=None, null=True, verbose_name="objet obsolète selon CA"),
        ),
        migrations.AlterField(
            model_name="historicalingredientsubstancerelation",
            name="CA_is_related",
            field=models.BooleanField(
                default=None,
                null=True,
                verbose_name="substance associée à l'ingrédient",
            ),
        ),
        migrations.AlterField(
            model_name="historicalmicroorganism",
            name="CA_is_obsolete",
            field=models.BooleanField(default=None, null=True, verbose_name="objet obsolète selon CA"),
        ),
        migrations.AlterField(
            model_name="historicalmicroorganismsubstancerelation",
            name="CA_is_related",
            field=models.BooleanField(
                default=None,
                null=True,
                verbose_name="substance associée au micro-organisme",
            ),
        ),
        migrations.AlterField(
            model_name="historicalpart",
            name="CA_is_useful",
            field=models.BooleanField(default=None, null=True, verbose_name="🍵 utile ?"),
        ),
        migrations.AlterField(
            model_name="historicalpart",
            name="CA_must_be_monitored",
            field=models.BooleanField(default=None, null=True, verbose_name="⚠️ à surveiller ?"),
        ),
        migrations.AlterField(
            model_name="historicalplant",
            name="CA_is_obsolete",
            field=models.BooleanField(default=None, null=True, verbose_name="objet obsolète selon CA"),
        ),
        migrations.AlterField(
            model_name="historicalplantfamily",
            name="CA_is_obsolete",
            field=models.BooleanField(default=None, null=True, verbose_name="objet obsolète selon CA"),
        ),
        migrations.AlterField(
            model_name="historicalplantpart",
            name="CA_is_obsolete",
            field=models.BooleanField(default=None, null=True, verbose_name="objet obsolète selon CA"),
        ),
        migrations.AlterField(
            model_name="historicalplantsubstancerelation",
            name="CA_is_related",
            field=models.BooleanField(default=None, null=True, verbose_name="substance associée à la plante"),
        ),
        migrations.AlterField(
            model_name="historicalpopulation",
            name="CA_is_obsolete",
            field=models.BooleanField(default=None, null=True, verbose_name="objet obsolète selon CA"),
        ),
        migrations.AlterField(
            model_name="historicalsubstance",
            name="CA_is_obsolete",
            field=models.BooleanField(default=None, null=True, verbose_name="objet obsolète selon CA"),
        ),
        migrations.AlterField(
            model_name="historicalsubstance",
            name="CA_must_specify_quantity",
            field=models.BooleanField(
                default=None,
                null=True,
                verbose_name="spécification de quantité obligatoire",
            ),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="CA_is_obsolete",
            field=models.BooleanField(default=None, null=True, verbose_name="objet obsolète selon CA"),
        ),
        migrations.AlterField(
            model_name="ingredientsubstancerelation",
            name="CA_is_related",
            field=models.BooleanField(
                default=None,
                null=True,
                verbose_name="substance associée à l'ingrédient",
            ),
        ),
        migrations.AlterField(
            model_name="microorganism",
            name="CA_is_obsolete",
            field=models.BooleanField(default=None, null=True, verbose_name="objet obsolète selon CA"),
        ),
        migrations.AlterField(
            model_name="microorganismsubstancerelation",
            name="CA_is_related",
            field=models.BooleanField(
                default=None,
                null=True,
                verbose_name="substance associée au micro-organisme",
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="CA_is_useful",
            field=models.BooleanField(default=None, null=True, verbose_name="🍵 utile ?"),
        ),
        migrations.AlterField(
            model_name="part",
            name="CA_must_be_monitored",
            field=models.BooleanField(default=None, null=True, verbose_name="⚠️ à surveiller ?"),
        ),
        migrations.AlterField(
            model_name="plant",
            name="CA_is_obsolete",
            field=models.BooleanField(default=None, null=True, verbose_name="objet obsolète selon CA"),
        ),
        migrations.AlterField(
            model_name="plantfamily",
            name="CA_is_obsolete",
            field=models.BooleanField(default=None, null=True, verbose_name="objet obsolète selon CA"),
        ),
        migrations.AlterField(
            model_name="plantpart",
            name="CA_is_obsolete",
            field=models.BooleanField(default=None, null=True, verbose_name="objet obsolète selon CA"),
        ),
        migrations.AlterField(
            model_name="plantsubstancerelation",
            name="CA_is_related",
            field=models.BooleanField(default=None, null=True, verbose_name="substance associée à la plante"),
        ),
        migrations.AlterField(
            model_name="population",
            name="CA_is_obsolete",
            field=models.BooleanField(default=None, null=True, verbose_name="objet obsolète selon CA"),
        ),
        migrations.AlterField(
            model_name="substance",
            name="CA_is_obsolete",
            field=models.BooleanField(default=None, null=True, verbose_name="objet obsolète selon CA"),
        ),
        migrations.AlterField(
            model_name="substance",
            name="CA_must_specify_quantity",
            field=models.BooleanField(
                default=None,
                null=True,
                verbose_name="spécification de quantité obligatoire",
            ),
        ),
    ]
