# Generated by Django 5.0.3 on 2024-03-18 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0022_merge_20240307_1122"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubstanceUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "missing_import_data",
                    models.BooleanField(
                        blank=True, default=False, editable=False, null=True
                    ),
                ),
                (
                    "siccrf_id",
                    models.IntegerField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        null=True,
                        unique=True,
                        verbose_name="id dans les tables et tables relationnelles SICCRF",
                    ),
                ),
                ("name", models.CharField(max_length=2, verbose_name="unité")),
                ("long_name", models.TextField(verbose_name="unité détaillée")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="historicalsubstance",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="data.substanceunit",
                verbose_name="unité des quantités spécifiées (quantité max, apport de référence)",
            ),
        ),
        migrations.AddField(
            model_name="substance",
            name="unit",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="data.substanceunit",
                verbose_name="unité des quantités spécifiées (quantité max, apport de référence)",
            ),
        ),
    ]
