# Generated by Django 5.0.2 on 2024-03-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0022_merge_20240307_1122"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "get_latest_by": "date_joined",
                "ordering": ["-date_joined"],
                "verbose_name": "utilisateur",
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
