# Generated by Django 5.0.2 on 2024-03-07 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0024_companysupervisor_company_declarant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="supervisor",
        ),
        migrations.AddField(
            model_name="companysupervisor",
            name="company",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="data.company",
                verbose_name="company",
            ),
            preserve_default=False,
        ),
    ]
