# Generated by Django 5.0.2 on 2024-03-07 14:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0025_remove_company_supervisor_companysupervisor_company"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={"verbose_name": "entreprise"},
        ),
        migrations.AlterField(
            model_name="company",
            name="siret",
            field=models.CharField(
                help_text="14 chiffres",
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(14),
                    django.core.validators.MaxLengthValidator(14),
                ],
                verbose_name="n° SIRET",
            ),
        ),
        migrations.AlterField(
            model_name="companysupervisor",
            name="company",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="data.company",
                verbose_name="entreprise",
            ),
        ),
    ]
