# Generated by Django 5.0.2 on 2024-03-11 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0026_alter_company_options_alter_company_siret_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
