# Generated by Django 5.0.2 on 2024-03-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0027_alter_user_managers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="companysupervisor",
            name="company",
        ),
        migrations.AddField(
            model_name="companysupervisor",
            name="companies",
            field=models.ManyToManyField(to="data.company", verbose_name="entreprises"),
        ),
    ]
