# Generated by Django 5.0.2 on 2024-03-11 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0028_remove_companysupervisor_company_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="companysupervisor",
            options={
                "verbose_name": "gestionnaire d'entreprises",
                "verbose_name_plural": "gestionnaires d'entreprises",
            },
        ),
    ]
