# Generated by Django 5.0.2 on 2024-03-22 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0032_substanceunit_historicalsubstance_unit_and_more"),
        ("data", "0032_user_is_verified"),
    ]

    operations = []
