# Generated by Django 5.0.3 on 2024-03-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0032_substanceunit_historicalsubstance_unit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="additional_details",
            field=models.CharField(
                blank=True,
                help_text="bâtiment, immeuble, escalier et numéro d’appartement",
                verbose_name="complément d’adresse",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="address",
            field=models.CharField(default="addresse", help_text="numéro et voie", verbose_name="adresse"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="company",
            name="cedex",
            field=models.CharField(blank=True, verbose_name="CEDEX"),
        ),
        migrations.AddField(
            model_name="company",
            name="city",
            field=models.CharField(default="ville", verbose_name="ville ou commune"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="company",
            name="country",
            field=models.CharField(
                choices=[
                    ("FR", "France"),
                    ("DE", "Allemagne"),
                    ("AT", "Autriche"),
                    ("BE", "Belgique"),
                    ("BG", "Bulgarie"),
                    ("CY", "Chypre"),
                    ("HR", "Croatie"),
                    ("DK", "Danemark"),
                    ("ES", "Espagne"),
                    ("EE", "Estonie"),
                    ("FI", "Finlande"),
                    ("GR", "Grèce"),
                    ("HU", "Hongrie"),
                    ("IE", "Irlande"),
                    ("NI", "Irlande du Nord"),
                    ("IS", "Islande"),
                    ("IT", "Italie"),
                    ("LV", "Lettonie"),
                    ("LI", "Liechtenstein"),
                    ("LT", "Lituanie"),
                    ("LU", "Luxembourg"),
                    ("MT", "Malte"),
                    ("NO", "Norvège"),
                    ("NL", "Pays-Bas"),
                    ("PL", "Pologne"),
                    ("PT", "Portugal"),
                    ("RO", "Roumanie"),
                    ("SK", "Slovaquie"),
                    ("SI", "Slovénie"),
                    ("SE", "Suède"),
                    ("CZ", "République Tchèque"),
                ],
                default="FR",
                max_length=50,
                verbose_name="pays",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="postal_code",
            field=models.CharField(default="12345", max_length=10, verbose_name="code postal"),
            preserve_default=False,
        ),
    ]
