# Generated by Django 5.0.3 on 2024-03-26 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0033_company_additional_details_company_address_and_more"),
        ("data", "0034_user_phone_number"),
    ]

    operations = []
