# Generated by Django 5.0.3 on 2024-03-27 16:54

import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0035_merge_20240326_1031"),
    ]

    operations = [
        # Opération ajoutée à posteriori car impossible de supprimer ca_name si le champ généré
        # existe encore. Contrainte sur Django 6 + Postgresql 15
        migrations.RemoveField(
            model_name="microorganism",
            name="name",
        ),
        ####################################################################
        migrations.RemoveField(
            model_name="historicalmicroorganism",
            name="ca_name",
        ),
        migrations.RemoveField(
            model_name="historicalmicroorganism",
            name="siccrf_name",
        ),
        migrations.RemoveField(
            model_name="microorganism",
            name="ca_name",
        ),
        migrations.RemoveField(
            model_name="microorganism",
            name="siccrf_name",
        ),
        migrations.RemoveField(
            model_name="microorganism",
            name="genre",
        ),
        migrations.AddField(
            model_name="historicalmicroorganism",
            name="ca_espece",
            field=models.TextField(default="", verbose_name="espèce de micro-organisme"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalmicroorganism",
            name="siccrf_espece",
            field=models.TextField(
                default="",
                verbose_name="espèce de micro-organisme (selon la base SICCRF)",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="microorganism",
            name="ca_espece",
            field=models.TextField(default="", verbose_name="espèce de micro-organisme"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="microorganism",
            name="siccrf_espece",
            field=models.TextField(
                default="",
                verbose_name="espèce de micro-organisme (selon la base SICCRF)",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="microorganism",
            name="name",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.functions.comparison.Coalesce(
                    django.db.models.functions.comparison.Coalesce(
                        django.db.models.functions.comparison.NullIf(models.F("ca_genre"), models.Value("")),
                        models.F("siccrf_genre"),
                    ),
                    django.db.models.functions.comparison.Coalesce(
                        django.db.models.functions.comparison.NullIf(models.F("ca_espece"), models.Value("")),
                        models.F("siccrf_espece"),
                    ),
                ),
                output_field=models.TextField(verbose_name="nom"),
            ),
        ),
    ]
