# Generated by Django 5.0.3 on 2024-03-27 17:28

import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0036_remove_historicalmicroorganism_ca_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="microorganism",
            name="name",
        ),
        migrations.RenameField(
            model_name="historicalmicroorganism",
            old_name="ca_genre",
            new_name="ca_genus",
        ),
        migrations.RenameField(
            model_name="historicalmicroorganism",
            old_name="ca_espece",
            new_name="ca_species",
        ),
        migrations.RenameField(
            model_name="historicalmicroorganism",
            old_name="siccrf_genre",
            new_name="siccrf_genus",
        ),
        migrations.RenameField(
            model_name="historicalmicroorganism",
            old_name="siccrf_espece",
            new_name="siccrf_species",
        ),
        migrations.RenameField(
            model_name="microorganism",
            old_name="ca_genre",
            new_name="ca_genus",
        ),
        migrations.RenameField(
            model_name="microorganism",
            old_name="ca_espece",
            new_name="ca_species",
        ),
        migrations.RenameField(
            model_name="microorganism",
            old_name="siccrf_genre",
            new_name="siccrf_genus",
        ),
        migrations.RenameField(
            model_name="microorganism",
            old_name="siccrf_espece",
            new_name="siccrf_species",
        ),
        migrations.RemoveField(
            model_name="historicalmicroorganism",
            name="siccrf_name_en",
        ),
        migrations.RemoveField(
            model_name="microorganism",
            name="siccrf_name_en",
        ),
        migrations.AddField(
            model_name="microorganism",
            name="genus",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.functions.comparison.Coalesce(
                    django.db.models.functions.comparison.NullIf(models.F("ca_genus"), models.Value("")),
                    models.F("siccrf_genus"),
                ),
                output_field=models.TextField(verbose_name="genre de micro-organisme"),
            ),
        ),
        migrations.AddField(
            model_name="microorganism",
            name="species",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.functions.comparison.Coalesce(
                    django.db.models.functions.comparison.NullIf(models.F("ca_species"), models.Value("")),
                    models.F("siccrf_species"),
                ),
                output_field=models.TextField(verbose_name="espèce de micro-organisme"),
            ),
        ),
        migrations.AddField(
            model_name="microorganism",
            name="name",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.functions.comparison.Coalesce(
                    django.db.models.functions.comparison.Coalesce(
                        django.db.models.functions.comparison.NullIf(models.F("ca_genus"), models.Value("")),
                        models.F("siccrf_genus"),
                    ),
                    django.db.models.functions.comparison.Coalesce(
                        django.db.models.functions.comparison.NullIf(models.F("ca_species"), models.Value("")),
                        models.F("siccrf_species"),
                    ),
                ),
                output_field=models.TextField(verbose_name="nom"),
            ),
        ),
    ]
