# Generated by Django 5.0.3 on 2024-03-27 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0036_remove_historicalmicroorganism_ca_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalmicroorganism",
            name="siccrf_name_en",
        ),
        migrations.RemoveField(
            model_name="microorganism",
            name="siccrf_name_en",
        ),
    ]
