# Generated by Django 5.0.3 on 2024-03-31 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0037_rename_ca_genre_historicalmicroorganism_ca_genus_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=False, verbose_name="Vérifié ?"),
        ),
    ]
