# Generated by Django 5.0.3 on 2024-03-29 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0036_declarant_companies"),
        ("data", "0037_rename_ca_genre_historicalmicroorganism_ca_genus_and_more"),
    ]

    operations = []
