# Generated by Django 5.0.3 on 2024-03-29 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0038_merge_20240329_1347"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalingredient",
            name="private_comments",
        ),
        migrations.RemoveField(
            model_name="historicalingredient",
            name="public_comments",
        ),
        migrations.RemoveField(
            model_name="historicalmicroorganism",
            name="private_comments",
        ),
        migrations.RemoveField(
            model_name="historicalmicroorganism",
            name="public_comments",
        ),
        migrations.RemoveField(
            model_name="historicalplant",
            name="private_comments",
        ),
        migrations.RemoveField(
            model_name="historicalplant",
            name="public_comments",
        ),
        migrations.RemoveField(
            model_name="historicalsubstance",
            name="private_comments",
        ),
        migrations.RemoveField(
            model_name="historicalsubstance",
            name="public_comments",
        ),
    ]
