# Generated by Django 5.0.3 on 2024-03-31 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0038_alter_user_is_verified"),
        ("data", "0038_merge_20240329_1347"),
    ]

    operations = []
