# Generated by Django 5.0.3 on 2024-04-04 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0039_remove_historicalingredient_private_comments_and_more"),
        ("data", "0041_alter_declaration_postal_code_and_more"),
    ]

    operations = []
