# Generated by Django 5.0.3 on 2024-04-04 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0039_merge_20240331_1811'),
        ('data', '0042_merge_20240404_1103'),
    ]

    operations = [
    ]
