# Generated by Django 5.0.3 on 2024-04-04 14:44

import django.db.models.deletion
import django.db.models.functions.comparison
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0043_merge_20240404_1354"),
    ]

    operations = [
        migrations.CreateModel(
            name="Effect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("modification_date", models.DateTimeField(auto_now=True)),
                (
                    "missing_import_data",
                    models.BooleanField(blank=True, default=False, editable=False, null=True),
                ),
                (
                    "siccrf_id",
                    models.IntegerField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        null=True,
                        unique=True,
                        verbose_name="id dans les tables et tables relationnelles SICCRF",
                    ),
                ),
                (
                    "siccrf_name",
                    models.TextField(editable=False, verbose_name="nom SICCRF"),
                ),
                ("ca_name", models.TextField(verbose_name="nom CA")),
                (
                    "name",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.functions.comparison.Coalesce(
                            django.db.models.functions.comparison.NullIf(models.F("ca_name"), models.Value("")),
                            models.F("siccrf_name"),
                        ),
                        output_field=models.TextField(verbose_name="nom"),
                    ),
                ),
                (
                    "siccrf_is_obsolete",
                    models.BooleanField(
                        default=False,
                        editable=False,
                        verbose_name="objet obsolète selon SICCRF",
                    ),
                ),
                (
                    "ca_is_obsolete",
                    models.BooleanField(default=None, null=True, verbose_name="objet obsolète selon CA"),
                ),
                (
                    "is_obsolete",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.functions.comparison.Coalesce(
                            models.F("ca_is_obsolete"), models.F("siccrf_is_obsolete")
                        ),
                        output_field=models.BooleanField(verbose_name="objet obsolète"),
                    ),
                ),
                ("siccrf_name_en", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Objectifs et effets des compléments alimentaires",
            },
        ),
        migrations.CreateModel(
            name="HistoricalEffect",
            fields=[
                (
                    "id",
                    models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID"),
                ),
                ("creation_date", models.DateTimeField(blank=True, editable=False)),
                ("modification_date", models.DateTimeField(blank=True, editable=False)),
                (
                    "missing_import_data",
                    models.BooleanField(blank=True, default=False, editable=False, null=True),
                ),
                (
                    "siccrf_id",
                    models.IntegerField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        null=True,
                        verbose_name="id dans les tables et tables relationnelles SICCRF",
                    ),
                ),
                (
                    "siccrf_name",
                    models.TextField(editable=False, verbose_name="nom SICCRF"),
                ),
                ("ca_name", models.TextField(verbose_name="nom CA")),
                (
                    "siccrf_is_obsolete",
                    models.BooleanField(
                        default=False,
                        editable=False,
                        verbose_name="objet obsolète selon SICCRF",
                    ),
                ),
                (
                    "ca_is_obsolete",
                    models.BooleanField(default=None, null=True, verbose_name="objet obsolète selon CA"),
                ),
                ("siccrf_name_en", models.TextField(blank=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Objectifs et effets des compléments alimentaires",
                "verbose_name_plural": "historical Objectifs et effets des compléments alimentairess",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
