# Generated by Django 5.0.3 on 2024-04-09 12:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0043_merge_20240404_1354"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="vat",
            field=models.CharField(
                blank=True,
                null=True,
                unique=True,
                verbose_name="n° TVA intracommunautaire",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="siret",
            field=models.CharField(
                blank=True,
                help_text="14 chiffres",
                null=True,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(14),
                    django.core.validators.MaxLengthValidator(14),
                ],
                verbose_name="n° SIRET",
            ),
        ),
        migrations.AlterField(
            model_name="companysupervisor",
            name="companies",
            field=models.ManyToManyField(
                related_name="supervisors",
                to="data.company",
                verbose_name="entreprises",
            ),
        ),
        migrations.AlterField(
            model_name="declarant",
            name="companies",
            field=models.ManyToManyField(
                related_name="declarants", to="data.company", verbose_name="entreprises"
            ),
        ),
    ]
