# Generated by Django 5.0.3 on 2024-04-11 10:08

import data.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0044_company_vat_alter_company_siret_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="siret",
            field=models.CharField(
                blank=True,
                help_text="14 chiffres",
                null=True,
                unique=True,
                validators=[data.validators.validate_siret],
                verbose_name="n° SIRET",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="vat",
            field=models.CharField(
                blank=True,
                null=True,
                unique=True,
                validators=[data.validators.validate_vat],
                verbose_name="n° TVA intracommunautaire",
            ),
        ),
    ]
