# Generated by Django 5.0.3 on 2024-04-09 10:07

import django.db.models.deletion
import django.db.models.functions.comparison
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0045_remove_historicaldeclaration_effects_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GalenicFormulation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("modification_date", models.DateTimeField(auto_now=True)),
                (
                    "missing_import_data",
                    models.BooleanField(
                        blank=True, default=False, editable=False, null=True
                    ),
                ),
                (
                    "siccrf_id",
                    models.IntegerField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        null=True,
                        unique=True,
                        verbose_name="id dans les tables et tables relationnelles SICCRF",
                    ),
                ),
                (
                    "siccrf_name",
                    models.TextField(editable=False, verbose_name="nom SICCRF"),
                ),
                ("ca_name", models.TextField(verbose_name="nom CA")),
                (
                    "name",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.functions.comparison.Coalesce(
                            django.db.models.functions.comparison.NullIf(
                                models.F("ca_name"), models.Value("")
                            ),
                            models.F("siccrf_name"),
                        ),
                        output_field=models.TextField(verbose_name="nom"),
                    ),
                ),
                (
                    "siccrf_is_obsolete",
                    models.BooleanField(
                        default=False,
                        editable=False,
                        verbose_name="objet obsolète selon SICCRF",
                    ),
                ),
                (
                    "ca_is_obsolete",
                    models.BooleanField(
                        default=None, null=True, verbose_name="objet obsolète selon CA"
                    ),
                ),
                (
                    "is_obsolete",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.functions.comparison.Coalesce(
                            models.F("ca_is_obsolete"), models.F("siccrf_is_obsolete")
                        ),
                        output_field=models.BooleanField(verbose_name="objet obsolète"),
                    ),
                ),
                (
                    "siccrf_name_en",
                    models.TextField(
                        blank=True, verbose_name="nom en anglais selon la base SICCRF"
                    ),
                ),
            ],
            options={
                "verbose_name": "Forme galénique",
                "verbose_name_plural": "Formes galéniques",
            },
        ),
        migrations.AlterField(
            model_name="condition",
            name="siccrf_name_en",
            field=models.TextField(
                blank=True, verbose_name="nom en anglais selon la base SICCRF"
            ),
        ),
        migrations.AlterField(
            model_name="effect",
            name="siccrf_name_en",
            field=models.TextField(
                blank=True, verbose_name="nom en anglais selon la base SICCRF"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcondition",
            name="siccrf_name_en",
            field=models.TextField(
                blank=True, verbose_name="nom en anglais selon la base SICCRF"
            ),
        ),
        migrations.AlterField(
            model_name="historicaleffect",
            name="siccrf_name_en",
            field=models.TextField(
                blank=True, verbose_name="nom en anglais selon la base SICCRF"
            ),
        ),
        migrations.CreateModel(
            name="HistoricalGalenicFormulation",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("creation_date", models.DateTimeField(blank=True, editable=False)),
                ("modification_date", models.DateTimeField(blank=True, editable=False)),
                (
                    "missing_import_data",
                    models.BooleanField(
                        blank=True, default=False, editable=False, null=True
                    ),
                ),
                (
                    "siccrf_id",
                    models.IntegerField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        null=True,
                        verbose_name="id dans les tables et tables relationnelles SICCRF",
                    ),
                ),
                (
                    "siccrf_name",
                    models.TextField(editable=False, verbose_name="nom SICCRF"),
                ),
                ("ca_name", models.TextField(verbose_name="nom CA")),
                (
                    "siccrf_is_obsolete",
                    models.BooleanField(
                        default=False,
                        editable=False,
                        verbose_name="objet obsolète selon SICCRF",
                    ),
                ),
                (
                    "ca_is_obsolete",
                    models.BooleanField(
                        default=None, null=True, verbose_name="objet obsolète selon CA"
                    ),
                ),
                (
                    "siccrf_name_en",
                    models.TextField(
                        blank=True, verbose_name="nom en anglais selon la base SICCRF"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Forme galénique",
                "verbose_name_plural": "historical Formes galéniques",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
