# Generated by Django 5.0.3 on 2024-04-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0045_remove_historicaldeclaration_effects_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="condition",
            name="siccrf_name_en",
            field=models.TextField(
                blank=True, verbose_name="nom en anglais selon la base SICCRF"
            ),
        ),
        migrations.AlterField(
            model_name="declaration",
            name="effects",
            field=models.ManyToManyField(
                blank=True, to="data.effect", verbose_name="objectifs ou effets"
            ),
        ),
        migrations.AlterField(
            model_name="effect",
            name="siccrf_name_en",
            field=models.TextField(
                blank=True, verbose_name="nom en anglais selon la base SICCRF"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcondition",
            name="siccrf_name_en",
            field=models.TextField(
                blank=True, verbose_name="nom en anglais selon la base SICCRF"
            ),
        ),
        migrations.AlterField(
            model_name="historicaleffect",
            name="siccrf_name_en",
            field=models.TextField(
                blank=True, verbose_name="nom en anglais selon la base SICCRF"
            ),
        ),
    ]
