# Generated by Django 5.0.3 on 2024-04-11 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0045_alter_company_siret_alter_company_vat"),
        ("data", "0046_alter_condition_siccrf_name_en_and_more"),
    ]

    operations = []
