# Generated by Django 5.0.3 on 2024-04-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0046_alter_condition_siccrf_name_en_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="declaredmicroorganism",
            name="new_name",
        ),
        migrations.RemoveField(
            model_name="historicaldeclaredmicroorganism",
            name="new_name",
        ),
        migrations.AddField(
            model_name="declaredmicroorganism",
            name="new_species",
            field=models.TextField(
                blank=True,
                verbose_name="espèce du micro-organisme ajoutée manuellement",
            ),
        ),
        migrations.AddField(
            model_name="historicaldeclaredmicroorganism",
            name="new_species",
            field=models.TextField(
                blank=True,
                verbose_name="espèce du micro-organisme ajoutée manuellement",
            ),
        ),
    ]
