# Generated by Django 5.0.3 on 2024-04-15 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0047_galenicformulation_historicalgalenicformulation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="galenicformulation",
            options={
                "verbose_name": "forme galénique",
                "verbose_name_plural": "formes galéniques",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalgalenicformulation",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical forme galénique",
                "verbose_name_plural": "historical formes galéniques",
            },
        ),
    ]
