# Generated by Django 5.0.4 on 2024-04-15 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0047_merge_20240411_1459"),
        ("data", "0048_alter_galenicformulation_options_and_more"),
    ]

    operations = []
