# Generated by Django 5.0.3 on 2024-04-15 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0048_declaredingredient_authorization_mode_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="declaredingredient",
            name="eu_details",
            field=models.TextField(
                blank=True,
                verbose_name="information additionnelle sur l'autorisation dans un autre pays européen",
            ),
        ),
        migrations.AlterField(
            model_name="declaredmicroorganism",
            name="eu_details",
            field=models.TextField(
                blank=True,
                verbose_name="information additionnelle sur l'autorisation dans un autre pays européen",
            ),
        ),
        migrations.AlterField(
            model_name="declaredmicroorganism",
            name="new_species",
            field=models.TextField(
                blank=True, verbose_name="espèce du micro-organisme ajouté manuellement"
            ),
        ),
        migrations.AlterField(
            model_name="declaredplant",
            name="eu_details",
            field=models.TextField(
                blank=True,
                verbose_name="information additionnelle sur l'autorisation dans un autre pays européen",
            ),
        ),
        migrations.AlterField(
            model_name="declaredplant",
            name="plant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="data.plant",
                verbose_name="plante ajoutée par l'utilisateur",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldeclaredingredient",
            name="eu_details",
            field=models.TextField(
                blank=True,
                verbose_name="information additionnelle sur l'autorisation dans un autre pays européen",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldeclaredmicroorganism",
            name="eu_details",
            field=models.TextField(
                blank=True,
                verbose_name="information additionnelle sur l'autorisation dans un autre pays européen",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldeclaredmicroorganism",
            name="new_species",
            field=models.TextField(
                blank=True, verbose_name="espèce du micro-organisme ajouté manuellement"
            ),
        ),
        migrations.AlterField(
            model_name="historicaldeclaredplant",
            name="eu_details",
            field=models.TextField(
                blank=True,
                verbose_name="information additionnelle sur l'autorisation dans un autre pays européen",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldeclaredplant",
            name="plant",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="data.plant",
                verbose_name="plante ajoutée par l'utilisateur",
            ),
        ),
    ]
