# Generated by Django 5.0.3 on 2024-04-15 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0048_alter_galenicformulation_options_and_more"),
        ("data", "0049_alter_declaredingredient_eu_details_and_more"),
    ]

    operations = []
