# Generated by Django 5.0.3 on 2024-04-15 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0050_merge_20240415_1214"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="declaration",
            name="galenic_formulation",
        ),
        migrations.RemoveField(
            model_name="historicaldeclaration",
            name="galenic_formulation",
        ),
        migrations.AddField(
            model_name="declaration",
            name="galenic_formulation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="data.galenicformulation",
                verbose_name="forme galénique",
            ),
        ),
        migrations.AddField(
            model_name="historicaldeclaration",
            name="galenic_formulation",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="data.galenicformulation",
                verbose_name="forme galénique",
            ),
        ),
    ]
