# Generated by Django 5.0.3 on 2024-04-15 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0049_merge_20240415_1245"),
        ("data", "0052_alter_declaredingredient_eu_reference_country_and_more"),
    ]

    operations = []
