# Generated by Django 5.0.4 on 2024-04-16 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0053_merge_20240415_1856"),
    ]

    operations = [
        migrations.CreateModel(
            name="IngredientStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "missing_import_data",
                    models.BooleanField(
                        blank=True, default=False, editable=False, null=True
                    ),
                ),
                (
                    "siccrf_id",
                    models.IntegerField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        null=True,
                        unique=True,
                        verbose_name="id dans les tables et tables relationnelles SICCRF",
                    ),
                ),
                ("name", models.TextField(verbose_name="statut")),
            ],
            options={
                "verbose_name": "statut de l'élément selon le décret 2006-352 du 20 mars 2006 relatif aux compléments alimentaires.",
            },
        ),
        migrations.AddField(
            model_name="ingredient",
            name="status",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_siccrf_status",
                to="data.ingredientstatus",
                verbose_name="statut de l'ingrédient ou substance",
            ),
        ),
        migrations.AddField(
            model_name="microorganism",
            name="status",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_siccrf_status",
                to="data.ingredientstatus",
                verbose_name="statut de l'ingrédient ou substance",
            ),
        ),
        migrations.AddField(
            model_name="plant",
            name="status",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_siccrf_status",
                to="data.ingredientstatus",
                verbose_name="statut de l'ingrédient ou substance",
            ),
        ),
        migrations.AddField(
            model_name="substance",
            name="status",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_siccrf_status",
                to="data.ingredientstatus",
                verbose_name="statut de l'ingrédient ou substance",
            ),
        ),
    ]
