# Generated by Django 5.0.4 on 2024-04-18 12:58

import django.db.models.deletion
import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0054_alter_declaration_status_and_more"),
    ]

    operations = [
        migrations.RenameField(model_name="plant", old_name="family", new_name="family_by_id"),
        migrations.AddField(
            model_name="plant",
            name="family",
            field=models.ForeignObject(
                from_fields=("family_by_id",),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="plant_set",
                to="data.plantfamily",
                to_fields=("id",),
            ),
        ),
    ]
