# Generated by Django 5.0.4 on 2024-04-16 14:49

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0054_company_activities"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="email",
            field=models.EmailField(
                default="test@example.com", max_length=254, verbose_name="adresse e-mail de contact"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="company",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default="33123232323",
                max_length=128,
                region=None,
                verbose_name="numéro de téléphone de contact",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="company",
            name="website",
            field=models.URLField(blank=True, verbose_name="site web de l'entreprise"),
        ),
    ]
