# Generated by Django 5.0.4 on 2024-04-16 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0055_company_email_company_phone_number_company_website"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="website",
            field=models.CharField(blank=True, verbose_name="site web de l'entreprise"),
        ),
    ]
