# Generated by Django 5.0.4 on 2024-04-22 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0055_alter_ingredient_status_alter_substance_status_and_more"),
        ("data", "0055_plant_family_by_id_alter_plant_family"),
    ]

    operations = []
