# Generated by Django 5.0.4 on 2024-04-18 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0054_alter_declaration_status_and_more"),
        ("data", "0056_alter_company_website"),
    ]

    operations = []
