# Generated by Django 5.0.4 on 2024-04-22 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0055_plant_family_by_id_alter_plant_family"),
        ("data", "0057_merge_20240418_1731"),
    ]

    operations = []
