# Generated by Django 5.0.4 on 2024-04-22 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0056_merge_20240422_1112"),
        ("data", "0057_alter_substance_max_quantity"),
    ]

    operations = []
