# Generated by Django 5.0.4 on 2024-04-23 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0058_merge_20240422_1243'),
        ('data', '0058_merge_20240422_1553'),
    ]

    operations = [
    ]
