# Generated by Django 5.0.4 on 2024-04-22 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0058_merge_20240422_1553"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="name",
            field=models.TextField(blank=True, verbose_name="nom du fichier"),
        ),
        migrations.AddField(
            model_name="historicalattachment",
            name="name",
            field=models.TextField(blank=True, verbose_name="nom du fichier"),
        ),
    ]
