# Generated by Django 5.0.4 on 2024-04-27 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0059_merge_20240423_1609'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompanySupervisor',
            new_name='Supervisor',
        ),
        migrations.AlterModelOptions(
            name='supervisor',
            options={'verbose_name': 'gestionnaire'},
        ),
    ]
