# Generated by Django 5.0.4 on 2024-04-30 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0059_attachment_name_historicalattachment_name"),
        ("data", "0059_merge_20240423_1609"),
    ]

    operations = []
