# Generated by Django 5.0.4 on 2024-04-30 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0060_rename_companysupervisor_supervisor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisor',
            name='companies',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='user',
        ),
        migrations.CreateModel(
            name='DeclarantRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declarant_roles', to='data.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declarant_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'rôle déclarant',
                'verbose_name_plural': 'rôles déclarant',
                'unique_together': {('company', 'user')},
            },
        ),
        migrations.AddField(
            model_name='company',
            name='declarants',
            field=models.ManyToManyField(blank=True, related_name='declarable_companies', through='data.DeclarantRole', to=settings.AUTH_USER_MODEL, verbose_name='déclarants'),
        ),
        migrations.CreateModel(
            name='SupervisorRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_roles', to='data.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'rôle gestionnaire',
                'verbose_name_plural': 'rôles gestionnaire',
                'unique_together': {('company', 'user')},
            },
        ),
        migrations.AddField(
            model_name='company',
            name='supervisors',
            field=models.ManyToManyField(blank=True, related_name='supervisable_companies', through='data.SupervisorRole', to=settings.AUTH_USER_MODEL, verbose_name='gestionnaires'),
        ),
        migrations.DeleteModel(
            name='Declarant',
        ),
        migrations.DeleteModel(
            name='Supervisor',
        ),
    ]
