# Generated by Django 5.0.4 on 2024-05-01 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0060_merge_20240430_1603'),
        ('data', '0061_remove_supervisor_companies_remove_supervisor_user_and_more'),
    ]

    operations = [
    ]
