# Generated by Django 5.0.4 on 2024-05-02 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0062_merge_20240501_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('RequestSupervisionSolicitation', 'demande de gestion'), ('RequestCoSupervisionSolicitation', 'demande de co-gestion'), ('InviteCoSupervision', 'invitation à une co-gestion')], verbose_name='type')),
                ('description', models.TextField()),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='traité à')),
                ('processed_action', models.CharField(blank=True, verbose_name='action de traitement')),
                ('processor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitations_processed', to=settings.AUTH_USER_MODEL, verbose_name='traité par')),
                ('recipients', models.ManyToManyField(related_name='solicitations_received', to=settings.AUTH_USER_MODEL, verbose_name='destinataires')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitations_sent', to=settings.AUTH_USER_MODEL, verbose_name='émetteur')),
            ],
            options={
                'verbose_name': 'solicitation',
                'ordering': ('-creation_date',),
            },
        ),
    ]
