# Generated by Django 5.0.4 on 2024-05-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0062_merge_20240501_1427"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalingredient",
            name="ingredient_type",
            field=models.IntegerField(
                choices=[
                    (1, "Nutriment (Forme d'apport)"),
                    (2, "Additif"),
                    (3, "Arôme"),
                    (4, "Autre ingrédient actif"),
                    (5, "Autre ingrédient"),
                ],
                null=True,
                verbose_name="type de l'ingrédient",
            ),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="ingredient_type",
            field=models.IntegerField(
                choices=[
                    (1, "Nutriment (Forme d'apport)"),
                    (2, "Additif"),
                    (3, "Arôme"),
                    (4, "Autre ingrédient actif"),
                    (5, "Autre ingrédient"),
                ],
                null=True,
                verbose_name="type de l'ingrédient",
            ),
        ),
    ]
