# Generated by Django 5.0.4 on 2024-05-09 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0063_instructionrole"),
    ]

    operations = []
