# Generated by Django 5.0.4 on 2024-05-03 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0063_solicitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitation',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.company'),
        ),
        migrations.AlterField(
            model_name='solicitation',
            name='kind',
            field=models.CharField(choices=[('RequestSupervision', 'demande de gestion'), ('RequestCoSupervision', 'demande de co-gestion'), ('InviteCoSupervision', 'invitation à une co-gestion')], verbose_name='type'),
        ),
    ]
