# Generated by Django 5.0.4 on 2024-05-22 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0063_collaborationinvitation_cosupervisionclaim_and_more'),
        ('data', '0063_instructionrole'),
    ]

    operations = [
    ]
