# Generated by Django 5.0.4 on 2024-05-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0064_solicitation_company_alter_solicitation_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitation',
            name='kind',
            field=models.CharField(choices=[('ClaimSupervision', 'demande de gestion'), ('ClaimCoSupervision', 'demande de co-gestion'), ('InviteCoSupervision', 'invitation à une co-gestion')], verbose_name='type'),
        ),
    ]
