# Generated by Django 5.0.4 on 2024-05-08 12:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0065_alter_solicitation_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitation',
            name='role_classnames',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='solicitation',
            name='kind',
            field=models.CharField(choices=[('ClaimSupervision', 'demande de gestion'), ('ClaimCoSupervision', 'demande de co-gestion'), ('InviteCreateCollaboratorAccount', 'invitation à créer son compte')], verbose_name='type'),
        ),
    ]
