# Generated by Django 5.0.6 on 2024-05-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0065_historicalingredient_to_be_entered_in_next_decree_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="status",
            field=models.IntegerField(
                choices=[(1, "autorisé"), (2, "non autorisé")],
                default=2,
                null=True,
                verbose_name="statut de l'ingrédient ou substance",
            ),
        ),
        migrations.AlterField(
            model_name="microorganism",
            name="status",
            field=models.IntegerField(
                choices=[(1, "autorisé"), (2, "non autorisé")],
                default=2,
                null=True,
                verbose_name="statut de l'ingrédient ou substance",
            ),
        ),
        migrations.AlterField(
            model_name="plant",
            name="status",
            field=models.IntegerField(
                choices=[(1, "autorisé"), (2, "non autorisé")],
                default=2,
                null=True,
                verbose_name="statut de l'ingrédient ou substance",
            ),
        ),
        migrations.AlterField(
            model_name="substance",
            name="status",
            field=models.IntegerField(
                choices=[(1, "autorisé"), (2, "non autorisé")],
                default=2,
                null=True,
                verbose_name="statut de l'ingrédient ou substance",
            ),
        ),
    ]
