# Generated by Django 5.0.6 on 2024-05-23 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0064_merge_20240522_1045"),
        ("data", "0066_alter_ingredient_status_alter_microorganism_status_and_more"),
    ]

    operations = []
