# Generated by Django 5.0.4 on 2024-05-08 17:12

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0066_solicitation_role_classnames_alter_solicitation_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollaborationInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('personal_msg', models.TextField(blank=True, null=True, verbose_name="message personnel de l'émetteur (optionnel)")),
                ('description', models.TextField()),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='traité à')),
                ('processed_action', models.CharField(blank=True, verbose_name='action de traitement')),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='adresse e-mail du destinataire')),
                ('roles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), size=None)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.company')),
                ('processor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_processed', to=settings.AUTH_USER_MODEL, verbose_name='traité par')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_sent', to=settings.AUTH_USER_MODEL, verbose_name='émetteur')),
            ],
            options={
                'verbose_name': 'invitation à devenir collaborateur',
                'verbose_name_plural': 'invitations à devenir collaborateur',
                'unique_together': {('company', 'recipient_email')},
            },
        ),
        migrations.CreateModel(
            name='CoSupervisionClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('personal_msg', models.TextField(blank=True, null=True, verbose_name="message personnel de l'émetteur (optionnel)")),
                ('description', models.TextField()),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='traité à')),
                ('processed_action', models.CharField(blank=True, verbose_name='action de traitement')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.company')),
                ('processor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_processed', to=settings.AUTH_USER_MODEL, verbose_name='traité par')),
                ('recipients', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='destinataires')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_sent', to=settings.AUTH_USER_MODEL, verbose_name='émetteur')),
            ],
            options={
                'verbose_name': 'demande de co-gestion',
                'verbose_name_plural': 'demandes de co-gestion',
            },
        ),
        migrations.CreateModel(
            name='SupervisionClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('personal_msg', models.TextField(blank=True, null=True, verbose_name="message personnel de l'émetteur (optionnel)")),
                ('description', models.TextField()),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='traité à')),
                ('processed_action', models.CharField(blank=True, verbose_name='action de traitement')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.company')),
                ('processor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_processed', to=settings.AUTH_USER_MODEL, verbose_name='traité par')),
                ('recipients', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='destinataires')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_sent', to=settings.AUTH_USER_MODEL, verbose_name='émetteur')),
            ],
            options={
                'verbose_name': 'demande de gestion',
                'verbose_name_plural': 'demandes de gestion',
            },
        ),
        migrations.DeleteModel(
            name='Solicitation',
        ),
    ]
