# Generated by Django 5.0.6 on 2024-05-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0067_merge_20240523_1039"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="status",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "autorisé"), (2, "non autorisé")],
                default=None,
                null=True,
                verbose_name="statut de l'ingrédient ou substance",
            ),
        ),
        migrations.AlterField(
            model_name="microorganism",
            name="status",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "autorisé"), (2, "non autorisé")],
                default=None,
                null=True,
                verbose_name="statut de l'ingrédient ou substance",
            ),
        ),
        migrations.AlterField(
            model_name="plant",
            name="status",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "autorisé"), (2, "non autorisé")],
                default=None,
                null=True,
                verbose_name="statut de l'ingrédient ou substance",
            ),
        ),
        migrations.AlterField(
            model_name="substance",
            name="status",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "autorisé"), (2, "non autorisé")],
                default=None,
                null=True,
                verbose_name="statut de l'ingrédient ou substance",
            ),
        ),
    ]
