# Generated by Django 5.0.4 on 2024-05-08 17:19

import data.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0067_collaborationinvitation_cosupervisionclaim_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborationinvitation',
            name='roles',
            field=data.fields.MultipleChoiceField(base_field=models.CharField(choices=[('DeclarantRole', 'Declarantrole'), ('SupervisorRole', 'Supervisorrole')]), default=list, size=None, verbose_name='classes de rôle'),
        ),
    ]
