# Generated by Django 5.0.4 on 2024-05-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0068_alter_collaborationinvitation_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborationinvitation',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='collaborationinvitation',
            name='personal_msg',
            field=models.TextField(blank=True, default='osef', verbose_name="message personnel de l'émetteur (optionnel)"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cosupervisionclaim',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cosupervisionclaim',
            name='personal_msg',
            field=models.TextField(blank=True, default='osef', verbose_name="message personnel de l'émetteur (optionnel)"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supervisionclaim',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='supervisionclaim',
            name='personal_msg',
            field=models.TextField(blank=True, default='osef', verbose_name="message personnel de l'émetteur (optionnel)"),
            preserve_default=False,
        ),
    ]
