# Generated by Django 5.0.4 on 2024-05-08 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0069_alter_collaborationinvitation_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborationinvitation',
            name='description',
        ),
        migrations.RemoveField(
            model_name='cosupervisionclaim',
            name='description',
        ),
        migrations.RemoveField(
            model_name='supervisionclaim',
            name='description',
        ),
    ]
