# Generated by Django 5.0.4 on 2024-05-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0070_remove_collaborationinvitation_description_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collaborationinvitation',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='collaborationinvitation',
            constraint=models.UniqueConstraint(condition=models.Q(('processed_at__isnull', True)), fields=('company', 'recipient_email'), name='unique_collaboration_invitation'),
        ),
    ]
