# Generated by Django 5.0.4 on 2024-06-17 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0069_declaration_instructor_declaration_private_notes_and_more"),
        ("data", "0070_alter_historicalingredient_ca_status_and_more"),
    ]

    operations = []
