# Generated by Django 5.0.4 on 2024-05-09 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0071_alter_collaborationinvitation_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborationinvitation',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.company', verbose_name='entreprise'),
        ),
        migrations.AlterField(
            model_name='cosupervisionclaim',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.company', verbose_name='entreprise'),
        ),
        migrations.AlterField(
            model_name='supervisionclaim',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.company', verbose_name='entreprise'),
        ),
    ]
