# Generated by Django 5.0.6 on 2024-06-24 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0063_historicalingredient_ingredient_type_and_more"),
        ("data", "0071_merge_20240617_0945"),
    ]

    operations = []
