# Generated by Django 5.0.6 on 2024-06-25 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0072_declaration_post_validation_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="declaration",
            name="post_validation_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DRAFT", "Brouillon"),
                    ("AWAITING_INSTRUCTION", "En attente d'instruction"),
                    ("ONGOING_INSTRUCTION", "Instruction en cours"),
                    ("AWAITING_VISA", "En attente de visa"),
                    ("ONGOING_VISA", "Visa en cours"),
                    ("OBJECTION", "En objection"),
                    ("OBSERVATION", "En observation"),
                    ("ABANDONED", "Abandonnée"),
                    ("AUTHORIZED", "Autorisée"),
                    ("REJECTED", "Refusée"),
                ],
                default="DRAFT",
                max_length=50,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldeclaration",
            name="post_validation_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DRAFT", "Brouillon"),
                    ("AWAITING_INSTRUCTION", "En attente d'instruction"),
                    ("ONGOING_INSTRUCTION", "Instruction en cours"),
                    ("AWAITING_VISA", "En attente de visa"),
                    ("ONGOING_VISA", "Visa en cours"),
                    ("OBJECTION", "En objection"),
                    ("OBSERVATION", "En observation"),
                    ("ABANDONED", "Abandonnée"),
                    ("AUTHORIZED", "Autorisée"),
                    ("REJECTED", "Refusée"),
                ],
                default="DRAFT",
                max_length=50,
                verbose_name="status",
            ),
        ),
    ]
