# Generated by Django 5.0.6 on 2024-06-28 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0072_merge_20240624_1651"),
        ("data", "0074_declaration_post_validation_expiration_days_and_more"),
    ]

    operations = []
