# Generated by Django 5.0.6 on 2024-07-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0075_merge_20240628_1510"),
    ]

    operations = [
        migrations.AddField(
            model_name="snapshot",
            name="action",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SUBMIT", "soumettre pour instruction"),
                    ("TAKE_FOR_INSTRUCTION", "prendre pour instruction"),
                    ("OBSERVE_NO_VISA", "mettre en observation sans visa"),
                    ("AUTHORIZE_NO_VISA", "autoriser sans visa"),
                    ("RESPOND_TO_OBSERVATION", "répondre à une observation"),
                    ("RESPOND_TO_OBJECTION", "répondre à une objection"),
                    ("REQUEST_VISA", "demander un visa"),
                    ("TAKE_FOR_VISA", "prendre pour visa"),
                    ("APPROVE_VISA", "valider le visa"),
                    ("REFUSE_VISA", "refuser le visa"),
                    ("RETIRE", "retirer du marché"),
                    ("ABANDON", "mettre en abandon"),
                    ("OTHER", "autre"),
                ],
                default="OTHER",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="snapshot",
            name="post_validation_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DRAFT", "Brouillon"),
                    ("AWAITING_INSTRUCTION", "En attente d'instruction"),
                    ("ONGOING_INSTRUCTION", "Instruction en cours"),
                    ("AWAITING_VISA", "En attente de visa"),
                    ("ONGOING_VISA", "Visa en cours"),
                    ("OBJECTION", "En objection"),
                    ("OBSERVATION", "En observation"),
                    ("ABANDONED", "Abandonnée"),
                    ("AUTHORIZED", "Autorisée"),
                    ("REJECTED", "Refusée"),
                ],
                default="DRAFT",
                max_length=50,
                verbose_name="status à assigner après la validation",
            ),
        ),
    ]
