# Generated by Django 5.0.7 on 2024-07-29 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0078_alter_declaration_conditioning_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="declaredingredient",
            name="quantity",
            field=models.FloatField(
                blank=True, null=True, verbose_name="quantité par DJR"
            ),
        ),
        migrations.AddField(
            model_name="declaredingredient",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="data.substanceunit",
                verbose_name="unité",
            ),
        ),
        migrations.AddField(
            model_name="historicaldeclaredingredient",
            name="quantity",
            field=models.FloatField(
                blank=True, null=True, verbose_name="quantité par DJR"
            ),
        ),
        migrations.AddField(
            model_name="historicaldeclaredingredient",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="data.substanceunit",
                verbose_name="unité",
            ),
        ),
    ]
