# Generated by Django 5.0.7 on 2024-07-29 14:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0078_alter_declaration_conditioning_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="snapshot",
            name="blocking_reasons",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                null=True,
                size=None,
                verbose_name="raisons de la dernière décision défavorable",
            ),
        ),
    ]
