# Generated by Django 5.0.7 on 2024-07-31 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0079_rename_souche_declaredmicroorganism_strain_and_more"),
        ("data", "0080_alter_declaration_conditioning_and_more"),
    ]

    operations = []
