# Generated by Django 5.0.7 on 2024-08-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0081_merge_20240731_1702"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="declaredmicroorganism",
            name="inactivated",
        ),
        migrations.RemoveField(
            model_name="historicaldeclaredmicroorganism",
            name="inactivated",
        ),
        migrations.AddField(
            model_name="declaredmicroorganism",
            name="activated",
            field=models.BooleanField(
                default=True,
                verbose_name="n'ayant pas été inactivé (rendu incapable de réplication)",
            ),
        ),
        migrations.AddField(
            model_name="historicaldeclaredmicroorganism",
            name="activated",
            field=models.BooleanField(
                default=True,
                verbose_name="n'ayant pas été inactivé (rendu incapable de réplication)",
            ),
        ),
    ]
