# Generated by Django 5.0.7 on 2024-08-02 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0081_declaredingredient_new_type_and_more"),
        ("data", "0082_remove_declaredmicroorganism_inactivated_and_more"),
    ]

    operations = []
