# Generated by Django 5.1 on 2024-08-13 09:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0083_merge_20240802_1017"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CoSupervisionClaim",
            new_name="CompanyAccessClaim",
        ),
        migrations.AlterModelOptions(
            name="companyaccessclaim",
            options={
                "verbose_name": "demande d'accès à une entreprise",
                "verbose_name_plural": "demandes d'accès à une entreprise",
            },
        ),
    ]
