# Generated by Django 5.1 on 2024-08-21 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0085_companyaccessclaim_declarant_role_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="effect",
            options={
                "verbose_name": "Objectif et effet des compléments alimentaires",
                "verbose_name_plural": "Objectifs et effets des compléments alimentaires",
            },
        ),
        migrations.AlterModelOptions(
            name="historicaleffect",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Objectif et effet des compléments alimentaires",
                "verbose_name_plural": "historical Objectifs et effets des compléments alimentaires",
            },
        ),
    ]
