# Generated by Django 5.1 on 2024-08-27 08:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0086_preparation_historicalpreparation"),
        ("data", "0087_declaration_other_conditions_and_more"),
    ]

    operations = []
