# Generated by Django 5.1 on 2024-08-28 10:41

import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0088_merge_20240827_1020"),
    ]

    operations = [
        migrations.AddField(
            model_name="declaration",
            name="calculated_article",
            field=models.TextField(
                blank=True,
                choices=[
                    ("15", "Article 15"),
                    ("15_WARNING", "Article 15 Vigilance"),
                    ("16", "Article 16"),
                ],
                verbose_name="article calculé automatiquement",
            ),
        ),
        migrations.AddField(
            model_name="declaration",
            name="overriden_article",
            field=models.TextField(
                blank=True,
                choices=[
                    ("15", "Article 15"),
                    ("15_WARNING", "Article 15 Vigilance"),
                    ("16", "Article 16"),
                ],
                verbose_name="article manuellement spécifié",
            ),
        ),
        migrations.AddField(
            model_name="historicaldeclaration",
            name="calculated_article",
            field=models.TextField(
                blank=True,
                choices=[
                    ("15", "Article 15"),
                    ("15_WARNING", "Article 15 Vigilance"),
                    ("16", "Article 16"),
                ],
                verbose_name="article calculé automatiquement",
            ),
        ),
        migrations.AddField(
            model_name="historicaldeclaration",
            name="overriden_article",
            field=models.TextField(
                blank=True,
                choices=[
                    ("15", "Article 15"),
                    ("15_WARNING", "Article 15 Vigilance"),
                    ("16", "Article 16"),
                ],
                verbose_name="article manuellement spécifié",
            ),
        ),
        migrations.AddField(
            model_name="declaration",
            name="article",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.functions.comparison.Coalesce(
                    models.Case(
                        models.When(overriden_article="", then=models.Value(None)),
                        default="overriden_article",
                    ),
                    models.Case(
                        models.When(calculated_article="", then=models.Value(None)),
                        default="calculated_article",
                    ),
                    models.Value(None),
                ),
                output_field=models.TextField(verbose_name="article"),
            ),
        ),
        migrations.AddField(
            model_name="historicaldeclaration",
            name="article",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.functions.comparison.Coalesce(
                    models.Case(
                        models.When(overriden_article="", then=models.Value(None)),
                        default="overriden_article",
                    ),
                    models.Case(
                        models.When(calculated_article="", then=models.Value(None)),
                        default="calculated_article",
                    ),
                    models.Value(None),
                ),
                output_field=models.TextField(verbose_name="article"),
            ),
        ),
    ]
