# Generated by Django 5.1 on 2024-09-05 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0090_alter_declaration_article_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="declaredplant",
            old_name="preparation",
            new_name="preparation_old",
        ),
        migrations.RenameField(
            model_name="historicaldeclaredplant",
            old_name="preparation",
            new_name="preparation_old",
        ),
        migrations.AddField(
            model_name="declaredplant",
            name="preparation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="data.preparation",
                verbose_name="préparation",
            ),
        ),
        migrations.AddField(
            model_name="historicaldeclaredplant",
            name="preparation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="data.preparation",
                verbose_name="préparation",
            ),
        ),
        
    ]
