# Generated by Django 5.1 on 2024-09-05 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0092_populate_new_preparation_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="declaredplant",
            name="preparation_old",
        ),
        migrations.RemoveField(
            model_name="historicaldeclaredplant",
            name="preparation_old",
        ),
        migrations.AlterField(
            model_name="historicaldeclaredplant",
            name="preparation",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="data.preparation",
                verbose_name="préparation",
            ),
        ),
    ]
