# Generated by Django 5.1 on 2024-09-07 13:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0091_alter_declaredingredient_options_and_more"),
        ("data", "0093_remove_declaredplant_preparation_old_and_more"),
    ]

    operations = []
