# Generated by Django 5.1.1 on 2024-09-11 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0094_declaredsubstance_authorization_mode_and_more"),
        ("data", "0094_merge_20240907_1514"),
    ]

    operations = []
