# Generated by Django 5.1.1 on 2024-09-11 09:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0094_merge_20240907_1514"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsubstance",
            name="substance_types",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(
                    choices=[
                        (1, "Vitamine"),
                        (2, "Minéral"),
                        (3, "Métabolite secondaire de plante"),
                        (4, "Glucide"),
                        (5, "Enzyme"),
                    ],
                    null=True,
                ),
                null=True,
                size=None,
                verbose_name="type(s) de la substance",
            ),
        ),
        migrations.AddField(
            model_name="substance",
            name="substance_types",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(
                    choices=[
                        (1, "Vitamine"),
                        (2, "Minéral"),
                        (3, "Métabolite secondaire de plante"),
                        (4, "Glucide"),
                        (5, "Enzyme"),
                    ],
                    null=True,
                ),
                null=True,
                size=None,
                verbose_name="type(s) de la substance",
            ),
        ),
    ]
