# Generated by Django 5.1.1 on 2024-09-23 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0095_declaredsubstance_authorization_mode_and_more"),
        ("data", "0095_historicalsubstance_substance_types_and_more"),
    ]

    operations = []
