# Generated by Django 5.1.1 on 2024-09-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0095_historicalsubstance_substance_types_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalsubstance",
            name="substance_types",
        ),
        migrations.AddField(
            model_name="declaredsubstance",
            name="authorization_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FR", "Utilisable en France"),
                    ("EU", "Autorisé dans un État membre de l'UE ou EEE"),
                ],
                verbose_name="modalité d'autorisation pour un élément ajouté manuellement",
            ),
        ),
        migrations.AddField(
            model_name="declaredsubstance",
            name="eu_details",
            field=models.TextField(
                blank=True,
                verbose_name="information additionnelle sur l'autorisation dans un autre pays européen",
            ),
        ),
        migrations.AddField(
            model_name="declaredsubstance",
            name="eu_legal_source",
            field=models.TextField(
                blank=True,
                verbose_name="référence du texte réglementaire d'un autre pays européen",
            ),
        ),
        migrations.AddField(
            model_name="declaredsubstance",
            name="eu_reference_country",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FR", "France"),
                    ("DE", "Allemagne"),
                    ("AT", "Autriche"),
                    ("BE", "Belgique"),
                    ("BG", "Bulgarie"),
                    ("CY", "Chypre"),
                    ("HR", "Croatie"),
                    ("DK", "Danemark"),
                    ("ES", "Espagne"),
                    ("EE", "Estonie"),
                    ("FI", "Finlande"),
                    ("GR", "Grèce"),
                    ("HU", "Hongrie"),
                    ("IE", "Irlande"),
                    ("NI", "Irlande du Nord"),
                    ("IS", "Islande"),
                    ("IT", "Italie"),
                    ("LV", "Lettonie"),
                    ("LI", "Liechtenstein"),
                    ("LT", "Lituanie"),
                    ("LU", "Luxembourg"),
                    ("MT", "Malte"),
                    ("NO", "Norvège"),
                    ("NL", "Pays-Bas"),
                    ("PL", "Pologne"),
                    ("PT", "Portugal"),
                    ("RO", "Roumanie"),
                    ("SK", "Slovaquie"),
                    ("SI", "Slovénie"),
                    ("SE", "Suède"),
                    ("CZ", "République Tchèque"),
                ],
                default="FR",
                verbose_name="pays de source réglementaire",
            ),
        ),
        migrations.AddField(
            model_name="declaredsubstance",
            name="first_ocurrence",
            field=models.BooleanField(
                default=False,
                verbose_name="Est-ce que cet ingrédient a été rajouté en base suite à cette déclaration ?",
            ),
        ),
        migrations.AddField(
            model_name="declaredsubstance",
            name="fr_details",
            field=models.CharField(
                blank=True,
                verbose_name="information additionnelle sur l'autorisation en France",
            ),
        ),
        migrations.AddField(
            model_name="declaredsubstance",
            name="fr_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "TRADITIONAL_USAGE",
                        "Ingrédient bénéficiant d'un historique de consommation selon le catalogue Novel Food ou dont l'utilisation en alimentation humaine est bien établie (directive 2004/24/CE)",
                    ),
                    (
                        "NOVEL_FOOD",
                        "L'ingrédient figure sur la liste de l'Union des nouveaux aliments conformément au règlement (UE) 2017/2470",
                    ),
                    (
                        "MISSING",
                        "L'ingrédient est autorisé en France mais ne figure pas dans la base de données",
                    ),
                ],
                verbose_name="raison de l'ajout manuel",
            ),
        ),
        migrations.AddField(
            model_name="declaredsubstance",
            name="new",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="declaredsubstance",
            name="new_description",
            field=models.TextField(blank=True, verbose_name="description"),
        ),
        migrations.AddField(
            model_name="declaredsubstance",
            name="new_name",
            field=models.TextField(blank=True, verbose_name="libellé"),
        ),
        migrations.AddField(
            model_name="historicaldeclaredsubstance",
            name="authorization_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FR", "Utilisable en France"),
                    ("EU", "Autorisé dans un État membre de l'UE ou EEE"),
                ],
                verbose_name="modalité d'autorisation pour un élément ajouté manuellement",
            ),
        ),
        migrations.AddField(
            model_name="historicaldeclaredsubstance",
            name="eu_details",
            field=models.TextField(
                blank=True,
                verbose_name="information additionnelle sur l'autorisation dans un autre pays européen",
            ),
        ),
        migrations.AddField(
            model_name="historicaldeclaredsubstance",
            name="eu_legal_source",
            field=models.TextField(
                blank=True,
                verbose_name="référence du texte réglementaire d'un autre pays européen",
            ),
        ),
        migrations.AddField(
            model_name="historicaldeclaredsubstance",
            name="eu_reference_country",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FR", "France"),
                    ("DE", "Allemagne"),
                    ("AT", "Autriche"),
                    ("BE", "Belgique"),
                    ("BG", "Bulgarie"),
                    ("CY", "Chypre"),
                    ("HR", "Croatie"),
                    ("DK", "Danemark"),
                    ("ES", "Espagne"),
                    ("EE", "Estonie"),
                    ("FI", "Finlande"),
                    ("GR", "Grèce"),
                    ("HU", "Hongrie"),
                    ("IE", "Irlande"),
                    ("NI", "Irlande du Nord"),
                    ("IS", "Islande"),
                    ("IT", "Italie"),
                    ("LV", "Lettonie"),
                    ("LI", "Liechtenstein"),
                    ("LT", "Lituanie"),
                    ("LU", "Luxembourg"),
                    ("MT", "Malte"),
                    ("NO", "Norvège"),
                    ("NL", "Pays-Bas"),
                    ("PL", "Pologne"),
                    ("PT", "Portugal"),
                    ("RO", "Roumanie"),
                    ("SK", "Slovaquie"),
                    ("SI", "Slovénie"),
                    ("SE", "Suède"),
                    ("CZ", "République Tchèque"),
                ],
                default="FR",
                verbose_name="pays de source réglementaire",
            ),
        ),
        migrations.AddField(
            model_name="historicaldeclaredsubstance",
            name="first_ocurrence",
            field=models.BooleanField(
                default=False,
                verbose_name="Est-ce que cet ingrédient a été rajouté en base suite à cette déclaration ?",
            ),
        ),
        migrations.AddField(
            model_name="historicaldeclaredsubstance",
            name="fr_details",
            field=models.CharField(
                blank=True,
                verbose_name="information additionnelle sur l'autorisation en France",
            ),
        ),
        migrations.AddField(
            model_name="historicaldeclaredsubstance",
            name="fr_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "TRADITIONAL_USAGE",
                        "Ingrédient bénéficiant d'un historique de consommation selon le catalogue Novel Food ou dont l'utilisation en alimentation humaine est bien établie (directive 2004/24/CE)",
                    ),
                    (
                        "NOVEL_FOOD",
                        "L'ingrédient figure sur la liste de l'Union des nouveaux aliments conformément au règlement (UE) 2017/2470",
                    ),
                    (
                        "MISSING",
                        "L'ingrédient est autorisé en France mais ne figure pas dans la base de données",
                    ),
                ],
                verbose_name="raison de l'ajout manuel",
            ),
        ),
        migrations.AddField(
            model_name="historicaldeclaredsubstance",
            name="new",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicaldeclaredsubstance",
            name="new_description",
            field=models.TextField(blank=True, verbose_name="description"),
        ),
        migrations.AddField(
            model_name="historicaldeclaredsubstance",
            name="new_name",
            field=models.TextField(blank=True, verbose_name="libellé"),
        ),
    ]
