# Generated by Django 5.1.1 on 2024-09-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0096_merge_20240923_1141"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalsubstance",
            name="substance_types",
        ),
        migrations.AddField(
            model_name="declaredsubstance",
            name="new_name",
            field=models.TextField(blank=True, verbose_name="libellé"),
        ),
        migrations.AddField(
            model_name="historicaldeclaredsubstance",
            name="new_name",
            field=models.TextField(blank=True, verbose_name="libellé"),
        ),
    ]
