# Generated by Django 5.1.1 on 2024-09-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0096_remove_historicalsubstance_substance_types_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="declaredsubstance",
            name="quantity",
            field=models.FloatField(
                blank=True, null=True, verbose_name="quantité par DJR"
            ),
        ),
        migrations.AddField(
            model_name="historicaldeclaredsubstance",
            name="quantity",
            field=models.FloatField(
                blank=True, null=True, verbose_name="quantité par DJR"
            ),
        ),
    ]
