# Generated by Django 5.1.2 on 2024-11-04 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0098_alter_computedsubstance_substance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='declaration',
            old_name='private_notes',
            new_name='private_notes_instruction',
        ),
        migrations.RenameField(
            model_name='historicaldeclaration',
            old_name='private_notes',
            new_name='private_notes_instruction',
        ),
    ]
