# Generated by Django 5.1.2 on 2024-10-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0098_alter_computedsubstance_substance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='country',
            field=models.CharField(choices=[('FR', 'France'), ('DE', 'Allemagne'), ('AT', 'Autriche'), ('BE', 'Belgique'), ('BG', 'Bulgarie'), ('CY', 'Chypre'), ('HR', 'Croatie'), ('DK', 'Danemark'), ('ES', 'Espagne'), ('EE', 'Estonie'), ('FI', 'Finlande'), ('GB', 'Grande-Bretagne'), ('GR', 'Grèce'), ('HU', 'Hongrie'), ('IE', 'Irlande'), ('NI', 'Irlande du Nord'), ('IS', 'Islande'), ('IT', 'Italie'), ('LV', 'Lettonie'), ('LI', 'Liechtenstein'), ('LT', 'Lituanie'), ('LU', 'Luxembourg'), ('MT', 'Malte'), ('NO', 'Norvège'), ('NL', 'Pays-Bas'), ('PL', 'Pologne'), ('PT', 'Portugal'), ('RO', 'Roumanie'), ('SK', 'Slovaquie'), ('SI', 'Slovénie'), ('SE', 'Suède'), ('CH', 'Suisse'), ('CZ', 'République Tchèque')], default='FR', max_length=50, verbose_name='pays'),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='country',
            field=models.TextField(blank=True, choices=[('FR', 'France'), ('DE', 'Allemagne'), ('AT', 'Autriche'), ('BE', 'Belgique'), ('BG', 'Bulgarie'), ('CY', 'Chypre'), ('HR', 'Croatie'), ('DK', 'Danemark'), ('ES', 'Espagne'), ('EE', 'Estonie'), ('FI', 'Finlande'), ('GB', 'Grande-Bretagne'), ('GR', 'Grèce'), ('HU', 'Hongrie'), ('IE', 'Irlande'), ('NI', 'Irlande du Nord'), ('IS', 'Islande'), ('IT', 'Italie'), ('LV', 'Lettonie'), ('LI', 'Liechtenstein'), ('LT', 'Lituanie'), ('LU', 'Luxembourg'), ('MT', 'Malte'), ('NO', 'Norvège'), ('NL', 'Pays-Bas'), ('PL', 'Pologne'), ('PT', 'Portugal'), ('RO', 'Roumanie'), ('SK', 'Slovaquie'), ('SI', 'Slovénie'), ('SE', 'Suède'), ('CH', 'Suisse'), ('CZ', 'République Tchèque')], verbose_name='pays'),
        ),
        migrations.AlterField(
            model_name='declaredingredient',
            name='eu_reference_country',
            field=models.CharField(blank=True, choices=[('FR', 'France'), ('DE', 'Allemagne'), ('AT', 'Autriche'), ('BE', 'Belgique'), ('BG', 'Bulgarie'), ('CY', 'Chypre'), ('HR', 'Croatie'), ('DK', 'Danemark'), ('ES', 'Espagne'), ('EE', 'Estonie'), ('FI', 'Finlande'), ('GB', 'Grande-Bretagne'), ('GR', 'Grèce'), ('HU', 'Hongrie'), ('IE', 'Irlande'), ('NI', 'Irlande du Nord'), ('IS', 'Islande'), ('IT', 'Italie'), ('LV', 'Lettonie'), ('LI', 'Liechtenstein'), ('LT', 'Lituanie'), ('LU', 'Luxembourg'), ('MT', 'Malte'), ('NO', 'Norvège'), ('NL', 'Pays-Bas'), ('PL', 'Pologne'), ('PT', 'Portugal'), ('RO', 'Roumanie'), ('SK', 'Slovaquie'), ('SI', 'Slovénie'), ('SE', 'Suède'), ('CH', 'Suisse'), ('CZ', 'République Tchèque')], default='FR', verbose_name='pays de source réglementaire'),
        ),
        migrations.AlterField(
            model_name='declaredmicroorganism',
            name='eu_reference_country',
            field=models.CharField(blank=True, choices=[('FR', 'France'), ('DE', 'Allemagne'), ('AT', 'Autriche'), ('BE', 'Belgique'), ('BG', 'Bulgarie'), ('CY', 'Chypre'), ('HR', 'Croatie'), ('DK', 'Danemark'), ('ES', 'Espagne'), ('EE', 'Estonie'), ('FI', 'Finlande'), ('GB', 'Grande-Bretagne'), ('GR', 'Grèce'), ('HU', 'Hongrie'), ('IE', 'Irlande'), ('NI', 'Irlande du Nord'), ('IS', 'Islande'), ('IT', 'Italie'), ('LV', 'Lettonie'), ('LI', 'Liechtenstein'), ('LT', 'Lituanie'), ('LU', 'Luxembourg'), ('MT', 'Malte'), ('NO', 'Norvège'), ('NL', 'Pays-Bas'), ('PL', 'Pologne'), ('PT', 'Portugal'), ('RO', 'Roumanie'), ('SK', 'Slovaquie'), ('SI', 'Slovénie'), ('SE', 'Suède'), ('CH', 'Suisse'), ('CZ', 'République Tchèque')], default='FR', verbose_name='pays de source réglementaire'),
        ),
        migrations.AlterField(
            model_name='declaredplant',
            name='eu_reference_country',
            field=models.CharField(blank=True, choices=[('FR', 'France'), ('DE', 'Allemagne'), ('AT', 'Autriche'), ('BE', 'Belgique'), ('BG', 'Bulgarie'), ('CY', 'Chypre'), ('HR', 'Croatie'), ('DK', 'Danemark'), ('ES', 'Espagne'), ('EE', 'Estonie'), ('FI', 'Finlande'), ('GB', 'Grande-Bretagne'), ('GR', 'Grèce'), ('HU', 'Hongrie'), ('IE', 'Irlande'), ('NI', 'Irlande du Nord'), ('IS', 'Islande'), ('IT', 'Italie'), ('LV', 'Lettonie'), ('LI', 'Liechtenstein'), ('LT', 'Lituanie'), ('LU', 'Luxembourg'), ('MT', 'Malte'), ('NO', 'Norvège'), ('NL', 'Pays-Bas'), ('PL', 'Pologne'), ('PT', 'Portugal'), ('RO', 'Roumanie'), ('SK', 'Slovaquie'), ('SI', 'Slovénie'), ('SE', 'Suède'), ('CH', 'Suisse'), ('CZ', 'République Tchèque')], default='FR', verbose_name='pays de source réglementaire'),
        ),
        migrations.AlterField(
            model_name='declaredsubstance',
            name='eu_reference_country',
            field=models.CharField(blank=True, choices=[('FR', 'France'), ('DE', 'Allemagne'), ('AT', 'Autriche'), ('BE', 'Belgique'), ('BG', 'Bulgarie'), ('CY', 'Chypre'), ('HR', 'Croatie'), ('DK', 'Danemark'), ('ES', 'Espagne'), ('EE', 'Estonie'), ('FI', 'Finlande'), ('GB', 'Grande-Bretagne'), ('GR', 'Grèce'), ('HU', 'Hongrie'), ('IE', 'Irlande'), ('NI', 'Irlande du Nord'), ('IS', 'Islande'), ('IT', 'Italie'), ('LV', 'Lettonie'), ('LI', 'Liechtenstein'), ('LT', 'Lituanie'), ('LU', 'Luxembourg'), ('MT', 'Malte'), ('NO', 'Norvège'), ('NL', 'Pays-Bas'), ('PL', 'Pologne'), ('PT', 'Portugal'), ('RO', 'Roumanie'), ('SK', 'Slovaquie'), ('SI', 'Slovénie'), ('SE', 'Suède'), ('CH', 'Suisse'), ('CZ', 'République Tchèque')], default='FR', verbose_name='pays de source réglementaire'),
        ),
        migrations.AlterField(
            model_name='historicaldeclaration',
            name='country',
            field=models.TextField(blank=True, choices=[('FR', 'France'), ('DE', 'Allemagne'), ('AT', 'Autriche'), ('BE', 'Belgique'), ('BG', 'Bulgarie'), ('CY', 'Chypre'), ('HR', 'Croatie'), ('DK', 'Danemark'), ('ES', 'Espagne'), ('EE', 'Estonie'), ('FI', 'Finlande'), ('GB', 'Grande-Bretagne'), ('GR', 'Grèce'), ('HU', 'Hongrie'), ('IE', 'Irlande'), ('NI', 'Irlande du Nord'), ('IS', 'Islande'), ('IT', 'Italie'), ('LV', 'Lettonie'), ('LI', 'Liechtenstein'), ('LT', 'Lituanie'), ('LU', 'Luxembourg'), ('MT', 'Malte'), ('NO', 'Norvège'), ('NL', 'Pays-Bas'), ('PL', 'Pologne'), ('PT', 'Portugal'), ('RO', 'Roumanie'), ('SK', 'Slovaquie'), ('SI', 'Slovénie'), ('SE', 'Suède'), ('CH', 'Suisse'), ('CZ', 'République Tchèque')], verbose_name='pays'),
        ),
        migrations.AlterField(
            model_name='historicaldeclaredingredient',
            name='eu_reference_country',
            field=models.CharField(blank=True, choices=[('FR', 'France'), ('DE', 'Allemagne'), ('AT', 'Autriche'), ('BE', 'Belgique'), ('BG', 'Bulgarie'), ('CY', 'Chypre'), ('HR', 'Croatie'), ('DK', 'Danemark'), ('ES', 'Espagne'), ('EE', 'Estonie'), ('FI', 'Finlande'), ('GB', 'Grande-Bretagne'), ('GR', 'Grèce'), ('HU', 'Hongrie'), ('IE', 'Irlande'), ('NI', 'Irlande du Nord'), ('IS', 'Islande'), ('IT', 'Italie'), ('LV', 'Lettonie'), ('LI', 'Liechtenstein'), ('LT', 'Lituanie'), ('LU', 'Luxembourg'), ('MT', 'Malte'), ('NO', 'Norvège'), ('NL', 'Pays-Bas'), ('PL', 'Pologne'), ('PT', 'Portugal'), ('RO', 'Roumanie'), ('SK', 'Slovaquie'), ('SI', 'Slovénie'), ('SE', 'Suède'), ('CH', 'Suisse'), ('CZ', 'République Tchèque')], default='FR', verbose_name='pays de source réglementaire'),
        ),
        migrations.AlterField(
            model_name='historicaldeclaredmicroorganism',
            name='eu_reference_country',
            field=models.CharField(blank=True, choices=[('FR', 'France'), ('DE', 'Allemagne'), ('AT', 'Autriche'), ('BE', 'Belgique'), ('BG', 'Bulgarie'), ('CY', 'Chypre'), ('HR', 'Croatie'), ('DK', 'Danemark'), ('ES', 'Espagne'), ('EE', 'Estonie'), ('FI', 'Finlande'), ('GB', 'Grande-Bretagne'), ('GR', 'Grèce'), ('HU', 'Hongrie'), ('IE', 'Irlande'), ('NI', 'Irlande du Nord'), ('IS', 'Islande'), ('IT', 'Italie'), ('LV', 'Lettonie'), ('LI', 'Liechtenstein'), ('LT', 'Lituanie'), ('LU', 'Luxembourg'), ('MT', 'Malte'), ('NO', 'Norvège'), ('NL', 'Pays-Bas'), ('PL', 'Pologne'), ('PT', 'Portugal'), ('RO', 'Roumanie'), ('SK', 'Slovaquie'), ('SI', 'Slovénie'), ('SE', 'Suède'), ('CH', 'Suisse'), ('CZ', 'République Tchèque')], default='FR', verbose_name='pays de source réglementaire'),
        ),
        migrations.AlterField(
            model_name='historicaldeclaredplant',
            name='eu_reference_country',
            field=models.CharField(blank=True, choices=[('FR', 'France'), ('DE', 'Allemagne'), ('AT', 'Autriche'), ('BE', 'Belgique'), ('BG', 'Bulgarie'), ('CY', 'Chypre'), ('HR', 'Croatie'), ('DK', 'Danemark'), ('ES', 'Espagne'), ('EE', 'Estonie'), ('FI', 'Finlande'), ('GB', 'Grande-Bretagne'), ('GR', 'Grèce'), ('HU', 'Hongrie'), ('IE', 'Irlande'), ('NI', 'Irlande du Nord'), ('IS', 'Islande'), ('IT', 'Italie'), ('LV', 'Lettonie'), ('LI', 'Liechtenstein'), ('LT', 'Lituanie'), ('LU', 'Luxembourg'), ('MT', 'Malte'), ('NO', 'Norvège'), ('NL', 'Pays-Bas'), ('PL', 'Pologne'), ('PT', 'Portugal'), ('RO', 'Roumanie'), ('SK', 'Slovaquie'), ('SI', 'Slovénie'), ('SE', 'Suède'), ('CH', 'Suisse'), ('CZ', 'République Tchèque')], default='FR', verbose_name='pays de source réglementaire'),
        ),
        migrations.AlterField(
            model_name='historicaldeclaredsubstance',
            name='eu_reference_country',
            field=models.CharField(blank=True, choices=[('FR', 'France'), ('DE', 'Allemagne'), ('AT', 'Autriche'), ('BE', 'Belgique'), ('BG', 'Bulgarie'), ('CY', 'Chypre'), ('HR', 'Croatie'), ('DK', 'Danemark'), ('ES', 'Espagne'), ('EE', 'Estonie'), ('FI', 'Finlande'), ('GB', 'Grande-Bretagne'), ('GR', 'Grèce'), ('HU', 'Hongrie'), ('IE', 'Irlande'), ('NI', 'Irlande du Nord'), ('IS', 'Islande'), ('IT', 'Italie'), ('LV', 'Lettonie'), ('LI', 'Liechtenstein'), ('LT', 'Lituanie'), ('LU', 'Luxembourg'), ('MT', 'Malte'), ('NO', 'Norvège'), ('NL', 'Pays-Bas'), ('PL', 'Pologne'), ('PT', 'Portugal'), ('RO', 'Roumanie'), ('SK', 'Slovaquie'), ('SI', 'Slovénie'), ('SE', 'Suède'), ('CH', 'Suisse'), ('CZ', 'République Tchèque')], default='FR', verbose_name='pays de source réglementaire'),
        ),
    ]
