# Generated by Django 5.1.2 on 2024-11-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0099_rename_private_notes_declaration_private_notes_instruction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaration',
            name='private_notes_visa',
            field=models.TextField(blank=True, default='', verbose_name="notes du visa à destination de l'administration"),
        ),
        migrations.AddField(
            model_name='historicaldeclaration',
            name='private_notes_visa',
            field=models.TextField(blank=True, default='', verbose_name="notes du visa à destination de l'administration"),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='private_notes_instruction',
            field=models.TextField(blank=True, default='', verbose_name="notes de l'instruction à destination de l'administration"),
        ),
        migrations.AlterField(
            model_name='historicaldeclaration',
            name='private_notes_instruction',
            field=models.TextField(blank=True, default='', verbose_name="notes de l'instruction à destination de l'administration"),
        ),
    ]
