# Generated by Django 5.1.3 on 2024-11-14 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0101_galenicformulation_is_risky_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshot',
            name='action',
            field=models.CharField(blank=True, choices=[('SUBMIT', 'soumettre pour instruction'), ('TAKE_FOR_INSTRUCTION', 'prendre pour instruction'), ('OBSERVE_NO_VISA', 'mettre en observation sans visa'), ('AUTHORIZE_NO_VISA', 'autoriser sans visa'), ('RESPOND_TO_OBSERVATION', 'répondre à une observation'), ('RESPOND_TO_OBJECTION', 'répondre à une objection'), ('REQUEST_VISA', 'demander un visa'), ('TAKE_FOR_VISA', 'prendre pour visa'), ('APPROVE_VISA', 'valider le visa'), ('REFUSE_VISA', 'refuser le visa'), ('WITHDRAW', 'retirer du marché'), ('ABANDON', 'mettre en abandon'), ('AUTOMATICALLY_AUTHORIZE', 'validé automatiquement par le bot'), ('OTHER', 'autre')], default='OTHER', max_length=50),
        ),
    ]
