# Generated by Django 5.1.3 on 2024-11-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0101_galenicformulation_is_risky_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalingredient",
            name="novel_food",
            field=models.BooleanField(
                default=False, verbose_name="est considéré comme Novel Food ?"
            ),
        ),
        migrations.AddField(
            model_name="historicalmicroorganism",
            name="novel_food",
            field=models.BooleanField(
                default=False, verbose_name="est considéré comme Novel Food ?"
            ),
        ),
        migrations.AddField(
            model_name="historicalplant",
            name="novel_food",
            field=models.BooleanField(
                default=False, verbose_name="est considéré comme Novel Food ?"
            ),
        ),
        migrations.AddField(
            model_name="historicalsubstance",
            name="novel_food",
            field=models.BooleanField(
                default=False, verbose_name="est considéré comme Novel Food ?"
            ),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="novel_food",
            field=models.BooleanField(
                default=False, verbose_name="est considéré comme Novel Food ?"
            ),
        ),
        migrations.AddField(
            model_name="microorganism",
            name="novel_food",
            field=models.BooleanField(
                default=False, verbose_name="est considéré comme Novel Food ?"
            ),
        ),
        migrations.AddField(
            model_name="plant",
            name="novel_food",
            field=models.BooleanField(
                default=False, verbose_name="est considéré comme Novel Food ?"
            ),
        ),
        migrations.AddField(
            model_name="substance",
            name="novel_food",
            field=models.BooleanField(
                default=False, verbose_name="est considéré comme Novel Food ?"
            ),
        ),
    ]
