# Generated by Django 5.1.2 on 2024-11-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0101_galenicformulation_is_risky_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaredingredient',
            name='private_notes_instruction',
            field=models.TextField(blank=True, default='', verbose_name="notes de l'instruction à destination de l'administration"),
        ),
        migrations.AddField(
            model_name='declaredingredient',
            name='status',
            field=models.CharField(choices=[('NEW', 'Nouveau'), ('INFORMATION', "En attente de plus d'information"), ('REJECTED', 'Refusé')], default='NEW', max_length=50, verbose_name='statut'),
        ),
        migrations.AddField(
            model_name='declaredmicroorganism',
            name='private_notes_instruction',
            field=models.TextField(blank=True, default='', verbose_name="notes de l'instruction à destination de l'administration"),
        ),
        migrations.AddField(
            model_name='declaredmicroorganism',
            name='status',
            field=models.CharField(choices=[('NEW', 'Nouveau'), ('INFORMATION', "En attente de plus d'information"), ('REJECTED', 'Refusé')], default='NEW', max_length=50, verbose_name='statut'),
        ),
        migrations.AddField(
            model_name='declaredplant',
            name='private_notes_instruction',
            field=models.TextField(blank=True, default='', verbose_name="notes de l'instruction à destination de l'administration"),
        ),
        migrations.AddField(
            model_name='declaredplant',
            name='status',
            field=models.CharField(choices=[('NEW', 'Nouveau'), ('INFORMATION', "En attente de plus d'information"), ('REJECTED', 'Refusé')], default='NEW', max_length=50, verbose_name='statut'),
        ),
        migrations.AddField(
            model_name='declaredsubstance',
            name='private_notes_instruction',
            field=models.TextField(blank=True, default='', verbose_name="notes de l'instruction à destination de l'administration"),
        ),
        migrations.AddField(
            model_name='declaredsubstance',
            name='status',
            field=models.CharField(choices=[('NEW', 'Nouveau'), ('INFORMATION', "En attente de plus d'information"), ('REJECTED', 'Refusé')], default='NEW', max_length=50, verbose_name='statut'),
        ),
        migrations.AddField(
            model_name='historicaldeclaredingredient',
            name='private_notes_instruction',
            field=models.TextField(blank=True, default='', verbose_name="notes de l'instruction à destination de l'administration"),
        ),
        migrations.AddField(
            model_name='historicaldeclaredingredient',
            name='status',
            field=models.CharField(choices=[('NEW', 'Nouveau'), ('INFORMATION', "En attente de plus d'information"), ('REJECTED', 'Refusé')], default='NEW', max_length=50, verbose_name='statut'),
        ),
        migrations.AddField(
            model_name='historicaldeclaredmicroorganism',
            name='private_notes_instruction',
            field=models.TextField(blank=True, default='', verbose_name="notes de l'instruction à destination de l'administration"),
        ),
        migrations.AddField(
            model_name='historicaldeclaredmicroorganism',
            name='status',
            field=models.CharField(choices=[('NEW', 'Nouveau'), ('INFORMATION', "En attente de plus d'information"), ('REJECTED', 'Refusé')], default='NEW', max_length=50, verbose_name='statut'),
        ),
        migrations.AddField(
            model_name='historicaldeclaredplant',
            name='private_notes_instruction',
            field=models.TextField(blank=True, default='', verbose_name="notes de l'instruction à destination de l'administration"),
        ),
        migrations.AddField(
            model_name='historicaldeclaredplant',
            name='status',
            field=models.CharField(choices=[('NEW', 'Nouveau'), ('INFORMATION', "En attente de plus d'information"), ('REJECTED', 'Refusé')], default='NEW', max_length=50, verbose_name='statut'),
        ),
        migrations.AddField(
            model_name='historicaldeclaredsubstance',
            name='private_notes_instruction',
            field=models.TextField(blank=True, default='', verbose_name="notes de l'instruction à destination de l'administration"),
        ),
        migrations.AddField(
            model_name='historicaldeclaredsubstance',
            name='status',
            field=models.CharField(choices=[('NEW', 'Nouveau'), ('INFORMATION', "En attente de plus d'information"), ('REJECTED', 'Refusé')], default='NEW', max_length=50, verbose_name='statut'),
        ),
    ]
