# Generated by Django 5.1.3 on 2024-11-18 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0102_alter_snapshot_action"),
        ("data", "0102_historicalingredient_novel_food_and_more"),
    ]

    operations = []
