# Generated by Django 5.1.2 on 2024-12-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0105_alter_declaration_calculated_article_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaredingredient',
            name='request_private_notes',
            field=models.TextField(blank=True, verbose_name="notes de l'instruction à destination de l'administration"),
        ),
        migrations.AddField(
            model_name='declaredingredient',
            name='request_status',
            field=models.CharField(choices=[('REQUESTED', 'Ingrédient ajouté à la déclaration par le déclarant'), ('INFORMATION', "En attente de plus d'information"), ('REJECTED', 'Refusé')], default='REQUESTED', max_length=50, verbose_name="statut de la demande de l'ajout du nouvel ingrédient"),
        ),
        migrations.AddField(
            model_name='declaredmicroorganism',
            name='request_private_notes',
            field=models.TextField(blank=True, verbose_name="notes de l'instruction à destination de l'administration"),
        ),
        migrations.AddField(
            model_name='declaredmicroorganism',
            name='request_status',
            field=models.CharField(choices=[('REQUESTED', 'Ingrédient ajouté à la déclaration par le déclarant'), ('INFORMATION', "En attente de plus d'information"), ('REJECTED', 'Refusé')], default='REQUESTED', max_length=50, verbose_name="statut de la demande de l'ajout du nouvel ingrédient"),
        ),
        migrations.AddField(
            model_name='declaredplant',
            name='request_private_notes',
            field=models.TextField(blank=True, verbose_name="notes de l'instruction à destination de l'administration"),
        ),
        migrations.AddField(
            model_name='declaredplant',
            name='request_status',
            field=models.CharField(choices=[('REQUESTED', 'Ingrédient ajouté à la déclaration par le déclarant'), ('INFORMATION', "En attente de plus d'information"), ('REJECTED', 'Refusé')], default='REQUESTED', max_length=50, verbose_name="statut de la demande de l'ajout du nouvel ingrédient"),
        ),
        migrations.AddField(
            model_name='declaredsubstance',
            name='request_private_notes',
            field=models.TextField(blank=True, verbose_name="notes de l'instruction à destination de l'administration"),
        ),
        migrations.AddField(
            model_name='declaredsubstance',
            name='request_status',
            field=models.CharField(choices=[('REQUESTED', 'Ingrédient ajouté à la déclaration par le déclarant'), ('INFORMATION', "En attente de plus d'information"), ('REJECTED', 'Refusé')], default='REQUESTED', max_length=50, verbose_name="statut de la demande de l'ajout du nouvel ingrédient"),
        ),
        migrations.AddField(
            model_name='historicaldeclaredingredient',
            name='request_private_notes',
            field=models.TextField(blank=True, verbose_name="notes de l'instruction à destination de l'administration"),
        ),
        migrations.AddField(
            model_name='historicaldeclaredingredient',
            name='request_status',
            field=models.CharField(choices=[('REQUESTED', 'Ingrédient ajouté à la déclaration par le déclarant'), ('INFORMATION', "En attente de plus d'information"), ('REJECTED', 'Refusé')], default='REQUESTED', max_length=50, verbose_name="statut de la demande de l'ajout du nouvel ingrédient"),
        ),
        migrations.AddField(
            model_name='historicaldeclaredmicroorganism',
            name='request_private_notes',
            field=models.TextField(blank=True, verbose_name="notes de l'instruction à destination de l'administration"),
        ),
        migrations.AddField(
            model_name='historicaldeclaredmicroorganism',
            name='request_status',
            field=models.CharField(choices=[('REQUESTED', 'Ingrédient ajouté à la déclaration par le déclarant'), ('INFORMATION', "En attente de plus d'information"), ('REJECTED', 'Refusé')], default='REQUESTED', max_length=50, verbose_name="statut de la demande de l'ajout du nouvel ingrédient"),
        ),
        migrations.AddField(
            model_name='historicaldeclaredplant',
            name='request_private_notes',
            field=models.TextField(blank=True, verbose_name="notes de l'instruction à destination de l'administration"),
        ),
        migrations.AddField(
            model_name='historicaldeclaredplant',
            name='request_status',
            field=models.CharField(choices=[('REQUESTED', 'Ingrédient ajouté à la déclaration par le déclarant'), ('INFORMATION', "En attente de plus d'information"), ('REJECTED', 'Refusé')], default='REQUESTED', max_length=50, verbose_name="statut de la demande de l'ajout du nouvel ingrédient"),
        ),
        migrations.AddField(
            model_name='historicaldeclaredsubstance',
            name='request_private_notes',
            field=models.TextField(blank=True, verbose_name="notes de l'instruction à destination de l'administration"),
        ),
        migrations.AddField(
            model_name='historicaldeclaredsubstance',
            name='request_status',
            field=models.CharField(choices=[('REQUESTED', 'Ingrédient ajouté à la déclaration par le déclarant'), ('INFORMATION', "En attente de plus d'information"), ('REJECTED', 'Refusé')], default='REQUESTED', max_length=50, verbose_name="statut de la demande de l'ajout du nouvel ingrédient"),
        ),
    ]
