# Generated by Django 5.1.3 on 2024-11-27 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0105_alter_declaration_calculated_article_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='mandated_companies',
            field=models.ManyToManyField(blank=True, related_name='represented_companies', to='data.company', verbose_name='Autres entreprises pouvant déclarer pour cette entreprise'),
        ),
        migrations.AddField(
            model_name='declaration',
            name='mandated_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mandated_declarations', to='data.company', verbose_name='entreprise mandataire'),
        ),
        migrations.AddField(
            model_name='historicaldeclaration',
            name='mandated_company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='data.company', verbose_name='entreprise mandataire'),
        ),
    ]
