# Generated by Django 5.1.2 on 2024-11-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0106_declaredingredient_request_private_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaredingredient',
            name='request_status',
            field=models.CharField(choices=[('ADDED', 'Ingrédient ajouté par le déclarant'), ('INFORMATION', "En attente de plus d'information"), ('REJECTED', 'Refusé'), ('REPLACED', 'Remplacé par un ingrédient existant')], default='ADDED', max_length=50, verbose_name="statut de la demande de l'ajout du nouvel ingrédient"),
        ),
        migrations.AlterField(
            model_name='declaredmicroorganism',
            name='request_status',
            field=models.CharField(choices=[('ADDED', 'Ingrédient ajouté par le déclarant'), ('INFORMATION', "En attente de plus d'information"), ('REJECTED', 'Refusé'), ('REPLACED', 'Remplacé par un ingrédient existant')], default='ADDED', max_length=50, verbose_name="statut de la demande de l'ajout du nouvel ingrédient"),
        ),
        migrations.AlterField(
            model_name='declaredplant',
            name='request_status',
            field=models.CharField(choices=[('ADDED', 'Ingrédient ajouté par le déclarant'), ('INFORMATION', "En attente de plus d'information"), ('REJECTED', 'Refusé'), ('REPLACED', 'Remplacé par un ingrédient existant')], default='ADDED', max_length=50, verbose_name="statut de la demande de l'ajout du nouvel ingrédient"),
        ),
        migrations.AlterField(
            model_name='declaredsubstance',
            name='request_status',
            field=models.CharField(choices=[('ADDED', 'Ingrédient ajouté par le déclarant'), ('INFORMATION', "En attente de plus d'information"), ('REJECTED', 'Refusé'), ('REPLACED', 'Remplacé par un ingrédient existant')], default='ADDED', max_length=50, verbose_name="statut de la demande de l'ajout du nouvel ingrédient"),
        ),
        migrations.AlterField(
            model_name='historicaldeclaredingredient',
            name='request_status',
            field=models.CharField(choices=[('ADDED', 'Ingrédient ajouté par le déclarant'), ('INFORMATION', "En attente de plus d'information"), ('REJECTED', 'Refusé'), ('REPLACED', 'Remplacé par un ingrédient existant')], default='ADDED', max_length=50, verbose_name="statut de la demande de l'ajout du nouvel ingrédient"),
        ),
        migrations.AlterField(
            model_name='historicaldeclaredmicroorganism',
            name='request_status',
            field=models.CharField(choices=[('ADDED', 'Ingrédient ajouté par le déclarant'), ('INFORMATION', "En attente de plus d'information"), ('REJECTED', 'Refusé'), ('REPLACED', 'Remplacé par un ingrédient existant')], default='ADDED', max_length=50, verbose_name="statut de la demande de l'ajout du nouvel ingrédient"),
        ),
        migrations.AlterField(
            model_name='historicaldeclaredplant',
            name='request_status',
            field=models.CharField(choices=[('ADDED', 'Ingrédient ajouté par le déclarant'), ('INFORMATION', "En attente de plus d'information"), ('REJECTED', 'Refusé'), ('REPLACED', 'Remplacé par un ingrédient existant')], default='ADDED', max_length=50, verbose_name="statut de la demande de l'ajout du nouvel ingrédient"),
        ),
        migrations.AlterField(
            model_name='historicaldeclaredsubstance',
            name='request_status',
            field=models.CharField(choices=[('ADDED', 'Ingrédient ajouté par le déclarant'), ('INFORMATION', "En attente de plus d'information"), ('REJECTED', 'Refusé'), ('REPLACED', 'Remplacé par un ingrédient existant')], default='ADDED', max_length=50, verbose_name="statut de la demande de l'ajout du nouvel ingrédient"),
        ),
    ]
