# Generated by Django 5.1.3 on 2024-11-28 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0106_alter_declaration_calculated_article_and_more'),
        ('data', '0106_company_mandated_companies_and_more'),
    ]

    operations = [
    ]
