# Generated by Django 5.1.2 on 2024-12-05 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0106_alter_declaration_calculated_article_and_more'),
        ('data', '0106_declaredingredient_request_private_notes_and_more'),
    ]

    operations = [
    ]
