# Generated by Django 5.1.3 on 2024-12-05 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0106_declaredingredient_request_private_notes_and_more'),
        ('data', '0107_merge_20241128_1025'),
    ]

    operations = [
    ]
