# Generated by Django 5.1.2 on 2024-12-05 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0107_alter_declaredingredient_request_status_and_more'),
        ('data', '0107_merge_20241205_1408'),
    ]

    operations = [
    ]
