# Generated by Django 5.1.3 on 2024-12-05 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0106_company_mandated_companies_and_more'),
        ('data', '0107_merge_20241205_1408'),
    ]

    operations = [
    ]
