# Generated by Django 5.1.2 on 2024-12-19 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0108_merge_20241205_1521'),
        ('data', '0108_merge_20241205_1538'),
    ]

    operations = [
    ]
