# Generated by Django 5.1.4 on 2024-12-19 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0109_icacomplementalimentaire_icadeclaration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='siccrf_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='data.icaetablissement', verbose_name='id dans les tables et tables relationnelles SICCRF'),
        ),
    ]
