# Generated by Django 5.1.4 on 2024-12-27 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0109_icacomplementalimentaire_icadeclaration_and_more'),
        ('data', '0109_merge_20241219_2256'),
    ]

    operations = [
    ]
