# Generated by Django 5.1.4 on 2024-12-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0109_icacomplementalimentaire_icadeclaration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaration',
            name='siccrf_id',
            field=models.IntegerField(blank=True, db_index=True, editable=False, null=True, unique=True, verbose_name='cplalim_ident dans le modèle IcaComplementAlimentaire si la déclaration provient de Teleicare'),
        ),
        migrations.AddField(
            model_name='historicaldeclaration',
            name='siccrf_id',
            field=models.IntegerField(blank=True, db_index=True, editable=False, null=True, verbose_name='cplalim_ident dans le modèle IcaComplementAlimentaire si la déclaration provient de Teleicare'),
        ),
        migrations.AlterField(
            model_name='company',
            name='siccrf_id',
            field=models.IntegerField(blank=True, db_index=True, editable=False, null=True, unique=True, verbose_name='etab_ident dans le modèle IcaEtablissement SICCRF'),
        ),
    ]
