# Generated by Django 5.1.4 on 2025-01-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0110_declaration_siccrf_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='matched',
            field=models.BooleanField(default=False, verbose_name="La Company Compl'Alim a été matchée avec un Etablissement TeleIcare"),
        ),
        migrations.AlterField(
            model_name='company',
            name='commercial_name',
            field=models.CharField(blank=True, help_text='nom commercial', verbose_name='enseigne'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='adresse e-mail de contact'),
        ),
    ]
