# Generated by Django 5.1.4 on 2025-01-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0110_merge_20241227_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaredingredient',
            name='request_status',
            field=models.CharField(choices=[('REQUESTED', 'Ingrédient ajouté à la déclaration par le déclarant'), ('INFORMATION', "En attente de plus d'information"), ('REJECTED', 'Refusé'), ('REPLACED', 'Remplacé par un ingrédient existant')], default='REQUESTED', max_length=50, verbose_name="statut de la demande de l'ajout du nouvel ingrédient"),
        ),
        migrations.AlterField(
            model_name='declaredmicroorganism',
            name='request_status',
            field=models.CharField(choices=[('REQUESTED', 'Ingrédient ajouté à la déclaration par le déclarant'), ('INFORMATION', "En attente de plus d'information"), ('REJECTED', 'Refusé'), ('REPLACED', 'Remplacé par un ingrédient existant')], default='REQUESTED', max_length=50, verbose_name="statut de la demande de l'ajout du nouvel ingrédient"),
        ),
        migrations.AlterField(
            model_name='declaredplant',
            name='request_status',
            field=models.CharField(choices=[('REQUESTED', 'Ingrédient ajouté à la déclaration par le déclarant'), ('INFORMATION', "En attente de plus d'information"), ('REJECTED', 'Refusé'), ('REPLACED', 'Remplacé par un ingrédient existant')], default='REQUESTED', max_length=50, verbose_name="statut de la demande de l'ajout du nouvel ingrédient"),
        ),
        migrations.AlterField(
            model_name='declaredsubstance',
            name='request_status',
            field=models.CharField(choices=[('REQUESTED', 'Ingrédient ajouté à la déclaration par le déclarant'), ('INFORMATION', "En attente de plus d'information"), ('REJECTED', 'Refusé'), ('REPLACED', 'Remplacé par un ingrédient existant')], default='REQUESTED', max_length=50, verbose_name="statut de la demande de l'ajout du nouvel ingrédient"),
        ),
        migrations.AlterField(
            model_name='historicaldeclaredingredient',
            name='request_status',
            field=models.CharField(choices=[('REQUESTED', 'Ingrédient ajouté à la déclaration par le déclarant'), ('INFORMATION', "En attente de plus d'information"), ('REJECTED', 'Refusé'), ('REPLACED', 'Remplacé par un ingrédient existant')], default='REQUESTED', max_length=50, verbose_name="statut de la demande de l'ajout du nouvel ingrédient"),
        ),
        migrations.AlterField(
            model_name='historicaldeclaredmicroorganism',
            name='request_status',
            field=models.CharField(choices=[('REQUESTED', 'Ingrédient ajouté à la déclaration par le déclarant'), ('INFORMATION', "En attente de plus d'information"), ('REJECTED', 'Refusé'), ('REPLACED', 'Remplacé par un ingrédient existant')], default='REQUESTED', max_length=50, verbose_name="statut de la demande de l'ajout du nouvel ingrédient"),
        ),
        migrations.AlterField(
            model_name='historicaldeclaredplant',
            name='request_status',
            field=models.CharField(choices=[('REQUESTED', 'Ingrédient ajouté à la déclaration par le déclarant'), ('INFORMATION', "En attente de plus d'information"), ('REJECTED', 'Refusé'), ('REPLACED', 'Remplacé par un ingrédient existant')], default='REQUESTED', max_length=50, verbose_name="statut de la demande de l'ajout du nouvel ingrédient"),
        ),
        migrations.AlterField(
            model_name='historicaldeclaredsubstance',
            name='request_status',
            field=models.CharField(choices=[('REQUESTED', 'Ingrédient ajouté à la déclaration par le déclarant'), ('INFORMATION', "En attente de plus d'information"), ('REJECTED', 'Refusé'), ('REPLACED', 'Remplacé par un ingrédient existant')], default='REQUESTED', max_length=50, verbose_name="statut de la demande de l'ajout du nouvel ingrédient"),
        ),
    ]
