# Generated by Django 5.1.4 on 2025-01-09 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0111_company_matched_alter_company_commercial_name_and_more'),
        ('data', '0112_blogpost_content_alter_blogpost_body'),
    ]

    operations = [
    ]
