# Generated by Django 5.1.4 on 2025-01-10 09:28

import data.fields
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0113_merge_20250109_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='activities',
            field=data.fields.MultipleChoiceField(base_field=models.CharField(choices=[('FABRICANT', 'Fabricant'), ('FAÇONNIER', 'Façonnier'), ('IMPORTATEUR', 'Importateur'), ('INTRODUCTEUR', 'Introducteur'), ('CONSEIL', 'Conseil'), ('DISTRIBUTEUR', 'Distributeur')]), blank=True, default=list, size=None, verbose_name='activités'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='numéro de téléphone de contact'),
        ),
    ]
