# Generated by Django 5.1.4 on 2025-01-10 15:59

import data.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0114_alter_company_activities_alter_company_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=data.fields.EnrichedRichTextField(blank=True, null=True, verbose_name='contenu'),
        ),
    ]
