# Generated by Django 5.1.4 on 2025-01-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0115_alter_blogpost_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='category',
            field=models.CharField(choices=[('AGE', 'âge'), ('MEDICAL', 'conditions médicales spécifiques'), ('PREGNANCY', 'grossesse et allaitement'), ('MEDICAMENTS', 'interactions médicamenteuses'), ('OTHER', 'autres')], default='OTHER', max_length=50, verbose_name='categorie'),
        ),
        migrations.AddField(
            model_name='condition',
            name='max_age',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='condition',
            name='min_age',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='historicalcondition',
            name='category',
            field=models.CharField(choices=[('AGE', 'âge'), ('MEDICAL', 'conditions médicales spécifiques'), ('PREGNANCY', 'grossesse et allaitement'), ('MEDICAMENTS', 'interactions médicamenteuses'), ('OTHER', 'autres')], default='OTHER', max_length=50, verbose_name='categorie'),
        ),
        migrations.AddField(
            model_name='historicalcondition',
            name='max_age',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='historicalcondition',
            name='min_age',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='historicalpopulation',
            name='category',
            field=models.CharField(choices=[('AGE', 'âge'), ('PREGNANCY', 'grossesse et allaitement'), ('OTHER', 'autres')], default='OTHER', max_length=50, verbose_name='categorie'),
        ),
        migrations.AddField(
            model_name='population',
            name='category',
            field=models.CharField(choices=[('AGE', 'âge'), ('PREGNANCY', 'grossesse et allaitement'), ('OTHER', 'autres')], default='OTHER', max_length=50, verbose_name='categorie'),
        ),
    ]
