# Generated by Django 5.1.4 on 2025-01-17 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0116_condition_category_condition_max_age_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='blogpost',
        #     name='body',
        # ),
    ]
