# Generated by Django 5.1.5 on 2025-01-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0117_remove_blogpost_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='IcaEffetDeclare',
            fields=[
                ('vrsdecl_ident', models.IntegerField(primary_key=True, serialize=False)),
                ('objeff_ident', models.IntegerField()),
                ('vrs_autre_objectif', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ica_effet_declare',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IcaPopulationCibleDeclaree',
            fields=[
                ('vrsdecl_ident', models.IntegerField(primary_key=True, serialize=False)),
                ('popcbl_ident', models.IntegerField()),
                ('vrspcb_popcible_autre', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ica_population_cible_declaree',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IcaPopulationRisqueDeclaree',
            fields=[
                ('vrsdecl_ident', models.IntegerField(primary_key=True, serialize=False)),
                ('poprs_ident', models.IntegerField()),
                ('vrsprs_poprisque_autre', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ica_population_risque_declaree',
                'managed': False,
            },
        ),
    ]
