# Generated by Django 5.1.5 on 2025-01-23 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0116_icaeffetdeclare_icapopulationcibledeclaree_and_more'),
        ('data', '0117_remove_blogpost_body'),
    ]

    operations = [
    ]
