# Generated by Django 5.1.5 on 2025-01-31 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0118_rename_overriden_article_declaration_overridden_article_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IcaEffetDeclare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vrsdecl_ident', models.IntegerField()),
                ('objeff_ident', models.IntegerField()),
                ('vrs_autre_objectif', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ica_effet_declare',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IcaPopulationCibleDeclaree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vrsdecl_ident', models.IntegerField()),
                ('popcbl_ident', models.IntegerField()),
                ('vrspcb_popcible_autre', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ica_population_cible_declaree',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IcaPopulationRisqueDeclaree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vrsdecl_ident', models.IntegerField()),
                ('poprs_ident', models.IntegerField()),
                ('vrsprs_poprisque_autre', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ica_population_risque_declaree',
                'managed': False,
            },
        ),
    ]
