# Generated by Django 5.1.5 on 2025-01-28 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0118_icaeffetdeclare_icapopulationcibledeclaree_and_more'),
        ('data', '0118_rename_overriden_article_declaration_overridden_article_and_more'),
    ]

    operations = [
    ]
