# Generated by Django 5.1.5 on 2025-01-30 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0119_merge_20250128_1101'),
        ('data', '0119_merge_20250128_1417'),
    ]

    operations = [
    ]
