# Generated by Django 5.1.5 on 2025-02-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0120_declaration_teleicare_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmicroorganism',
            name='ca_genus',
            field=models.TextField(blank=True, verbose_name='genre de micro-organisme'),
        ),
        migrations.AlterField(
            model_name='historicalmicroorganism',
            name='ca_species',
            field=models.TextField(blank=True, verbose_name='espèce de micro-organisme'),
        ),
        migrations.AlterField(
            model_name='historicalmicroorganism',
            name='siccrf_genus',
            field=models.TextField(editable=False, verbose_name='genre de micro-organisme (selon la base SICCRF)'),
        ),
        migrations.AlterField(
            model_name='historicalmicroorganism',
            name='siccrf_species',
            field=models.TextField(editable=False, verbose_name='espèce de micro-organisme (selon la base SICCRF)'),
        ),
        migrations.AlterField(
            model_name='microorganism',
            name='ca_genus',
            field=models.TextField(blank=True, verbose_name='genre de micro-organisme'),
        ),
        migrations.AlterField(
            model_name='microorganism',
            name='ca_species',
            field=models.TextField(blank=True, verbose_name='espèce de micro-organisme'),
        ),
        migrations.AlterField(
            model_name='microorganism',
            name='siccrf_genus',
            field=models.TextField(editable=False, verbose_name='genre de micro-organisme (selon la base SICCRF)'),
        ),
        migrations.AlterField(
            model_name='microorganism',
            name='siccrf_species',
            field=models.TextField(editable=False, verbose_name='espèce de micro-organisme (selon la base SICCRF)'),
        ),
    ]
