# Generated by Django 5.1.5 on 2025-02-20 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0121_alter_declaration_calculated_article_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'verbose_name': 'pièce jointe', 'verbose_name_plural': 'pièces jointes'},
        ),
        migrations.AlterModelOptions(
            name='historicalattachment',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical pièce jointe', 'verbose_name_plural': 'historical pièces jointes'},
        ),
    ]
