# Generated by Django 5.1.5 on 2025-02-20 16:04

import data.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0122_alter_attachment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='old_siret',
            field=models.CharField(blank=True, help_text='14 chiffres', null=True, unique=True, validators=[data.validators.validate_siret], verbose_name='n° SIRET dans TeleIcare'),
        ),
        migrations.AddField(
            model_name='company',
            name='old_vat',
            field=models.CharField(blank=True, null=True, unique=True, validators=[data.validators.validate_vat], verbose_name='n° TVA intracommunautaire'),
        ),
    ]
