# Generated by Django 5.1.5 on 2025-02-21 13:53

import data.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0123_company_old_siret_company_old_vat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='old_siret',
            field=models.CharField(help_text='14 chiffres', null=True, unique=True, validators=[data.validators.validate_siret], verbose_name='n° SIRET dans TeleIcare, si différent'),
        ),
        migrations.AlterField(
            model_name='company',
            name='old_vat',
            field=models.CharField(null=True, unique=True, validators=[data.validators.validate_vat], verbose_name='n° TVA intracommunautaire dans TeleIcare, si différent'),
        ),
        migrations.AlterField(
            model_name='company',
            name='siret',
            field=models.CharField(help_text='14 chiffres', null=True, unique=True, validators=[data.validators.validate_siret], verbose_name='n° SIRET'),
        ),
        migrations.AlterField(
            model_name='company',
            name='vat',
            field=models.CharField(null=True, unique=True, validators=[data.validators.validate_vat], verbose_name='n° TVA intracommunautaire'),
        ),
    ]
