# Generated by Django 5.1.5 on 2025-03-05 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0123_company_old_siret_company_old_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='first_declaration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.declaration', verbose_name='La première déclaration autorisée avec cet ingrédient'),
        ),
        migrations.AddField(
            model_name='effect',
            name='first_declaration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.declaration', verbose_name='La première déclaration autorisée avec cet ingrédient'),
        ),
        migrations.AddField(
            model_name='galenicformulation',
            name='first_declaration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.declaration', verbose_name='La première déclaration autorisée avec cet ingrédient'),
        ),
        migrations.AddField(
            model_name='historicalcondition',
            name='first_declaration',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='data.declaration', verbose_name='La première déclaration autorisée avec cet ingrédient'),
        ),
        migrations.AddField(
            model_name='historicaleffect',
            name='first_declaration',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='data.declaration', verbose_name='La première déclaration autorisée avec cet ingrédient'),
        ),
        migrations.AddField(
            model_name='historicalgalenicformulation',
            name='first_declaration',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='data.declaration', verbose_name='La première déclaration autorisée avec cet ingrédient'),
        ),
        migrations.AddField(
            model_name='historicalingredient',
            name='first_declaration',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='data.declaration', verbose_name='La première déclaration autorisée avec cet ingrédient'),
        ),
        migrations.AddField(
            model_name='historicalmicroorganism',
            name='first_declaration',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='data.declaration', verbose_name='La première déclaration autorisée avec cet ingrédient'),
        ),
        migrations.AddField(
            model_name='historicalplant',
            name='first_declaration',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='data.declaration', verbose_name='La première déclaration autorisée avec cet ingrédient'),
        ),
        migrations.AddField(
            model_name='historicalplantfamily',
            name='first_declaration',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='data.declaration', verbose_name='La première déclaration autorisée avec cet ingrédient'),
        ),
        migrations.AddField(
            model_name='historicalplantpart',
            name='first_declaration',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='data.declaration', verbose_name='La première déclaration autorisée avec cet ingrédient'),
        ),
        migrations.AddField(
            model_name='historicalpopulation',
            name='first_declaration',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='data.declaration', verbose_name='La première déclaration autorisée avec cet ingrédient'),
        ),
        migrations.AddField(
            model_name='historicalpreparation',
            name='first_declaration',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='data.declaration', verbose_name='La première déclaration autorisée avec cet ingrédient'),
        ),
        migrations.AddField(
            model_name='historicalsubstance',
            name='first_declaration',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='data.declaration', verbose_name='La première déclaration autorisée avec cet ingrédient'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='first_declaration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.declaration', verbose_name='La première déclaration autorisée avec cet ingrédient'),
        ),
        migrations.AddField(
            model_name='microorganism',
            name='first_declaration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.declaration', verbose_name='La première déclaration autorisée avec cet ingrédient'),
        ),
        migrations.AddField(
            model_name='plant',
            name='first_declaration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.declaration', verbose_name='La première déclaration autorisée avec cet ingrédient'),
        ),
        migrations.AddField(
            model_name='plantfamily',
            name='first_declaration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.declaration', verbose_name='La première déclaration autorisée avec cet ingrédient'),
        ),
        migrations.AddField(
            model_name='plantpart',
            name='first_declaration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.declaration', verbose_name='La première déclaration autorisée avec cet ingrédient'),
        ),
        migrations.AddField(
            model_name='population',
            name='first_declaration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.declaration', verbose_name='La première déclaration autorisée avec cet ingrédient'),
        ),
        migrations.AddField(
            model_name='preparation',
            name='first_declaration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.declaration', verbose_name='La première déclaration autorisée avec cet ingrédient'),
        ),
        migrations.AddField(
            model_name='substance',
            name='first_declaration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.declaration', verbose_name='La première déclaration autorisée avec cet ingrédient'),
        ),
    ]
