# Generated by Django 5.1.5 on 2025-02-27 13:57

from django.db import migrations
from data.etl.teleicare_history.extractor import compute_action

class Migration(migrations.Migration):

    dependencies = [
        ('data', '0123_company_old_siret_company_old_vat'),
    ]

    def set_action(apps, schema_editor):
        """Set action to the first snapshot of declarations from TeleIcare"""
        Declaration = apps.get_model("data", "Declaration")
        Snapshot = apps.get_model("data", "Snapshot")
        IcaVersionDeclaration = apps.get_model("data", "IcaVersionDeclaration")
        for declaration in Declaration.objects.exclude(siccrf_id=None).iterator():
            try:
                snapshot = declaration.snapshots.earliest("creation_date") # filtre le premier snapshot créé pour éviter les snapshots de 'Retrait du marché'
                snapshot.action = compute_action(snapshot.status, 1) # en forçant le nb de version à 1 les actions RESPOND_ éventuelles seront remplacées par des actions SUBMIT
                snapshot.save()
            except Snapshot.DoesNotExist:
                pass
                


    def reverse_set_action(apps, schema_editor):
        pass

    operations = [
        migrations.RunPython(set_action, reverse_set_action),

    ]
