# Generated by Django 5.1.5 on 2025-03-14 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0124_add_action_to_historical_declarations_snapshots'),
        ('data', '0124_historicalmaxquantityperpopulationrelation_and_more'),
    ]

    operations = [
    ]
