# Generated by Django 5.1.7 on 2025-03-14 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0126_icaingredient_icaingredientautre_icamicroorganisme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalingredient',
            name='origin_declaration',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='data.declaration', verbose_name='La déclaration qui a demandé la création de cet ingrédient'),
        ),
        migrations.AddField(
            model_name='historicalmicroorganism',
            name='origin_declaration',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='data.declaration', verbose_name='La déclaration qui a demandé la création de cet ingrédient'),
        ),
        migrations.AddField(
            model_name='historicalplant',
            name='origin_declaration',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='data.declaration', verbose_name='La déclaration qui a demandé la création de cet ingrédient'),
        ),
        migrations.AddField(
            model_name='historicalsubstance',
            name='origin_declaration',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='data.declaration', verbose_name='La déclaration qui a demandé la création de cet ingrédient'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='origin_declaration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.declaration', verbose_name='La déclaration qui a demandé la création de cet ingrédient'),
        ),
        migrations.AddField(
            model_name='microorganism',
            name='origin_declaration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.declaration', verbose_name='La déclaration qui a demandé la création de cet ingrédient'),
        ),
        migrations.AddField(
            model_name='plant',
            name='origin_declaration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.declaration', verbose_name='La déclaration qui a demandé la création de cet ingrédient'),
        ),
        migrations.AddField(
            model_name='substance',
            name='origin_declaration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.declaration', verbose_name='La déclaration qui a demandé la création de cet ingrédient'),
        ),
    ]
