# Generated by Django 5.1.7 on 2025-03-18 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0126_icaingredient_icaingredientautre_icamicroorganisme_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsubstance',
            name='ca_max_quantity',
        ),
        migrations.RemoveField(
            model_name='historicalsubstance',
            name='siccrf_max_quantity',
        ),
        migrations.RemoveField(
            model_name='substance',
            name='ca_max_quantity',
        ),
        migrations.RemoveField(
            model_name='substance',
            name='siccrf_max_quantity',
        ),
    ]
