# Generated by Django 5.1.7 on 2025-03-20 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0127_auto_20250318_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='substance',
            name='max_quantity',)
    ]
