# Generated by Django 5.1.7 on 2025-03-20 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0127_historicalingredient_origin_declaration_and_more'),
        ('data', '0129_remove_historicalsubstance_ca_max_quantity_and_more'),
    ]

    operations = [
    ]
