# Generated by Django 5.1.7 on 2025-03-27 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0130_merge_20250320_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('message', models.TextField(blank=True, verbose_name='problème constaté')),
                ('status', models.TextField(blank=True, choices=[('NEW', 'Nouveau'), ('ONGOING', "En cours d'analyse"), ('DONE', 'Traité')], default='NEW', verbose_name='statut')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='error_reports', to=settings.AUTH_USER_MODEL, verbose_name='auteur')),
                ('ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='error_reports', to='data.ingredient', verbose_name='ingredient concerné')),
                ('microorganism', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='error_reports', to='data.microorganism', verbose_name='microorganisms concerné')),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='error_reports', to='data.plant', verbose_name='plante concernée')),
                ('substance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='error_reports', to='data.substance', verbose_name='substance concernée')),
            ],
            options={
                'verbose_name': "signalement d'erreur",
                'verbose_name_plural': "signalements d'erreur",
                'ordering': ['-creation_date'],
            },
        ),
    ]
