# Generated by Django 5.1.7 on 2025-03-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0130_merge_20250320_1905'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalmaxquantityperpopulationrelation',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical quantité maximum de substance autorisée pour une population cible', 'verbose_name_plural': 'historical quantité maximum de substance autorisée pour une population cibles'},
        ),
        migrations.AlterModelOptions(
            name='maxquantityperpopulationrelation',
            options={'verbose_name': 'quantité maximum de substance autorisée pour une population cible'},
        ),
        migrations.AddConstraint(
            model_name='maxquantityperpopulationrelation',
            constraint=models.UniqueConstraint(fields=('substance', 'population'), name='unique_max_quantity_per_population'),
        ),
    ]
