# Generated by Django 5.1.7 on 2025-03-31 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0131_alter_historicalmaxquantityperpopulationrelation_options_and_more'),
        ('data', '0131_errorreport'),
    ]

    operations = [
    ]
