# Generated by Django 5.1.7 on 2025-03-31 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0132_merge_20250331_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorreport',
            name='microorganism',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='error_reports', to='data.microorganism', verbose_name='micro-organisme concerné'),
        ),
    ]
