# Generated by Django 5.1.7 on 2025-04-15 09:03

from django.db import migrations

from data.models.substance import SubstanceType



class Migration(migrations.Migration):
    dependencies = [
        ("data", "0133_alter_errorreport_microorganism"),
    ]

    def remove_unused_types_from_substance_types(apps, schema_editor):
        Substance = apps.get_model("data", "Substance")
        if 'CARBOHYDRATE' in SubstanceType._member_names_ and 'ENZYME' in SubstanceType._member_names_:
            for substance in Substance.objects.filter(
                substance_types__overlap=[SubstanceType.CARBOHYDRATE, SubstanceType.ENZYME]
            ):
                new_substance_types = list(
                    set(substance.substance_types) - set([SubstanceType.CARBOHYDRATE, SubstanceType.ENZYME])
                )
                substance.substance_types = new_substance_types
                substance.save()
        else:
            pass

    def reverse_remove_unused_types_from_substance_types(apps, schema_editor):
        pass

    operations = [
        migrations.RunPython(
            remove_unused_types_from_substance_types, reverse_remove_unused_types_from_substance_types
        ),
    ]
