# Generated by Django 5.1.7 on 2025-04-18 14:31

import data.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0134_remove_useless_substance_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalEtablissementToCompanyRelation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('siccrf_id', models.IntegerField(blank=True, db_index=True, editable=False, null=True, verbose_name='etab_ident dans le modèle IcaEtablissement SICCRF')),
                ('old_siret', models.CharField(blank=True, db_index=True, help_text='14 chiffres', null=True, validators=[data.validators.validate_siret], verbose_name='n° SIRET dans TeleIcare, si différent')),
                ('old_vat', models.CharField(blank=True, db_index=True, null=True, validators=[data.validators.validate_vat], verbose_name='n° TVA intracommunautaire dans TeleIcare, si différent')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='data.company')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "historical Anciens n° SIRET et n° TVA intracommunautaire, relation avec table d'entreprises TeleIcare et les entreprises Compl'Alim",
                'verbose_name_plural': "historical Anciens n° SIRET et n° TVA intracommunautaire, relation avec table d'entreprises TeleIcare et les entreprises Compl'Alims",
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='EtablissementToCompanyRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siccrf_id', models.IntegerField(blank=True, db_index=True, editable=False, null=True, unique=True, verbose_name='etab_ident dans le modèle IcaEtablissement SICCRF')),
                ('old_siret', models.CharField(blank=True, help_text='14 chiffres', null=True, unique=True, validators=[data.validators.validate_siret], verbose_name='n° SIRET dans TeleIcare, si différent')),
                ('old_vat', models.CharField(blank=True, null=True, unique=True, validators=[data.validators.validate_vat], verbose_name='n° TVA intracommunautaire dans TeleIcare, si différent')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.company')),
            ],
            options={
                'verbose_name': "Anciens n° SIRET et n° TVA intracommunautaire, relation avec table d'entreprises TeleIcare et les entreprises Compl'Alim",
                'constraints': [models.UniqueConstraint(fields=('company', 'siccrf_id'), name='unique_link')],
            },
        ),
    ]
