# Generated by Django 5.1.7 on 2025-04-18 07:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0136_fill_substance_type_with_teleicare_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substance',
            name='substance_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(1, 'Vitamine'), (2, 'Minéral'), (3, 'Métabolite secondaire de plante'), (4, 'Substance active à but nutritionnel ou physiologique')]), default=list, size=None, verbose_name='type(s) de la substance'),
        ),
    ]
