# Generated by Django 5.1.7 on 2025-04-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0137_alter_substance_substance_types'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='substanceunit',
            options={'verbose_name': 'unité'},
        ),
        migrations.AlterField(
            model_name='substanceunit',
            name='name',
            field=models.CharField(max_length=3, unique=True, verbose_name='unité'),
        ),
    ]
