# Generated by Django 5.1.7 on 2025-04-23 16:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0138_historicaletablissementtocompanyrelation_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='etablissementtocompanyrelation',
            name='unique_link',
        ),
        migrations.RemoveField(
            model_name='company',
            name='matched',
        ),
        migrations.RemoveField(
            model_name='company',
            name='old_siret',
        ),
        migrations.RemoveField(
            model_name='company',
            name='old_vat',
        ),
        migrations.RemoveField(
            model_name='company',
            name='siccrf_id',
        ),
        migrations.AddField(
            model_name='company',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='modification_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='etablissementtocompanyrelation',
            name='siccrf_registration_date',
            field=models.DateField(editable=False, null=True, verbose_name="date d'adhésion à la plateforme TeleIcare"),
        ),
    ]
