# Generated by Django 5.1.7 on 2025-04-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0138_alter_substanceunit_options_alter_substanceunit_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalingredient',
            name='history_public_change_reason',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Raison de changement (visibilité publique)'),
        ),
        migrations.AddField(
            model_name='historicalmicroorganism',
            name='history_public_change_reason',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Raison de changement (visibilité publique)'),
        ),
        migrations.AddField(
            model_name='historicalplant',
            name='history_public_change_reason',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Raison de changement (visibilité publique)'),
        ),
        migrations.AddField(
            model_name='historicalsubstance',
            name='history_public_change_reason',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Raison de changement (visibilité publique)'),
        ),
    ]
