# Generated by Django 5.1.7 on 2025-04-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0138_historicaletablissementtocompanyrelation_and_more'),
    ]

    def fill_ca_registration_date(apps, schema_editor):
        Company = apps.get_model("data", "Company")
        Declaration = apps.get_model("data", "Declaration")
        for company in Company.objects.all():
            #TODO : récupérer plutôt de l'historique
            company.ca_registration_date = Declaration.object.filter(company_id=company.id).earliest("creation_date").creation_date
            company.save()

    def reverse_fill_ca_registration_date(apps, schema_editor):
        pass


    def fill_siccrf_registration_date(apps, schema_editor):
        Company = apps.get_model("data", "Company")
        IcaEtablissement = apps.get_model("data", "IcaEtablissement")
        EtablissementToCompanyRelation = apps.get_model("data", "EtablissementToCompanyRelation")
        for company in Company.objects.exclude(siccrf_id=None):
            relation = EtablissementToCompanyRelation(
                company=company, siccrf_id=company.siccrf_id, old_vat=company.old_vat, old_siret=company.old_siret
            )
            relation.save()

    def reverse_fill_siccrf_registration_date(apps, schema_editor):
        pass

    operations = [
        migrations.RemoveConstraint(
            model_name='etablissementtocompanyrelation',
            name='unique_link',
        ),
        migrations.RemoveField(
            model_name='company',
            name='matched',
        ),
        migrations.RemoveField(
            model_name='company',
            name='old_siret',
        ),
        migrations.RemoveField(
            model_name='company',
            name='old_vat',
        ),
        migrations.RemoveField(
            model_name='company',
            name='siccrf_id',
        ),
        migrations.AddField(
            model_name='company',
            name='ca_registration_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='etablissementtocompanyrelation',
            name='siccrf_registration_date',
            field=models.DateField(editable=False, null=True, verbose_name="date d'adhésion à la plateforme TeleIcare"),
        ),
        migrations.AddField(
            model_name='historicaletablissementtocompanyrelation',
            name='siccrf_registration_date',
            field=models.DateField(editable=False, null=True, verbose_name="date d'adhésion à la plateforme TeleIcare"),
        ),
        migrations.RunPython(fill_ca_registration_date, reverse_fill_ca_registration_date),
        migrations.RunPython(fill_siccrf_registration_date, reverse_fill_siccrf_registration_date),

    ]
