# Generated by Django 5.1.7 on 2025-04-23 15:15

from django.db import migrations

from data.behaviours.time_stampable import suppress_autotime


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0139_remove_etablissementtocompanyrelation_unique_link_and_more"),
    ]

    def fill_company_creation_date(apps, schema_editor):
        Company = apps.get_model("data", "Company")
        User = apps.get_model("data", "User")
        for company in Company.objects.all():
            # la company_creation_date correspond à la date d'adhésion du gestionnaire
            try:
                company.creation_date = (company.supervisors.earliest("date_joined").date_joined)
                with suppress_autotime(company, ["creation_date"]):
                    company.save()
            except User.DoesNotExist:
                pass

    def reverse_fill_company_creation_date(apps, schema_editor):
        pass

    operations = [
        migrations.RunPython(fill_company_creation_date, reverse_fill_company_creation_date),
    ]
