# Generated by Django 5.1.7 on 2025-04-23 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0139_remove_etablissementtocompanyrelation_unique_link_and_more'),
    ]

    def fill_ca_registration_date(apps, schema_editor):
        Company = apps.get_model("data", "Company")
        Declaration = apps.get_model("data", "Declaration")
        for company in Company.objects.all():
            # la ca_registration_date correspond à la date de création de la première déclaration
            company.ca_registration_date = Declaration.objects.filter(company_id=company.id).earliest("creation_date").creation_date
            company.save()

    def reverse_fill_ca_registration_date(apps, schema_editor):
        pass

    def fill_siccrf_registration_date(apps, schema_editor):
        IcaEtablissement = apps.get_model("data", "IcaEtablissement")
        EtablissementToCompanyRelation = apps.get_model("data", "EtablissementToCompanyRelation")
        for relation in EtablissementToCompanyRelation.objects.all():
            IcaEtablissement.objects.get(etab_ident=relation.siccrf_id)
            relation.siccrf_registration_date = IcaEtablissement.objects.get(etab_ident=relation.siccrf_id).etab_date_adhesion
            relation.save()

    def reverse_fill_siccrf_registration_date(apps, schema_editor):
        pass

    operations = [
        migrations.RunPython(fill_ca_registration_date, reverse_fill_ca_registration_date),
        migrations.RunPython(fill_siccrf_registration_date, reverse_fill_siccrf_registration_date),
    ]
