# Generated by Django 5.1.7 on 2025-04-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0139_historicalingredient_history_public_change_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalingredient',
            name='history_public_change_reason',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Raison de changement (public)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalmicroorganism',
            name='history_public_change_reason',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Raison de changement (public)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalplant',
            name='history_public_change_reason',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Raison de changement (public)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalsubstance',
            name='history_public_change_reason',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Raison de changement (public)'),
            preserve_default=False,
        ),
    ]
