# Generated by Django 5.1.7 on 2025-04-29 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0138_alter_substanceunit_options_alter_substanceunit_name'),
        ('data', '0140_fill_registration_dates'),
    ]

    operations = [
    ]
