# Generated by Django 5.1.7 on 2025-04-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0142_historicalingredient_history_public_change_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpart',
            name='authorized',
            field=models.BooleanField(default=True, verbose_name='autorisée ?'),
        ),
        migrations.AddField(
            model_name='part',
            name='authorized',
            field=models.BooleanField(default=True, verbose_name='autorisée ?'),
        ),
    ]
