# Generated by Django 5.1.7 on 2025-05-07 12:49
# Modifié manuellement pour éviter ValueError: Modifying GeneratedFields is not supported - the field data.Population.is_obsolete must be removed and re-added with the new definition.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0143_fill_siccrf_registration_date'),
    ]

    operations = [
        # Depuis Django 6 + Postgresql 15, on a besoin de supprimer les GeneratedField qui ne sont plus automatiquement
        # supprimés avec la suppression d'un des champs source
        migrations.RemoveField(
            model_name='population',
            name='is_obsolete',
        ),
        migrations.RemoveField(
            model_name='population',
            name='name',
        ),
        # migrations.RemoveField(
        #     model_name='historicalpopulation',
        #     name='is_obsolete',
        # ),
        # migrations.RemoveField(
        #     model_name='historicalpopulation',
        #     name='name',
        # ),
        ####################################
        migrations.RemoveField(
            model_name='historicalpopulation',
            name='siccrf_id',
        ),
        migrations.RemoveField(
            model_name='historicalpopulation',
            name='siccrf_is_obsolete',
        ),
        migrations.RemoveField(
            model_name='historicalpopulation',
            name='siccrf_name',
        ),
        migrations.RemoveField(
            model_name='population',
            name='siccrf_id',
        ),
        migrations.RemoveField(
            model_name='population',
            name='siccrf_is_obsolete',
        ),
        migrations.RemoveField(
            model_name='population',
            name='siccrf_name',
        ),

        migrations.RenameField(
            model_name="population",
            old_name="ca_is_obsolete",
            new_name="is_obsolete",
        ),
        migrations.RenameField(
            model_name="population",
            old_name="ca_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="historicalpopulation",
            old_name="ca_is_obsolete",
            new_name="is_obsolete",
        ),
        migrations.RenameField(
            model_name="historicalpopulation",
            old_name="ca_name",
            new_name="name",
        ),
    ]
