# Generated by Django 5.1.7 on 2025-05-09 08:55

from django.db import migrations

from data.etl.teleicare_history.extractor import get_CA_corresponding_population

class Migration(migrations.Migration):

    dependencies = [
        ('data', '0144_remove_historicalpopulation_ca_is_obsolete_and_more'),
    ]

    def replace_population_of_teleicare_declarations(apps, schema_editor):
        Declaration = apps.get_model("data", "Declaration")
        for declaration in Declaration.objects.exclude(siccrf_id=None).exclude(populations=None):
            bad_populations = list(declaration.populations.all().values_list("id", flat=True)) # création d'une copy
            declaration.populations.clear()
            declaration.populations.set(get_CA_corresponding_population(bad_populations))

    def reverse_replace_population_of_teleicare_declarations(apps, schema_editor):
        pass

    operations = [
        migrations.RunPython(replace_population_of_teleicare_declarations, reverse_replace_population_of_teleicare_declarations),

    ]
