# Generated by Django 5.1.7 on 2025-05-12 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0144_snapshot_effective_withdrawal_date'),
        ('data', '0145_replace_historic_populations'),
    ]

    operations = [
    ]
