# Generated by Django 5.1.7 on 2025-05-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0146_merge_20250512_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpopulation',
            name='name',
            field=models.TextField(blank=True, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='population',
            name='name',
            field=models.TextField(blank=True, verbose_name='nom'),
        ),
    ]
