# Generated by Django 5.1.7 on 2025-05-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0148_alter_attachment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaration',
            name='teleicare_id',
            field=models.TextField(blank=True, editable=False, null=True, verbose_name='identifiant Teleicare connu par les déclarants et indiqué dans les attestations'),
        ),
        migrations.AlterField(
            model_name='historicaldeclaration',
            name='teleicare_id',
            field=models.TextField(blank=True, editable=False, null=True, verbose_name='identifiant Teleicare connu par les déclarants et indiqué dans les attestations'),
        ),
    ]
