# Generated by Django 5.1.7 on 2025-05-26 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0149_alter_declaration_teleicare_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalingredient',
            old_name='to_be_entered_in_next_decree',
            new_name='siccrf_to_be_entered_in_next_decree',
        ),
        migrations.RenameField(
            model_name='historicalmicroorganism',
            old_name='to_be_entered_in_next_decree',
            new_name='siccrf_to_be_entered_in_next_decree',
        ),
        migrations.RenameField(
            model_name='historicalplant',
            old_name='to_be_entered_in_next_decree',
            new_name='siccrf_to_be_entered_in_next_decree',
        ),
        migrations.RenameField(
            model_name='historicalsubstance',
            old_name='to_be_entered_in_next_decree',
            new_name='siccrf_to_be_entered_in_next_decree',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='to_be_entered_in_next_decree',
            new_name='siccrf_to_be_entered_in_next_decree',
        ),
        migrations.RenameField(
            model_name='microorganism',
            old_name='to_be_entered_in_next_decree',
            new_name='siccrf_to_be_entered_in_next_decree',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='to_be_entered_in_next_decree',
            new_name='siccrf_to_be_entered_in_next_decree',
        ),
        migrations.RenameField(
            model_name='substance',
            old_name='to_be_entered_in_next_decree',
            new_name='siccrf_to_be_entered_in_next_decree',
        ),
    ]
