# Generated by Django 5.1.7 on 2025-05-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0149_alter_declaration_teleicare_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalingredient',
            name='to_be_entered_in_next_decree',
            field=models.BooleanField(default=False, verbose_name="L'ingrédient doit-il être inscrit dans le prochain décret ?"),
        ),
        migrations.AlterField(
            model_name='historicalmicroorganism',
            name='to_be_entered_in_next_decree',
            field=models.BooleanField(default=False, verbose_name="L'ingrédient doit-il être inscrit dans le prochain décret ?"),
        ),
        migrations.AlterField(
            model_name='historicalplant',
            name='to_be_entered_in_next_decree',
            field=models.BooleanField(default=False, verbose_name="L'ingrédient doit-il être inscrit dans le prochain décret ?"),
        ),
        migrations.AlterField(
            model_name='historicalsubstance',
            name='to_be_entered_in_next_decree',
            field=models.BooleanField(default=False, verbose_name="L'ingrédient doit-il être inscrit dans le prochain décret ?"),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='to_be_entered_in_next_decree',
            field=models.BooleanField(default=False, verbose_name="L'ingrédient doit-il être inscrit dans le prochain décret ?"),
        ),
        migrations.AlterField(
            model_name='microorganism',
            name='to_be_entered_in_next_decree',
            field=models.BooleanField(default=False, verbose_name="L'ingrédient doit-il être inscrit dans le prochain décret ?"),
        ),
        migrations.AlterField(
            model_name='plant',
            name='to_be_entered_in_next_decree',
            field=models.BooleanField(default=False, verbose_name="L'ingrédient doit-il être inscrit dans le prochain décret ?"),
        ),
        migrations.AlterField(
            model_name='substance',
            name='to_be_entered_in_next_decree',
            field=models.BooleanField(default=False, verbose_name="L'ingrédient doit-il être inscrit dans le prochain décret ?"),
        ),
    ]
