# Generated by Django 5.1.7 on 2025-05-26 15:27

import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0150_rename_to_be_entered_in_next_decree_historicalingredient_siccrf_to_be_entered_in_next_decree_and_mor'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalingredient',
            name='ca_to_be_entered_in_next_decree',
            field=models.BooleanField(default=None, null=True, verbose_name="L'ingrédient doit-il être inscrit dans le prochain décret ?"),
        ),
        migrations.AddField(
            model_name='historicalmicroorganism',
            name='ca_to_be_entered_in_next_decree',
            field=models.BooleanField(default=None, null=True, verbose_name="L'ingrédient doit-il être inscrit dans le prochain décret ?"),
        ),
        migrations.AddField(
            model_name='historicalplant',
            name='ca_to_be_entered_in_next_decree',
            field=models.BooleanField(default=None, null=True, verbose_name="L'ingrédient doit-il être inscrit dans le prochain décret ?"),
        ),
        migrations.AddField(
            model_name='historicalsubstance',
            name='ca_to_be_entered_in_next_decree',
            field=models.BooleanField(default=None, null=True, verbose_name="L'ingrédient doit-il être inscrit dans le prochain décret ?"),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='ca_to_be_entered_in_next_decree',
            field=models.BooleanField(default=None, null=True, verbose_name="L'ingrédient doit-il être inscrit dans le prochain décret ?"),
        ),
        migrations.AddField(
            model_name='microorganism',
            name='ca_to_be_entered_in_next_decree',
            field=models.BooleanField(default=None, null=True, verbose_name="L'ingrédient doit-il être inscrit dans le prochain décret ?"),
        ),
        migrations.AddField(
            model_name='plant',
            name='ca_to_be_entered_in_next_decree',
            field=models.BooleanField(default=None, null=True, verbose_name="L'ingrédient doit-il être inscrit dans le prochain décret ?"),
        ),
        migrations.AddField(
            model_name='substance',
            name='ca_to_be_entered_in_next_decree',
            field=models.BooleanField(default=None, null=True, verbose_name="L'ingrédient doit-il être inscrit dans le prochain décret ?"),
        ),
        migrations.AlterField(
            model_name='historicalingredient',
            name='siccrf_to_be_entered_in_next_decree',
            field=models.BooleanField(default=False, editable=False, verbose_name="L'ingrédient doit-il être inscrit dans le prochain décret ? (selon SICCRF)"),
        ),
        migrations.AlterField(
            model_name='historicalmicroorganism',
            name='siccrf_to_be_entered_in_next_decree',
            field=models.BooleanField(default=False, editable=False, verbose_name="L'ingrédient doit-il être inscrit dans le prochain décret ? (selon SICCRF)"),
        ),
        migrations.AlterField(
            model_name='historicalplant',
            name='siccrf_to_be_entered_in_next_decree',
            field=models.BooleanField(default=False, editable=False, verbose_name="L'ingrédient doit-il être inscrit dans le prochain décret ? (selon SICCRF)"),
        ),
        migrations.AlterField(
            model_name='historicalsubstance',
            name='siccrf_to_be_entered_in_next_decree',
            field=models.BooleanField(default=False, editable=False, verbose_name="L'ingrédient doit-il être inscrit dans le prochain décret ? (selon SICCRF)"),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='siccrf_to_be_entered_in_next_decree',
            field=models.BooleanField(default=False, editable=False, verbose_name="L'ingrédient doit-il être inscrit dans le prochain décret ? (selon SICCRF)"),
        ),
        migrations.AlterField(
            model_name='microorganism',
            name='siccrf_to_be_entered_in_next_decree',
            field=models.BooleanField(default=False, editable=False, verbose_name="L'ingrédient doit-il être inscrit dans le prochain décret ? (selon SICCRF)"),
        ),
        migrations.AlterField(
            model_name='plant',
            name='siccrf_to_be_entered_in_next_decree',
            field=models.BooleanField(default=False, editable=False, verbose_name="L'ingrédient doit-il être inscrit dans le prochain décret ? (selon SICCRF)"),
        ),
        migrations.AlterField(
            model_name='substance',
            name='siccrf_to_be_entered_in_next_decree',
            field=models.BooleanField(default=False, editable=False, verbose_name="L'ingrédient doit-il être inscrit dans le prochain décret ? (selon SICCRF)"),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='to_be_entered_in_next_decree',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.comparison.Coalesce(models.F('ca_to_be_entered_in_next_decree'), models.F('siccrf_to_be_entered_in_next_decree')), output_field=models.BooleanField(verbose_name="L'ingrédient doit-il être inscrit dans le prochain décret ?")),
        ),
        migrations.AddField(
            model_name='microorganism',
            name='to_be_entered_in_next_decree',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.comparison.Coalesce(models.F('ca_to_be_entered_in_next_decree'), models.F('siccrf_to_be_entered_in_next_decree')), output_field=models.BooleanField(verbose_name="L'ingrédient doit-il être inscrit dans le prochain décret ?")),
        ),
        migrations.AddField(
            model_name='plant',
            name='to_be_entered_in_next_decree',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.comparison.Coalesce(models.F('ca_to_be_entered_in_next_decree'), models.F('siccrf_to_be_entered_in_next_decree')), output_field=models.BooleanField(verbose_name="L'ingrédient doit-il être inscrit dans le prochain décret ?")),
        ),
        migrations.AddField(
            model_name='substance',
            name='to_be_entered_in_next_decree',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.comparison.Coalesce(models.F('ca_to_be_entered_in_next_decree'), models.F('siccrf_to_be_entered_in_next_decree')), output_field=models.BooleanField(verbose_name="L'ingrédient doit-il être inscrit dans le prochain décret ?")),
        ),
    ]
