# Generated by Django 5.1.7 on 2025-06-03 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0150_alter_historicalingredient_to_be_entered_in_next_decree_and_more'),
        ('data', '0150_effective_withdrawal_date'),
    ]

    operations = [
    ]
