# Generated by Django 5.1.7 on 2025-06-05 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0151_alter_historicalingredient_ca_private_comments_and_more'),
        ('data', '0151_merge_20250603_1013'),
    ]

    operations = [
    ]
