# Generated by Django 5.1.7 on 2025-06-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0153_alter_etablissementtocompanyrelation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaredplant',
            name='new_part',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaldeclaredplant',
            name='new_part',
            field=models.BooleanField(default=False),
        ),
    ]
