# Generated by Django 5.1.7 on 2025-06-16 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0153_alter_etablissementtocompanyrelation_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='declaration',
            old_name='teleicare_id',
            new_name='teleicare_declaration_number',
        ),
        migrations.RenameField(
            model_name='historicaldeclaration',
            old_name='teleicare_id',
            new_name='teleicare_declaration_number',
        ),
        migrations.AlterField(
            model_name='declaration',
            name='siccrf_id',
            field=models.IntegerField(blank=True, db_index=True, editable=False, null=True, unique=True, verbose_name='identifiant Teleicare si la déclaration provient de Teleicare, IcaComplementAlimentaire.cplalim_ident'),
        ),
        migrations.AlterField(
            model_name='historicaldeclaration',
            name='siccrf_id',
            field=models.IntegerField(blank=True, db_index=True, editable=False, null=True, verbose_name='identifiant Teleicare si la déclaration provient de Teleicare, IcaComplementAlimentaire.cplalim_ident'),
        ),
    ]
