# Generated by Django 5.1.7 on 2025-06-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0154_remove_declaration_teleicare_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaration',
            name='teleicare_declaration_number',
            field=models.TextField(blank=True, editable=False, null=True, verbose_name='numéro de déclaration Teleicare connu par les déclarants et indiqué dans les attestations'),
        ),
        migrations.AlterField(
            model_name='historicaldeclaration',
            name='teleicare_declaration_number',
            field=models.TextField(blank=True, editable=False, null=True, verbose_name='numéro de déclaration Teleicare connu par les déclarants et indiqué dans les attestations'),
        ),
    ]
