# Generated by Django 5.1.7 on 2025-06-20 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0154_deduplicate_declared_ingredients'),
        ('data', '0155_alter_declaration_teleicare_declaration_number_and_more'),
    ]

    operations = [
    ]
