# Generated by Django 5.1.7 on 2025-06-23 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0156_merge_20250620_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'rôle de contrôle',
                'verbose_name_plural': 'rôles de contrôle',
            },
        ),
    ]
