# Generated by Django 5.1.7 on 2025-06-26 14:49
import sys

from django.conf import settings
from django.db import migrations

import pandas as pd


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0157_controlrole'),
    ]

    def set_attachments_from_teleicare(apps, schema_editor):
        # Cette migration est appliquée manuellement dans le shell django en staging, prod, demo
        teleicare_attachments = pd.read_csv("data/migrations/0158_mappingGUIDFileName.csv", sep=",")
        Attachment = apps.get_model("data", "Attachment")
        Declaration = apps.get_model("data", "Declaration")
        for index, teleicare_attachment in teleicare_attachments.iterrows():
            # teleicare_attachments['path']
            new_attachment = Attachment(
                type=teleicare_attachment["type"],
                declaration=Declaration.objects.get(siccrf_id=teleicare_attachment['cplalim_ident']),
                file=teleicare_attachment['path'],
                name=teleicare_attachment["name"],
            )
            new_attachment.save()

    def reverse_set_attachments_from_teleicare(apps, schema_editor):
        pass

    operations = (
        [migrations.RunPython(set_attachments_from_teleicare, reverse_set_attachments_from_teleicare)]
        if "test" not in sys.argv
        else []
    )
