# Generated by Django 5.1.7 on 2025-07-03 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0158_declaredplant_is_part_request_and_more'),
        ('data', '0158_import_teleicare_attachments'),
    ]

    operations = [
    ]
