# Generated by Django 5.1.7 on 2025-07-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0160_alter_etablissementtocompanyrelation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalingredient',
            name='requires_analysis_report',
            field=models.BooleanField(default=False, verbose_name="L'utilisation de cet ingrédient nécessite un bulletin d'analyse"),
        ),
        migrations.AddField(
            model_name='historicalmicroorganism',
            name='requires_analysis_report',
            field=models.BooleanField(default=False, verbose_name="L'utilisation de cet ingrédient nécessite un bulletin d'analyse"),
        ),
        migrations.AddField(
            model_name='historicalplant',
            name='requires_analysis_report',
            field=models.BooleanField(default=False, verbose_name="L'utilisation de cet ingrédient nécessite un bulletin d'analyse"),
        ),
        migrations.AddField(
            model_name='historicalsubstance',
            name='requires_analysis_report',
            field=models.BooleanField(default=False, verbose_name="L'utilisation de cet ingrédient nécessite un bulletin d'analyse"),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='requires_analysis_report',
            field=models.BooleanField(default=False, verbose_name="L'utilisation de cet ingrédient nécessite un bulletin d'analyse"),
        ),
        migrations.AddField(
            model_name='microorganism',
            name='requires_analysis_report',
            field=models.BooleanField(default=False, verbose_name="L'utilisation de cet ingrédient nécessite un bulletin d'analyse"),
        ),
        migrations.AddField(
            model_name='plant',
            name='requires_analysis_report',
            field=models.BooleanField(default=False, verbose_name="L'utilisation de cet ingrédient nécessite un bulletin d'analyse"),
        ),
        migrations.AddField(
            model_name='substance',
            name='requires_analysis_report',
            field=models.BooleanField(default=False, verbose_name="L'utilisation de cet ingrédient nécessite un bulletin d'analyse"),
        ),
    ]
