# Generated by Django 5.1.7 on 2025-07-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0160_alter_etablissementtocompanyrelation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='new_is_obsolete',
            field=models.BooleanField(default=False, verbose_name='objet obsolète'),
        ),
        migrations.AddField(
            model_name='condition',
            name='new_name',
            field=models.TextField(default='', verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='effect',
            name='new_is_obsolete',
            field=models.BooleanField(default=False, verbose_name='objet obsolète'),
        ),
        migrations.AddField(
            model_name='effect',
            name='new_name',
            field=models.TextField(default='', verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='galenicformulation',
            name='new_is_obsolete',
            field=models.BooleanField(default=False, verbose_name='objet obsolète'),
        ),
        migrations.AddField(
            model_name='galenicformulation',
            name='new_name',
            field=models.TextField(default='', verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='historicalcondition',
            name='new_is_obsolete',
            field=models.BooleanField(default=False, verbose_name='objet obsolète'),
        ),
        migrations.AddField(
            model_name='historicalcondition',
            name='new_name',
            field=models.TextField(default='', verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='historicaleffect',
            name='new_is_obsolete',
            field=models.BooleanField(default=False, verbose_name='objet obsolète'),
        ),
        migrations.AddField(
            model_name='historicaleffect',
            name='new_name',
            field=models.TextField(default='', verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='historicalgalenicformulation',
            name='new_is_obsolete',
            field=models.BooleanField(default=False, verbose_name='objet obsolète'),
        ),
        migrations.AddField(
            model_name='historicalgalenicformulation',
            name='new_name',
            field=models.TextField(default='', verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='historicalingredient',
            name='new_is_obsolete',
            field=models.BooleanField(default=False, verbose_name='objet obsolète'),
        ),
        migrations.AddField(
            model_name='historicalingredient',
            name='new_name',
            field=models.TextField(default='', verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='historicalingredient',
            name='new_private_comments',
            field=models.TextField(blank=True, default='', verbose_name='commentaires privés'),
        ),
        migrations.AddField(
            model_name='historicalingredient',
            name='new_public_comments',
            field=models.TextField(blank=True, default='', verbose_name='commentaires publics'),
        ),
        migrations.AddField(
            model_name='historicalingredient',
            name='new_status',
            field=models.IntegerField(blank=True, choices=[(1, 'autorisé'), (2, 'non autorisé'), (3, 'sans objet')], default=None, null=True, verbose_name="statut de l'ingrédient ou substance"),
        ),
        migrations.AddField(
            model_name='historicalmaxquantityperpopulationrelation',
            name='new_max_quantity',
            field=models.FloatField(blank=True, null=True, verbose_name='quantité maximale autorisée pour la population cible'),
        ),
        migrations.AddField(
            model_name='historicalmicroorganism',
            name='new_genus',
            field=models.TextField(default=None, null=True, verbose_name='genre de micro-organisme'),
        ),
        migrations.AddField(
            model_name='historicalmicroorganism',
            name='new_is_obsolete',
            field=models.BooleanField(default=False, verbose_name='objet obsolète'),
        ),
        migrations.AddField(
            model_name='historicalmicroorganism',
            name='new_private_comments',
            field=models.TextField(blank=True, default='', verbose_name='commentaires privés'),
        ),
        migrations.AddField(
            model_name='historicalmicroorganism',
            name='new_public_comments',
            field=models.TextField(blank=True, default='', verbose_name='commentaires publics'),
        ),
        migrations.AddField(
            model_name='historicalmicroorganism',
            name='new_species',
            field=models.TextField(default=None, null=True, verbose_name='espèce de micro-organisme'),
        ),
        migrations.AddField(
            model_name='historicalmicroorganism',
            name='new_status',
            field=models.IntegerField(blank=True, choices=[(1, 'autorisé'), (2, 'non autorisé'), (3, 'sans objet')], default=None, null=True, verbose_name="statut de l'ingrédient ou substance"),
        ),
        migrations.AddField(
            model_name='historicalpart',
            name='new_is_useful',
            field=models.BooleanField(default=False, null=True, verbose_name='🍵 utile ?'),
        ),
        migrations.AddField(
            model_name='historicalpart',
            name='new_must_be_monitored',
            field=models.BooleanField(default=False, null=True, verbose_name='⚠️ à surveiller ?'),
        ),
        # la migration permet aussi le remplacement du champ BigInteger family_by_id par un simple champ ForeignKey
        migrations.AddField(
            model_name='historicalplant',
            name='new_family',
            field=models.ForeignKey(
                null=True,
                on_delete=models.deletion.SET_NULL,
                to="data.plantfamily",
                verbose_name="famille de plante",
            ),
        ),
        migrations.AddField(
            model_name='historicalplant',
            name='new_is_obsolete',
            field=models.BooleanField(default=False, verbose_name='objet obsolète'),
        ),
        migrations.AddField(
            model_name='historicalplant',
            name='new_name',
            field=models.TextField(default='', verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='historicalplant',
            name='new_private_comments',
            field=models.TextField(blank=True, default='', verbose_name='commentaires privés'),
        ),
        migrations.AddField(
            model_name='historicalplant',
            name='new_public_comments',
            field=models.TextField(blank=True, default='', verbose_name='commentaires publics'),
        ),
        migrations.AddField(
            model_name='historicalplant',
            name='new_status',
            field=models.IntegerField(blank=True, choices=[(1, 'autorisé'), (2, 'non autorisé'), (3, 'sans objet')], default=None, null=True, verbose_name="statut de l'ingrédient ou substance"),
        ),
        migrations.AddField(
            model_name='historicalplantfamily',
            name='new_is_obsolete',
            field=models.BooleanField(default=False, verbose_name='objet obsolète'),
        ),
        migrations.AddField(
            model_name='historicalplantfamily',
            name='new_name',
            field=models.TextField(default='', verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='historicalplantpart',
            name='new_is_obsolete',
            field=models.BooleanField(default=False, verbose_name='objet obsolète'),
        ),
        migrations.AddField(
            model_name='historicalplantpart',
            name='new_name',
            field=models.TextField(default='', verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='historicalpreparation',
            name='new_is_obsolete',
            field=models.BooleanField(default=False, verbose_name='objet obsolète'),
        ),
        migrations.AddField(
            model_name='historicalpreparation',
            name='new_name',
            field=models.TextField(default='', verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='historicalsubstance',
            name='new_cas_number',
            field=models.CharField(blank=True, max_length=10, verbose_name='numéro CAS'),
        ),
        migrations.AddField(
            model_name='historicalsubstance',
            name='new_einec_number',
            field=models.CharField(blank=True, max_length=7, verbose_name='numéro EINECS'),
        ),
        migrations.AddField(
            model_name='historicalsubstance',
            name='new_is_obsolete',
            field=models.BooleanField(default=False, verbose_name='objet obsolète'),
        ),
        migrations.AddField(
            model_name='historicalsubstance',
            name='new_must_specify_quantity',
            field=models.BooleanField(default=False, verbose_name='spécification de quantité obligatoire'),
        ),
        migrations.AddField(
            model_name='historicalsubstance',
            name='new_name',
            field=models.TextField(default='', verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='historicalsubstance',
            name='new_nutritional_reference',
            field=models.FloatField(blank=True, null=True, verbose_name='apport nutritionnel conseillé'),
        ),
        migrations.AddField(
            model_name='historicalsubstance',
            name='new_private_comments',
            field=models.TextField(blank=True, default='', verbose_name='commentaires privés'),
        ),
        migrations.AddField(
            model_name='historicalsubstance',
            name='new_public_comments',
            field=models.TextField(blank=True, default='', verbose_name='commentaires publics'),
        ),
        migrations.AddField(
            model_name='historicalsubstance',
            name='new_source',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalsubstance',
            name='new_status',
            field=models.IntegerField(blank=True, choices=[(1, 'autorisé'), (2, 'non autorisé'), (3, 'sans objet')], default=None, null=True, verbose_name="statut de l'ingrédient ou substance"),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='new_is_obsolete',
            field=models.BooleanField(default=False, verbose_name='objet obsolète'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='new_name',
            field=models.TextField(default='', verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='new_private_comments',
            field=models.TextField(blank=True, default='', verbose_name='commentaires privés'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='new_public_comments',
            field=models.TextField(blank=True, default='', verbose_name='commentaires publics'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='new_status',
            field=models.IntegerField(blank=True, choices=[(1, 'autorisé'), (2, 'non autorisé'), (3, 'sans objet')], default=None, null=True, verbose_name="statut de l'ingrédient ou substance"),
        ),
        migrations.AddField(
            model_name='maxquantityperpopulationrelation',
            name='new_max_quantity',
            field=models.FloatField(blank=True, null=True, verbose_name='quantité maximale autorisée pour la population cible'),
        ),
        migrations.AddField(
            model_name='microorganism',
            name='new_genus',
            field=models.TextField(default=None, null=True, verbose_name='genre de micro-organisme'),
        ),
        migrations.AddField(
            model_name='microorganism',
            name='new_is_obsolete',
            field=models.BooleanField(default=False, verbose_name='objet obsolète'),
        ),
        migrations.AddField(
            model_name='microorganism',
            name='new_private_comments',
            field=models.TextField(blank=True, default='', verbose_name='commentaires privés'),
        ),
        migrations.AddField(
            model_name='microorganism',
            name='new_public_comments',
            field=models.TextField(blank=True, default='', verbose_name='commentaires publics'),
        ),
        migrations.AddField(
            model_name='microorganism',
            name='new_species',
            field=models.TextField(default=None, null=True, verbose_name='espèce de micro-organisme'),
        ),
        migrations.AddField(
            model_name='microorganism',
            name='new_status',
            field=models.IntegerField(blank=True, choices=[(1, 'autorisé'), (2, 'non autorisé'), (3, 'sans objet')], default=None, null=True, verbose_name="statut de l'ingrédient ou substance"),
        ),
        migrations.AddField(
            model_name='part',
            name='new_is_useful',
            field=models.BooleanField(default=False, null=True, verbose_name='🍵 utile ?'),
        ),
        migrations.AddField(
            model_name='part',
            name='new_must_be_monitored',
            field=models.BooleanField(default=False, null=True, verbose_name='⚠️ à surveiller ?'),
        ),
        migrations.AddField(
            model_name='plant',
            name='new_family',
            field=models.ForeignKey(
                null=True,
                on_delete=models.deletion.SET_NULL,
                to="data.plantfamily",
                verbose_name="famille de plante",
            ),
        ),
        migrations.AddField(
            model_name='plant',
            name='new_is_obsolete',
            field=models.BooleanField(default=False, verbose_name='objet obsolète'),
        ),
        migrations.AddField(
            model_name='plant',
            name='new_name',
            field=models.TextField(default='', verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='plant',
            name='new_private_comments',
            field=models.TextField(blank=True, default='', verbose_name='commentaires privés'),
        ),
        migrations.AddField(
            model_name='plant',
            name='new_public_comments',
            field=models.TextField(blank=True, default='', verbose_name='commentaires publics'),
        ),
        migrations.AddField(
            model_name='plant',
            name='new_status',
            field=models.IntegerField(blank=True, choices=[(1, 'autorisé'), (2, 'non autorisé'), (3, 'sans objet')], default=None, null=True, verbose_name="statut de l'ingrédient ou substance"),
        ),
        migrations.AddField(
            model_name='plantfamily',
            name='new_is_obsolete',
            field=models.BooleanField(default=False, verbose_name='objet obsolète'),
        ),
        migrations.AddField(
            model_name='plantfamily',
            name='new_name',
            field=models.TextField(default='', verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='plantpart',
            name='new_is_obsolete',
            field=models.BooleanField(default=False, verbose_name='objet obsolète'),
        ),
        migrations.AddField(
            model_name='plantpart',
            name='new_name',
            field=models.TextField(default='', verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='preparation',
            name='new_is_obsolete',
            field=models.BooleanField(default=False, verbose_name='objet obsolète'),
        ),
        migrations.AddField(
            model_name='preparation',
            name='new_name',
            field=models.TextField(default='', verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='substance',
            name='new_cas_number',
            field=models.CharField(blank=True, max_length=10, verbose_name='numéro CAS'),
        ),
        migrations.AddField(
            model_name='substance',
            name='new_einec_number',
            field=models.CharField(blank=True, max_length=7, verbose_name='numéro EINECS'),
        ),
        migrations.AddField(
            model_name='substance',
            name='new_is_obsolete',
            field=models.BooleanField(default=False, verbose_name='objet obsolète'),
        ),
        migrations.AddField(
            model_name='substance',
            name='new_must_specify_quantity',
            field=models.BooleanField(default=False, verbose_name='spécification de quantité obligatoire'),
        ),
        migrations.AddField(
            model_name='substance',
            name='new_name',
            field=models.TextField(default='', verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='substance',
            name='new_nutritional_reference',
            field=models.FloatField(blank=True, null=True, verbose_name='apport nutritionnel conseillé'),
        ),
        migrations.AddField(
            model_name='substance',
            name='new_private_comments',
            field=models.TextField(blank=True, default='', verbose_name='commentaires privés'),
        ),
        migrations.AddField(
            model_name='substance',
            name='new_public_comments',
            field=models.TextField(blank=True, default='', verbose_name='commentaires publics'),
        ),
        migrations.AddField(
            model_name='substance',
            name='new_source',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='substance',
            name='new_status',
            field=models.IntegerField(blank=True, choices=[(1, 'autorisé'), (2, 'non autorisé'), (3, 'sans objet')], default=None, null=True, verbose_name="statut de l'ingrédient ou substance"),
        ),
        # Ces changements permettent que la migration 163 soit réversible (mais doivent être commentés lors du revert de 161)
        migrations.AlterField(
            model_name='substance',
            name='siccrf_name',
            field=models.TextField(editable=False, verbose_name="nom SICCRF", null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalsubstance',
            name='siccrf_name',
            field=models.TextField(editable=False, verbose_name="nom SICCRF", null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='microorganism',
            name='siccrf_species',
            field=models.TextField(verbose_name="espèce de micro-organisme (selon la base SICCRF)", null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalmicroorganism',
            name='siccrf_species',
            field=models.TextField(verbose_name="espèce de micro-organisme (selon la base SICCRF)", null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='microorganism',
            name='siccrf_genus',
            field=models.TextField(verbose_name="genre de micro-organisme (selon la base SICCRF)", null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalmicroorganism',
            name='siccrf_genus',
            field=models.TextField(verbose_name="genre de micro-organisme (selon la base SICCRF)", null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='microorganism',
            name='ca_species',
            field=models.TextField(verbose_name="espèce de micro-organisme", null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalmicroorganism',
            name='ca_species',
            field=models.TextField(verbose_name="espèce de micro-organisme", null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='microorganism',
            name='ca_genus',
            field=models.TextField(verbose_name="genre de micro-organisme", null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalmicroorganism',
            name='ca_genus',
            field=models.TextField(verbose_name="genre de micro-organisme", null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plant',
            name='siccrf_name',
            field=models.TextField(editable=False, verbose_name="nom SICCRF", null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalplant',
            name='siccrf_name',
            field=models.TextField(editable=False, verbose_name="nom SICCRF", null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='siccrf_name',
            field=models.TextField(editable=False, verbose_name="nom SICCRF", null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalingredient',
            name='siccrf_name',
            field=models.TextField(editable=False, verbose_name="nom SICCRF", null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='preparation',
            name='siccrf_name',
            field=models.TextField(editable=False, verbose_name="nom SICCRF", null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalpreparation',
            name='siccrf_name',
            field=models.TextField(editable=False, verbose_name="nom SICCRF", null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='galenicformulation',
            name='siccrf_name',
            field=models.TextField(editable=False, verbose_name="nom SICCRF", null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalgalenicformulation',
            name='siccrf_name',
            field=models.TextField(editable=False, verbose_name="nom SICCRF", null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='effect',
            name='siccrf_name',
            field=models.TextField(editable=False, verbose_name="nom SICCRF", null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicaleffect',
            name='siccrf_name',
            field=models.TextField(editable=False, verbose_name="nom SICCRF", null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='condition',
            name='siccrf_name',
            field=models.TextField(editable=False, verbose_name="nom SICCRF", null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalcondition',
            name='siccrf_name',
            field=models.TextField(editable=False, verbose_name="nom SICCRF", null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plantpart',
            name='siccrf_name',
            field=models.TextField(editable=False, verbose_name="nom SICCRF", null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalplantpart',
            name='siccrf_name',
            field=models.TextField(editable=False, verbose_name="nom SICCRF", null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plantfamily',
            name='siccrf_name',
            field=models.TextField(editable=False, verbose_name="nom SICCRF", null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalplantfamily',
            name='siccrf_name',
            field=models.TextField(editable=False, verbose_name="nom SICCRF", null=True),
            preserve_default=False,
        ),
    ]
