# Generated by Django 5.1.7 on 2025-07-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0160_alter_etablissementtocompanyrelation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='new_is_obsolete',
            field=models.BooleanField(default=False, verbose_name='objet obsolète'),
        ),
        migrations.AddField(
            model_name='condition',
            name='new_name',
            field=models.TextField(default='', verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='effect',
            name='new_is_obsolete',
            field=models.BooleanField(default=False, verbose_name='objet obsolète'),
        ),
        migrations.AddField(
            model_name='effect',
            name='new_name',
            field=models.TextField(default='', verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='galenicformulation',
            name='new_is_obsolete',
            field=models.BooleanField(default=False, verbose_name='objet obsolète'),
        ),
        migrations.AddField(
            model_name='galenicformulation',
            name='new_name',
            field=models.TextField(default='', verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='historicalcondition',
            name='new_is_obsolete',
            field=models.BooleanField(default=False, verbose_name='objet obsolète'),
        ),
        migrations.AddField(
            model_name='historicalcondition',
            name='new_name',
            field=models.TextField(default='', verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='historicaleffect',
            name='new_is_obsolete',
            field=models.BooleanField(default=False, verbose_name='objet obsolète'),
        ),
        migrations.AddField(
            model_name='historicaleffect',
            name='new_name',
            field=models.TextField(default='', verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='historicalgalenicformulation',
            name='new_is_obsolete',
            field=models.BooleanField(default=False, verbose_name='objet obsolète'),
        ),
        migrations.AddField(
            model_name='historicalgalenicformulation',
            name='new_name',
            field=models.TextField(default='', verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='historicalingredient',
            name='new_is_obsolete',
            field=models.BooleanField(default=False, verbose_name='objet obsolète'),
        ),
        migrations.AddField(
            model_name='historicalingredient',
            name='new_name',
            field=models.TextField(default='', verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='historicalingredient',
            name='new_private_comments',
            field=models.TextField(blank=True, default='', verbose_name='commentaires privés'),
        ),
        migrations.AddField(
            model_name='historicalingredient',
            name='new_public_comments',
            field=models.TextField(blank=True, default='', verbose_name='commentaires publics'),
        ),
        migrations.AddField(
            model_name='historicalingredient',
            name='new_status',
            field=models.IntegerField(blank=True, choices=[(1, 'autorisé'), (2, 'non autorisé'), (3, 'sans objet')], default=None, null=True, verbose_name="statut de l'ingrédient ou substance"),
        ),
        migrations.AddField(
            model_name='historicalmaxquantityperpopulationrelation',
            name='new_max_quantity',
            field=models.FloatField(blank=True, null=True, verbose_name='quantité maximale autorisée pour la population cible'),
        ),
        migrations.AddField(
            model_name='historicalmicroorganism',
            name='new_genus',
            field=models.TextField(default=None, null=True, verbose_name='genre de micro-organisme'),
        ),
        migrations.AddField(
            model_name='historicalmicroorganism',
            name='new_is_obsolete',
            field=models.BooleanField(default=False, verbose_name='objet obsolète'),
        ),
        migrations.AddField(
            model_name='historicalmicroorganism',
            name='new_name',
            field=models.TextField(default='', verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='historicalmicroorganism',
            name='new_private_comments',
            field=models.TextField(blank=True, default='', verbose_name='commentaires privés'),
        ),
        migrations.AddField(
            model_name='historicalmicroorganism',
            name='new_public_comments',
            field=models.TextField(blank=True, default='', verbose_name='commentaires publics'),
        ),
        migrations.AddField(
            model_name='historicalmicroorganism',
            name='new_species',
            field=models.TextField(default=None, null=True, verbose_name='espèce de micro-organisme'),
        ),
        migrations.AddField(
            model_name='historicalmicroorganism',
            name='new_status',
            field=models.IntegerField(blank=True, choices=[(1, 'autorisé'), (2, 'non autorisé'), (3, 'sans objet')], default=None, null=True, verbose_name="statut de l'ingrédient ou substance"),
        ),
        migrations.AddField(
            model_name='historicalpart',
            name='new_is_useful',
            field=models.BooleanField(default=None, null=True, verbose_name='🍵 utile ?'),
        ),
        migrations.AddField(
            model_name='historicalpart',
            name='new_must_be_monitored',
            field=models.BooleanField(default=None, null=True, verbose_name='⚠️ à surveiller ?'),
        ),
        migrations.AddField(
            model_name='historicalplant',
            name='new_family_by_id',
            field=models.BigIntegerField(default=None, null=True, verbose_name='famille de plante'),
        ),
        migrations.AddField(
            model_name='historicalplant',
            name='new_is_obsolete',
            field=models.BooleanField(default=False, verbose_name='objet obsolète'),
        ),
        migrations.AddField(
            model_name='historicalplant',
            name='new_name',
            field=models.TextField(default='', verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='historicalplant',
            name='new_private_comments',
            field=models.TextField(blank=True, default='', verbose_name='commentaires privés'),
        ),
        migrations.AddField(
            model_name='historicalplant',
            name='new_public_comments',
            field=models.TextField(blank=True, default='', verbose_name='commentaires publics'),
        ),
        migrations.AddField(
            model_name='historicalplant',
            name='new_status',
            field=models.IntegerField(blank=True, choices=[(1, 'autorisé'), (2, 'non autorisé'), (3, 'sans objet')], default=None, null=True, verbose_name="statut de l'ingrédient ou substance"),
        ),
        migrations.AddField(
            model_name='historicalplantfamily',
            name='new_is_obsolete',
            field=models.BooleanField(default=False, verbose_name='objet obsolète'),
        ),
        migrations.AddField(
            model_name='historicalplantfamily',
            name='new_name',
            field=models.TextField(default='', verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='historicalplantpart',
            name='new_is_obsolete',
            field=models.BooleanField(default=False, verbose_name='objet obsolète'),
        ),
        migrations.AddField(
            model_name='historicalplantpart',
            name='new_name',
            field=models.TextField(default='', verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='historicalpreparation',
            name='new_is_obsolete',
            field=models.BooleanField(default=False, verbose_name='objet obsolète'),
        ),
        migrations.AddField(
            model_name='historicalpreparation',
            name='new_name',
            field=models.TextField(default='', verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='historicalsubstance',
            name='new_cas_number',
            field=models.CharField(blank=True, max_length=10, verbose_name='numéro CAS'),
        ),
        migrations.AddField(
            model_name='historicalsubstance',
            name='new_einec_number',
            field=models.CharField(blank=True, max_length=7, verbose_name='numéro EINECS'),
        ),
        migrations.AddField(
            model_name='historicalsubstance',
            name='new_is_obsolete',
            field=models.BooleanField(default=False, verbose_name='objet obsolète'),
        ),
        migrations.AddField(
            model_name='historicalsubstance',
            name='new_must_specify_quantity',
            field=models.BooleanField(default=False, verbose_name='spécification de quantité obligatoire'),
        ),
        migrations.AddField(
            model_name='historicalsubstance',
            name='new_name',
            field=models.TextField(default='', verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='historicalsubstance',
            name='new_nutritional_reference',
            field=models.FloatField(blank=True, null=True, verbose_name='apport nutritionnel conseillé'),
        ),
        migrations.AddField(
            model_name='historicalsubstance',
            name='new_private_comments',
            field=models.TextField(blank=True, default='', verbose_name='commentaires privés'),
        ),
        migrations.AddField(
            model_name='historicalsubstance',
            name='new_public_comments',
            field=models.TextField(blank=True, default='', verbose_name='commentaires publics'),
        ),
        migrations.AddField(
            model_name='historicalsubstance',
            name='new_source',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalsubstance',
            name='new_status',
            field=models.IntegerField(blank=True, choices=[(1, 'autorisé'), (2, 'non autorisé'), (3, 'sans objet')], default=None, null=True, verbose_name="statut de l'ingrédient ou substance"),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='new_is_obsolete',
            field=models.BooleanField(default=False, verbose_name='objet obsolète'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='new_name',
            field=models.TextField(default='', verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='new_private_comments',
            field=models.TextField(blank=True, default='', verbose_name='commentaires privés'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='new_public_comments',
            field=models.TextField(blank=True, default='', verbose_name='commentaires publics'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='new_status',
            field=models.IntegerField(blank=True, choices=[(1, 'autorisé'), (2, 'non autorisé'), (3, 'sans objet')], default=None, null=True, verbose_name="statut de l'ingrédient ou substance"),
        ),
        migrations.AddField(
            model_name='maxquantityperpopulationrelation',
            name='new_max_quantity',
            field=models.FloatField(blank=True, null=True, verbose_name='quantité maximale autorisée pour la population cible'),
        ),
        migrations.AddField(
            model_name='microorganism',
            name='new_genus',
            field=models.TextField(default=None, null=True, verbose_name='genre de micro-organisme'),
        ),
        migrations.AddField(
            model_name='microorganism',
            name='new_is_obsolete',
            field=models.BooleanField(default=False, verbose_name='objet obsolète'),
        ),
        migrations.AddField(
            model_name='microorganism',
            name='new_name',
            field=models.TextField(default='', verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='microorganism',
            name='new_private_comments',
            field=models.TextField(blank=True, default='', verbose_name='commentaires privés'),
        ),
        migrations.AddField(
            model_name='microorganism',
            name='new_public_comments',
            field=models.TextField(blank=True, default='', verbose_name='commentaires publics'),
        ),
        migrations.AddField(
            model_name='microorganism',
            name='new_species',
            field=models.TextField(default=None, null=True, verbose_name='espèce de micro-organisme'),
        ),
        migrations.AddField(
            model_name='microorganism',
            name='new_status',
            field=models.IntegerField(blank=True, choices=[(1, 'autorisé'), (2, 'non autorisé'), (3, 'sans objet')], default=None, null=True, verbose_name="statut de l'ingrédient ou substance"),
        ),
        migrations.AddField(
            model_name='part',
            name='new_is_useful',
            field=models.BooleanField(default=None, null=True, verbose_name='🍵 utile ?'),
        ),
        migrations.AddField(
            model_name='part',
            name='new_must_be_monitored',
            field=models.BooleanField(default=None, null=True, verbose_name='⚠️ à surveiller ?'),
        ),
        migrations.AddField(
            model_name='plant',
            name='new_family_by_id',
            field=models.BigIntegerField(default=None, null=True, verbose_name='famille de plante'),
        ),
        migrations.AddField(
            model_name='plant',
            name='new_is_obsolete',
            field=models.BooleanField(default=False, verbose_name='objet obsolète'),
        ),
        migrations.AddField(
            model_name='plant',
            name='new_name',
            field=models.TextField(default='', verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='plant',
            name='new_private_comments',
            field=models.TextField(blank=True, default='', verbose_name='commentaires privés'),
        ),
        migrations.AddField(
            model_name='plant',
            name='new_public_comments',
            field=models.TextField(blank=True, default='', verbose_name='commentaires publics'),
        ),
        migrations.AddField(
            model_name='plant',
            name='new_status',
            field=models.IntegerField(blank=True, choices=[(1, 'autorisé'), (2, 'non autorisé'), (3, 'sans objet')], default=None, null=True, verbose_name="statut de l'ingrédient ou substance"),
        ),
        migrations.AddField(
            model_name='plantfamily',
            name='new_is_obsolete',
            field=models.BooleanField(default=False, verbose_name='objet obsolète'),
        ),
        migrations.AddField(
            model_name='plantfamily',
            name='new_name',
            field=models.TextField(default='', verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='plantpart',
            name='new_is_obsolete',
            field=models.BooleanField(default=False, verbose_name='objet obsolète'),
        ),
        migrations.AddField(
            model_name='plantpart',
            name='new_name',
            field=models.TextField(default='', verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='preparation',
            name='new_is_obsolete',
            field=models.BooleanField(default=False, verbose_name='objet obsolète'),
        ),
        migrations.AddField(
            model_name='preparation',
            name='new_name',
            field=models.TextField(default='', verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='substance',
            name='new_cas_number',
            field=models.CharField(blank=True, max_length=10, verbose_name='numéro CAS'),
        ),
        migrations.AddField(
            model_name='substance',
            name='new_einec_number',
            field=models.CharField(blank=True, max_length=7, verbose_name='numéro EINECS'),
        ),
        migrations.AddField(
            model_name='substance',
            name='new_is_obsolete',
            field=models.BooleanField(default=False, verbose_name='objet obsolète'),
        ),
        migrations.AddField(
            model_name='substance',
            name='new_must_specify_quantity',
            field=models.BooleanField(default=False, verbose_name='spécification de quantité obligatoire'),
        ),
        migrations.AddField(
            model_name='substance',
            name='new_name',
            field=models.TextField(default='', verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='substance',
            name='new_nutritional_reference',
            field=models.FloatField(blank=True, null=True, verbose_name='apport nutritionnel conseillé'),
        ),
        migrations.AddField(
            model_name='substance',
            name='new_private_comments',
            field=models.TextField(blank=True, default='', verbose_name='commentaires privés'),
        ),
        migrations.AddField(
            model_name='substance',
            name='new_public_comments',
            field=models.TextField(blank=True, default='', verbose_name='commentaires publics'),
        ),
        migrations.AddField(
            model_name='substance',
            name='new_source',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='substance',
            name='new_status',
            field=models.IntegerField(blank=True, choices=[(1, 'autorisé'), (2, 'non autorisé'), (3, 'sans objet')], default=None, null=True, verbose_name="statut de l'ingrédient ou substance"),
        ),
    ]
