# Generated by Django 5.1.7 on 2025-07-08 09:21

import data.models.microorganism
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0164_remove_obsolete_ca_and_siccrf_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalingredient',
            old_name='siccrf_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='siccrf_description',
            new_name='description',
        ),
        migrations.AddField(
            model_name='microorganism',
            name='name',
            field=models.GeneratedField(db_persist=True, expression=data.models.microorganism.ConcatOp(models.F('genus'), models.Value(' '), models.F('species')), output_field=models.TextField(verbose_name='nom')),
        ),
        migrations.AlterField(
            model_name='historicalingredient',
            name='private_comments',
            field=models.TextField(blank=True, verbose_name='commentaires privés'),
        ),
        migrations.AlterField(
            model_name='historicalingredient',
            name='public_comments',
            field=models.TextField(blank=True, verbose_name='commentaires publics'),
        ),
        migrations.AlterField(
            model_name='historicalmicroorganism',
            name='genus',
            field=models.TextField(null=True, verbose_name='genre de micro-organisme'),
        ),
        migrations.AlterField(
            model_name='historicalmicroorganism',
            name='private_comments',
            field=models.TextField(blank=True, verbose_name='commentaires privés'),
        ),
        migrations.AlterField(
            model_name='historicalmicroorganism',
            name='public_comments',
            field=models.TextField(blank=True, verbose_name='commentaires publics'),
        ),
        migrations.AlterField(
            model_name='historicalmicroorganism',
            name='species',
            field=models.TextField(null=True, verbose_name='espèce de micro-organisme'),
        ),
        migrations.AlterField(
            model_name='historicalpart',
            name='is_useful',
            field=models.BooleanField(default=False, verbose_name='🍵 utile ?'),
        ),
        migrations.AlterField(
            model_name='historicalpart',
            name='must_be_monitored',
            field=models.BooleanField(default=False, verbose_name='⚠️ à surveiller ?'),
        ),
        migrations.AlterField(
            model_name='historicalplant',
            name='private_comments',
            field=models.TextField(blank=True, verbose_name='commentaires privés'),
        ),
        migrations.AlterField(
            model_name='historicalplant',
            name='public_comments',
            field=models.TextField(blank=True, verbose_name='commentaires publics'),
        ),
        migrations.AlterField(
            model_name='historicalsubstance',
            name='private_comments',
            field=models.TextField(blank=True, verbose_name='commentaires privés'),
        ),
        migrations.AlterField(
            model_name='historicalsubstance',
            name='public_comments',
            field=models.TextField(blank=True, verbose_name='commentaires publics'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='private_comments',
            field=models.TextField(blank=True, verbose_name='commentaires privés'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='public_comments',
            field=models.TextField(blank=True, verbose_name='commentaires publics'),
        ),
        migrations.AlterField(
            model_name='microorganism',
            name='genus',
            field=models.TextField(null=True, verbose_name='genre de micro-organisme'),
        ),
        migrations.AlterField(
            model_name='microorganism',
            name='private_comments',
            field=models.TextField(blank=True, verbose_name='commentaires privés'),
        ),
        migrations.AlterField(
            model_name='microorganism',
            name='public_comments',
            field=models.TextField(blank=True, verbose_name='commentaires publics'),
        ),
        migrations.AlterField(
            model_name='microorganism',
            name='species',
            field=models.TextField(null=True, verbose_name='espèce de micro-organisme'),
        ),
        migrations.AlterField(
            model_name='part',
            name='is_useful',
            field=models.BooleanField(default=False, verbose_name='🍵 utile ?'),
        ),
        migrations.AlterField(
            model_name='part',
            name='must_be_monitored',
            field=models.BooleanField(default=False, verbose_name='⚠️ à surveiller ?'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='private_comments',
            field=models.TextField(blank=True, verbose_name='commentaires privés'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='public_comments',
            field=models.TextField(blank=True, verbose_name='commentaires publics'),
        ),
        migrations.AlterField(
            model_name='substance',
            name='private_comments',
            field=models.TextField(blank=True, verbose_name='commentaires privés'),
        ),
        migrations.AlterField(
            model_name='substance',
            name='public_comments',
            field=models.TextField(blank=True, verbose_name='commentaires publics'),
        ),
    ]
