# Generated by Django 5.1.7 on 2025-07-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0165_remove_historicalplant_family_by_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalingredient',
            old_name='novel_food',
            new_name='is_novel_food',
        ),
        migrations.RenameField(
            model_name='historicalmicroorganism',
            old_name='novel_food',
            new_name='is_novel_food',
        ),
        migrations.RenameField(
            model_name='historicalplant',
            old_name='novel_food',
            new_name='is_novel_food',
        ),
        migrations.RenameField(
            model_name='historicalsubstance',
            old_name='novel_food',
            new_name='is_novel_food',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='novel_food',
            new_name='is_novel_food',
        ),
        migrations.RenameField(
            model_name='microorganism',
            old_name='novel_food',
            new_name='is_novel_food',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='novel_food',
            new_name='is_novel_food',
        ),
        migrations.RenameField(
            model_name='substance',
            old_name='novel_food',
            new_name='is_novel_food',
        ),
        migrations.AddField(
            model_name='historicalingredient',
            name='warning',
            field=models.TextField(blank=True, editable=False, verbose_name='avertissement'),
        ),
        migrations.AddField(
            model_name='historicalmicroorganism',
            name='warning',
            field=models.TextField(blank=True, editable=False, verbose_name='avertissement'),
        ),
        migrations.AddField(
            model_name='historicalplant',
            name='warning',
            field=models.TextField(blank=True, editable=False, verbose_name='avertissement'),
        ),
        migrations.AddField(
            model_name='historicalsubstance',
            name='warning',
            field=models.TextField(blank=True, editable=False, verbose_name='avertissement'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='warning',
            field=models.TextField(blank=True, editable=False, verbose_name='avertissement'),
        ),
        migrations.AddField(
            model_name='microorganism',
            name='warning',
            field=models.TextField(blank=True, editable=False, verbose_name='avertissement'),
        ),
        migrations.AddField(
            model_name='plant',
            name='warning',
            field=models.TextField(blank=True, editable=False, verbose_name='avertissement'),
        ),
        migrations.AddField(
            model_name='substance',
            name='warning',
            field=models.TextField(blank=True, editable=False, verbose_name='avertissement'),
        ),
    ]
