# Generated by Django 5.1.7 on 2025-07-16 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0165_remove_historicalplant_family_by_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalingredientsubstancerelation',
            name='ca_is_related',
        ),
        migrations.RemoveField(
            model_name='historicalingredientsubstancerelation',
            name='siccrf_is_related',
        ),
        migrations.RemoveField(
            model_name='historicalmicroorganismsubstancerelation',
            name='ca_is_related',
        ),
        migrations.RemoveField(
            model_name='historicalmicroorganismsubstancerelation',
            name='siccrf_is_related',
        ),
        migrations.RemoveField(
            model_name='historicalplantsubstancerelation',
            name='ca_is_related',
        ),
        migrations.RemoveField(
            model_name='historicalplantsubstancerelation',
            name='siccrf_is_related',
        ),
        migrations.RemoveField(
            model_name='ingredientsubstancerelation',
            name='ca_is_related',
        ),
        migrations.RemoveField(
            model_name='ingredientsubstancerelation',
            name='siccrf_is_related',
        ),
        migrations.RemoveField(
            model_name='microorganismsubstancerelation',
            name='ca_is_related',
        ),
        migrations.RemoveField(
            model_name='microorganismsubstancerelation',
            name='siccrf_is_related',
        ),
        migrations.RemoveField(
            model_name='plantsubstancerelation',
            name='ca_is_related',
        ),
        migrations.RemoveField(
            model_name='plantsubstancerelation',
            name='siccrf_is_related',
        ),
    ]
