# Generated by Django 5.1.7 on 2025-07-11 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0166_rename_novel_food_historicalingredient_is_novel_food_and_more'),
    ]

    def set_novel_food(apps, schema_editor):
        Ingredient = apps.get_model("data", "Ingredient")
        # on ne filtre pas les mentions à "novel food" dans les commentaires privés car cela correspond souvent à des doutes
        for ingredient in Ingredient.objects.filter(public_comments__iregex="(novel food|nouvel aliment)",):
            ingredient.is_novel_food = True
            ingredient.save()
        Microorganism = apps.get_model("data", "Microorganism")
        # on ne filtre pas les mentions à "novel food" dans les commentaires privés car cela correspond souvent à des doutes
        for microorganism in Microorganism.objects.filter(public_comments__iregex="(novel food|nouvel aliment)",):
            microorganism.is_novel_food = True
            microorganism.save()
        Plant = apps.get_model("data", "Plant")
        # on ne filtre pas les mentions à "novel food" dans les commentaires privés car cela correspond souvent à des doutes
        for plant in Plant.objects.filter(public_comments__iregex="(novel food|nouvel aliment)",):
            plant.is_novel_food = True
            plant.save()
        Substance = apps.get_model("data", "Substance")
        # on ne filtre pas les mentions à "novel food" dans les commentaires privés car cela correspond souvent à des doutes
        for substance in Substance.objects.filter(public_comments__iregex="(novel food|nouvel aliment)",):
            substance.is_novel_food = True
            substance.save()

    def reverse_set_novel_food(apps, schema_editor):
        pass

    operations = [
        migrations.RunPython(set_novel_food, reverse_set_novel_food),
        migrations.RunPython(set_warning, reverse_set_warning),
    ]
