# Generated by Django 5.1.7 on 2025-07-30 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0166_remove_historicalingredientsubstancerelation_ca_is_related_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalplant',
            name='family',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='data.plantfamily', verbose_name='famille de plante'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plant_set', to='data.plantfamily', verbose_name='famille de plante'),
        ),
    ]
