# Generated by Django 5.1.7 on 2025-08-04 14:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0167_alter_historicalplant_family_alter_plant_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsubstance',
            name='substance_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(1, 'Vitamine'), (2, 'Minéral'), (3, 'Métabolite secondaire de plante'), (4, 'Substance active à but nutritionnel ou physiologique')]), default=list, size=None, verbose_name='type(s) de la substance'),
        ),
    ]
