# Generated by Django 5.1.7 on 2025-08-05 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0161_historicalingredient_requires_analysis_report_and_more'),
        ('data', '0168_historicalsubstance_substance_types'),
    ]

    operations = [
    ]
