# Generated by Django 5.1.7 on 2025-08-27 11:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0169_merge_20250805_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalingredient',
            name='regulatory_resource_links',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, null=True, size=None, verbose_name='Lien(s) vers les ressources reglementaires'),
        ),
        migrations.AddField(
            model_name='historicalmicroorganism',
            name='regulatory_resource_links',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, null=True, size=None, verbose_name='Lien(s) vers les ressources reglementaires'),
        ),
        migrations.AddField(
            model_name='historicalplant',
            name='regulatory_resource_links',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, null=True, size=None, verbose_name='Lien(s) vers les ressources reglementaires'),
        ),
        migrations.AddField(
            model_name='historicalsubstance',
            name='regulatory_resource_links',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, null=True, size=None, verbose_name='Lien(s) vers les ressources reglementaires'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='regulatory_resource_links',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, null=True, size=None, verbose_name='Lien(s) vers les ressources reglementaires'),
        ),
        migrations.AddField(
            model_name='microorganism',
            name='regulatory_resource_links',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, null=True, size=None, verbose_name='Lien(s) vers les ressources reglementaires'),
        ),
        migrations.AddField(
            model_name='plant',
            name='regulatory_resource_links',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, null=True, size=None, verbose_name='Lien(s) vers les ressources reglementaires'),
        ),
        migrations.AddField(
            model_name='substance',
            name='regulatory_resource_links',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, null=True, size=None, verbose_name='Lien(s) vers les ressources reglementaires'),
        ),
    ]
