# Generated by Django 5.1.7 on 2025-08-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0170_historicalingredient_regulatory_resource_links_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaredingredient',
            name='fr_reason',
            field=models.CharField(blank=True, choices=[('TRADITIONAL_USAGE', "Ingrédient bénéficiant d'un historique de consommation selon le catalogue Novel Food ou dont l'utilisation en alimentation humaine est bien établie"), ('NOVEL_FOOD', "L'ingrédient figure sur la liste de l'Union des nouveaux aliments conformément au règlement (UE) 2017/2470"), ('MISSING', "L'ingrédient est autorisé en France mais ne figure pas dans la base de données")], verbose_name="raison de l'ajout manuel"),
        ),
        migrations.AlterField(
            model_name='declaredmicroorganism',
            name='fr_reason',
            field=models.CharField(blank=True, choices=[('TRADITIONAL_USAGE', "Ingrédient bénéficiant d'un historique de consommation selon le catalogue Novel Food ou dont l'utilisation en alimentation humaine est bien établie"), ('NOVEL_FOOD', "L'ingrédient figure sur la liste de l'Union des nouveaux aliments conformément au règlement (UE) 2017/2470"), ('MISSING', "L'ingrédient est autorisé en France mais ne figure pas dans la base de données")], verbose_name="raison de l'ajout manuel"),
        ),
        migrations.AlterField(
            model_name='declaredplant',
            name='fr_reason',
            field=models.CharField(blank=True, choices=[('TRADITIONAL_USAGE', "Ingrédient bénéficiant d'un historique de consommation selon le catalogue Novel Food ou dont l'utilisation en alimentation humaine est bien établie"), ('NOVEL_FOOD', "L'ingrédient figure sur la liste de l'Union des nouveaux aliments conformément au règlement (UE) 2017/2470"), ('MISSING', "L'ingrédient est autorisé en France mais ne figure pas dans la base de données")], verbose_name="raison de l'ajout manuel"),
        ),
        migrations.AlterField(
            model_name='declaredsubstance',
            name='fr_reason',
            field=models.CharField(blank=True, choices=[('TRADITIONAL_USAGE', "Ingrédient bénéficiant d'un historique de consommation selon le catalogue Novel Food ou dont l'utilisation en alimentation humaine est bien établie"), ('NOVEL_FOOD', "L'ingrédient figure sur la liste de l'Union des nouveaux aliments conformément au règlement (UE) 2017/2470"), ('MISSING', "L'ingrédient est autorisé en France mais ne figure pas dans la base de données")], verbose_name="raison de l'ajout manuel"),
        ),
        migrations.AlterField(
            model_name='historicaldeclaredingredient',
            name='fr_reason',
            field=models.CharField(blank=True, choices=[('TRADITIONAL_USAGE', "Ingrédient bénéficiant d'un historique de consommation selon le catalogue Novel Food ou dont l'utilisation en alimentation humaine est bien établie"), ('NOVEL_FOOD', "L'ingrédient figure sur la liste de l'Union des nouveaux aliments conformément au règlement (UE) 2017/2470"), ('MISSING', "L'ingrédient est autorisé en France mais ne figure pas dans la base de données")], verbose_name="raison de l'ajout manuel"),
        ),
        migrations.AlterField(
            model_name='historicaldeclaredmicroorganism',
            name='fr_reason',
            field=models.CharField(blank=True, choices=[('TRADITIONAL_USAGE', "Ingrédient bénéficiant d'un historique de consommation selon le catalogue Novel Food ou dont l'utilisation en alimentation humaine est bien établie"), ('NOVEL_FOOD', "L'ingrédient figure sur la liste de l'Union des nouveaux aliments conformément au règlement (UE) 2017/2470"), ('MISSING', "L'ingrédient est autorisé en France mais ne figure pas dans la base de données")], verbose_name="raison de l'ajout manuel"),
        ),
        migrations.AlterField(
            model_name='historicaldeclaredplant',
            name='fr_reason',
            field=models.CharField(blank=True, choices=[('TRADITIONAL_USAGE', "Ingrédient bénéficiant d'un historique de consommation selon le catalogue Novel Food ou dont l'utilisation en alimentation humaine est bien établie"), ('NOVEL_FOOD', "L'ingrédient figure sur la liste de l'Union des nouveaux aliments conformément au règlement (UE) 2017/2470"), ('MISSING', "L'ingrédient est autorisé en France mais ne figure pas dans la base de données")], verbose_name="raison de l'ajout manuel"),
        ),
        migrations.AlterField(
            model_name='historicaldeclaredsubstance',
            name='fr_reason',
            field=models.CharField(blank=True, choices=[('TRADITIONAL_USAGE', "Ingrédient bénéficiant d'un historique de consommation selon le catalogue Novel Food ou dont l'utilisation en alimentation humaine est bien établie"), ('NOVEL_FOOD', "L'ingrédient figure sur la liste de l'Union des nouveaux aliments conformément au règlement (UE) 2017/2470"), ('MISSING', "L'ingrédient est autorisé en France mais ne figure pas dans la base de données")], verbose_name="raison de l'ajout manuel"),
        ),
    ]
