# Generated by Django 5.1.7 on 2025-09-02 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0171_alter_declaredingredient_fr_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='market_ready_count_cache',
            field=models.IntegerField(blank=True, null=True, verbose_name='cache du nombre de déclarations prêtes pour la commercialisation'),
        ),
        migrations.AddField(
            model_name='company',
            name='market_ready_count_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='dernière mise à jour du cache'),
        ),
        migrations.AddField(
            model_name='historicalcompany',
            name='market_ready_count_cache',
            field=models.IntegerField(blank=True, null=True, verbose_name='cache du nombre de déclarations prêtes pour la commercialisation'),
        ),
        migrations.AddField(
            model_name='historicalcompany',
            name='market_ready_count_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='dernière mise à jour du cache'),
        ),
    ]
