# Generated by Django 5.1.7 on 2025-09-15 14:01

from django.db import migrations
from django.db.models import Q


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0172_company_market_ready_count_cache_and_more"),
    ]

    def fill_analysis_report(apps, schema_editor):
        Ingredient = apps.get_model("data", "Ingredient")
        Plant = apps.get_model("data", "Plant")
        Microorganism = apps.get_model("data", "Microorganism")
        Substance = apps.get_model("data", "Substance")
        for ingredient in Ingredient.objects.exclude(siccrf_id=None).filter(
            Q(public_comments__icontains="bulletin") | Q(private_comments__icontains="bulletin")
        ):
            ingredient.requires_analysis_report = True
            ingredient.save()
        for plant in Plant.objects.exclude(siccrf_id=None).filter(
            Q(public_comments__icontains="bulletin") | Q(private_comments__icontains="bulletin")
        ):
            plant.requires_analysis_report = True
            plant.save()
        for microorganism in Microorganism.objects.exclude(siccrf_id=None).filter(
            Q(public_comments__icontains="bulletin") | Q(private_comments__icontains="bulletin")
        ):
            microorganism.requires_analysis_report = True
            microorganism.save()
        for substance in Substance.objects.exclude(siccrf_id=None).filter(
            Q(public_comments__icontains="bulletin") | Q(private_comments__icontains="bulletin")
        ):
            substance.requires_analysis_report = True
            substance.save()

    def reverse_fill_analysis_report(apps, schema_editor):
        pass

    operations = [
        migrations.RunPython(fill_analysis_report, reverse_fill_analysis_report),
    ]
