# Generated by Django 5.1.7 on 2025-09-25 14:42

import data.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0172_company_market_ready_count_cache_and_more'),
    ]

    def massage_old_cas_number(apps, schema_editor):
        Substance = apps.get_model("data", "Substance")
        for substance in Substance.objects.all():
            if not substance.cas_number:
                substance.cas_number = None
                substance.save()

    def reverse_massage_old_cas_number(apps, schema_editor):
        Substance = apps.get_model("data", "Substance")
        for substance in Substance.objects.all():
            if not substance.cas_number:
                substance.cas_number = ''
                substance.save()

    operations = [
        migrations.AlterField(
            model_name='historicalsubstance',
            name='cas_number',
            field=models.CharField(blank=True, null=True, validators=[data.validators.validate_cas], verbose_name='n° CAS'),
        ),
        migrations.AlterField(
            model_name='substance',
            name='cas_number',
            field=models.CharField(blank=True, null=True, validators=[data.validators.validate_cas], verbose_name='n° CAS'),
        ),
        migrations.RunPython(massage_old_cas_number, reverse_massage_old_cas_number),
    ]
