# Generated by Django 5.1.7 on 2025-09-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0172_company_market_ready_count_cache_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlRoleEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email autorisé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='controlrole',
            name='always_persist',
            field=models.BooleanField(default=False, help_text='Ce rôle ne sera pas retiré lors des synchronisations automatiques avec Grist', verbose_name='toujours maintenir le rôle'),
        ),
    ]
