# Generated by Django 5.1.7 on 2025-09-22 12:59

import data.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0172_company_market_ready_count_cache_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsubstance',
            name='cas_number',
            field=models.CharField(blank=True, db_index=True, validators=[data.validators.validate_cas], verbose_name='n° CAS'),
        ),
        migrations.AlterField(
            model_name='substance',
            name='cas_number',
            field=models.CharField(blank=True, unique=True, validators=[data.validators.validate_cas], verbose_name='n° CAS'),
        ),
    ]
