# Generated by Django 5.1.7 on 2025-09-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0173_fill_analysis_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalsubstance',
            old_name='source',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='substance',
            old_name='source',
            new_name='description',
        ),
        migrations.AddField(
            model_name='historicalingredient',
            name='warning_on_label',
            field=models.TextField(blank=True, verbose_name="mentions d'avertissement devant figurer sur l'étiquette"),
        ),
        migrations.AddField(
            model_name='historicalmicroorganism',
            name='warning_on_label',
            field=models.TextField(blank=True, verbose_name="mentions d'avertissement devant figurer sur l'étiquette"),
        ),
        migrations.AddField(
            model_name='historicalplant',
            name='warning_on_label',
            field=models.TextField(blank=True, verbose_name="mentions d'avertissement devant figurer sur l'étiquette"),
        ),
        migrations.AddField(
            model_name='historicalsubstance',
            name='warning_on_label',
            field=models.TextField(blank=True, verbose_name="mentions d'avertissement devant figurer sur l'étiquette"),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='warning_on_label',
            field=models.TextField(blank=True, verbose_name="mentions d'avertissement devant figurer sur l'étiquette"),
        ),
        migrations.AddField(
            model_name='microorganism',
            name='warning_on_label',
            field=models.TextField(blank=True, verbose_name="mentions d'avertissement devant figurer sur l'étiquette"),
        ),
        migrations.AddField(
            model_name='plant',
            name='warning_on_label',
            field=models.TextField(blank=True, verbose_name="mentions d'avertissement devant figurer sur l'étiquette"),
        ),
        migrations.AddField(
            model_name='substance',
            name='warning_on_label',
            field=models.TextField(blank=True, verbose_name="mentions d'avertissement devant figurer sur l'étiquette"),
        ),
    ]
