# Generated by Django 5.1.7 on 2025-09-26 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0173_fill_analysis_report'),
        ('data', '0174_alter_historicalsubstance_cas_number_and_more'),
    ]

    operations = [
    ]
