# Generated by Django 5.1.7 on 2025-09-26 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0174_alter_historicalsubstance_cas_number_and_more'),
    ]

    def remove_obsolete(apps, schema_editor):
        IngredientSynonym = apps.get_model("data", "IngredientSynonym")
        MicroorganismSynonym = apps.get_model("data", "MicroorganismSynonym")
        PlantSynonym = apps.get_model("data", "PlantSynonym")
        SubstanceSynonym = apps.get_model("data", "SubstanceSynonym")
        for ingr_synonyms in [IngredientSynonym, MicroorganismSynonym, PlantSynonym, SubstanceSynonym]:
            for synonym in ingr_synonyms.objects.all().iterator():
                if synonym.siccrf_is_obsolete:
                    synonym.delete()

    def reverse_remove_obsolete(apps, schema_editor):
        pass

    operations = [
        migrations.RunPython(remove_obsolete, reverse_remove_obsolete),

    ]
