# Generated by Django 5.1.7 on 2025-09-29 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0173_controlroleemail_controlrole_always_persist'),
        ('data', '0176_fill_novel_food_and_warning'),
    ]

    operations = [
    ]
