# Generated by Django 5.1.7 on 2025-09-29 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0177_merge_20250929_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlrole',
            name='always_persist',
            field=models.BooleanField(default=False, help_text='Ce rôle ne sera pas retiré lors des synchronisations automatiques', verbose_name='toujours maintenir le rôle'),
        ),
    ]
