# Generated by Django 5.1.7 on 2025-09-30 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0177_rename_source_historicalsubstance_description_and_more'),
        ('data', '0178_alter_controlrole_always_persist'),
    ]

    operations = [
    ]
