# Generated by Django 5.1.7 on 2025-09-26 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0178_alter_controlrole_always_persist'),
    ]

    def remove_obsolete(apps, schema_editor):
        IngredientSynonym = apps.get_model("data", "IngredientSynonym")
        MicroorganismSynonym = apps.get_model("data", "MicroorganismSynonym")
        PlantSynonym = apps.get_model("data", "PlantSynonym")
        SubstanceSynonym = apps.get_model("data", "SubstanceSynonym")
        for ingr_synonyms in [IngredientSynonym, MicroorganismSynonym, PlantSynonym, SubstanceSynonym]:
            for synonym in ingr_synonyms.objects.all().iterator():
                if synonym.siccrf_is_obsolete:
                    synonym.delete()

    def reverse_remove_obsolete(apps, schema_editor):
        pass

    def remove_duplicates(apps, schema_editor):
        IngredientSynonym = apps.get_model("data", "IngredientSynonym")
        MicroorganismSynonym = apps.get_model("data", "MicroorganismSynonym")
        PlantSynonym = apps.get_model("data", "PlantSynonym")
        SubstanceSynonym = apps.get_model("data", "SubstanceSynonym")
        for synonym_model in [IngredientSynonym, MicroorganismSynonym, PlantSynonym, SubstanceSynonym]:
            duplicates_qs = synonym_model.all().values('standard_name').annotate(total=Count('standard_name')).filter(total__gt=1)
            for duplicate in duplicates_qs:
                objects_to_deduplicate = synonym_model.objects.filter(name=duplicate['name'])
                for i in range(duplicate['total']-1):
                    objects_to_deduplicate[i].delete()

    def reverse_remove_duplicates(apps, schema_editor):
        pass

    operations = [
        migrations.RunPython(remove_obsolete, reverse_remove_obsolete),
        migrations.RunPython(remove_duplicates, reverse_remove_duplicates),

    ]
