# Generated by Django 5.1.7 on 2025-09-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0179_clean_synonyms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalingredientsynonym',
            name='siccrf_is_obsolete',
        ),
        migrations.RemoveField(
            model_name='historicalmicroorganismsynonym',
            name='siccrf_is_obsolete',
        ),
        migrations.RemoveField(
            model_name='historicalplantsynonym',
            name='siccrf_is_obsolete',
        ),
        migrations.RemoveField(
            model_name='historicalsubstancesynonym',
            name='siccrf_is_obsolete',
        ),
        migrations.RemoveField(
            model_name='ingredientsynonym',
            name='siccrf_is_obsolete',
        ),
        migrations.RemoveField(
            model_name='microorganismsynonym',
            name='siccrf_is_obsolete',
        ),
        migrations.RemoveField(
            model_name='plantsynonym',
            name='siccrf_is_obsolete',
        ),
        migrations.RemoveField(
            model_name='substancesynonym',
            name='siccrf_is_obsolete',
        ),
        migrations.AddField(
            model_name='historicalingredientsynonym',
            name='synonym_type',
            field=models.CharField(choices=[('SCIENTIFIC_NAME', 'Nom scientifique'), ('FRENCH_NAME', 'Nom en français'), ('ENGLISH_NAME', 'Nom en anglais')], default='FRENCH_NAME', verbose_name='type de synonyme'),
        ),
        migrations.AddField(
            model_name='historicalmicroorganismsynonym',
            name='synonym_type',
            field=models.CharField(choices=[('SCIENTIFIC_NAME', 'Nom scientifique'), ('FRENCH_NAME', 'Nom en français'), ('ENGLISH_NAME', 'Nom en anglais')], default='FRENCH_NAME', verbose_name='type de synonyme'),
        ),
        migrations.AddField(
            model_name='historicalplantsynonym',
            name='synonym_type',
            field=models.CharField(choices=[('SCIENTIFIC_NAME', 'Nom scientifique'), ('FRENCH_NAME', 'Nom en français'), ('ENGLISH_NAME', 'Nom en anglais')], default='FRENCH_NAME', verbose_name='type de synonyme'),
        ),
        migrations.AddField(
            model_name='historicalsubstancesynonym',
            name='synonym_type',
            field=models.CharField(choices=[('SCIENTIFIC_NAME', 'Nom scientifique'), ('FRENCH_NAME', 'Nom en français'), ('ENGLISH_NAME', 'Nom en anglais')], default='FRENCH_NAME', verbose_name='type de synonyme'),
        ),
        migrations.AddField(
            model_name='ingredientsynonym',
            name='synonym_type',
            field=models.CharField(choices=[('SCIENTIFIC_NAME', 'Nom scientifique'), ('FRENCH_NAME', 'Nom en français'), ('ENGLISH_NAME', 'Nom en anglais')], default='FRENCH_NAME', verbose_name='type de synonyme'),
        ),
        migrations.AddField(
            model_name='microorganismsynonym',
            name='synonym_type',
            field=models.CharField(choices=[('SCIENTIFIC_NAME', 'Nom scientifique'), ('FRENCH_NAME', 'Nom en français'), ('ENGLISH_NAME', 'Nom en anglais')], default='FRENCH_NAME', verbose_name='type de synonyme'),
        ),
        migrations.AddField(
            model_name='plantsynonym',
            name='synonym_type',
            field=models.CharField(choices=[('SCIENTIFIC_NAME', 'Nom scientifique'), ('FRENCH_NAME', 'Nom en français'), ('ENGLISH_NAME', 'Nom en anglais')], default='FRENCH_NAME', verbose_name='type de synonyme'),
        ),
        migrations.AddField(
            model_name='substancesynonym',
            name='synonym_type',
            field=models.CharField(choices=[('SCIENTIFIC_NAME', 'Nom scientifique'), ('FRENCH_NAME', 'Nom en français'), ('ENGLISH_NAME', 'Nom en anglais')], default='FRENCH_NAME', verbose_name='type de synonyme'),
        ),
    ]
