# Generated by Django 5.1.7 on 2025-09-29 12:37

from django.db import migrations

from data.models.abstract_models import SynonymType


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0180_remove_historicalingredientsynonym_siccrf_is_obsolete_and_more"),
    ]

    def move_name_en_as_synonym(apps, schema_editor):
        """
        Les modèles Microorganism et Plant n'avaient pas de champ name_en
        """
        # models d'ingrédients
        Ingredient = apps.get_model("data", "Ingredient")
        Substance = apps.get_model("data", "Substance")

        # modèles de synonymes d'ingrédients
        IngredientSynonym = apps.get_model("data", "IngredientSynonym")
        SubstanceSynonym = apps.get_model("data", "SubstanceSynonym")

        for ingredient in Ingredient.objects.all():
            if ingredient.siccrf_name_en:
                IngredientSynonym.objects.create(
                    name=ingredient.siccrf_name_en, standard_name=ingredient, synonym_type=SynonymType.ENGLISH
                )

        for substance in Substance.objects.all():
            if substance.siccrf_name_en:
                SubstanceSynonym.objects.create(
                    name=substance.siccrf_name_en, standard_name=substance, synonym_type=SynonymType.ENGLISH
                )

    def reverse_move_name_en_as_synonym(apps, schema_editor):
        pass

    operations = [
        migrations.RunPython(move_name_en_as_synonym, reverse_move_name_en_as_synonym),
    ]
