# Generated by Django 5.1.7 on 2025-09-29 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0181_name_en_as_synonym'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalingredient',
            name='siccrf_name_en',
        ),
        migrations.RemoveField(
            model_name='historicalsubstance',
            name='siccrf_name_en',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='siccrf_name_en',
        ),
        migrations.RemoveField(
            model_name='substance',
            name='siccrf_name_en',
        ),
    ]
