# Generated by Django 5.1.7 on 2025-10-02 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0179_merge_20250930_1434'),
        ('data', '0182_remove_historicalingredient_siccrf_name_en_and_more'),
    ]

    operations = [
    ]
