# Generated by Django 5.1.7 on 2025-10-02 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0183_merge_20251002_1033'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ingredientsynonym',
            unique_together={('standard_name', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='microorganismsynonym',
            unique_together={('standard_name', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='plantsynonym',
            unique_together={('standard_name', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='substancesynonym',
            unique_together={('standard_name', 'name')},
        ),
    ]
