# Generated by Django 5.1.7 on 2025-10-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0183_merge_20251002_1033'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ingredientsynonym',
            constraint=models.UniqueConstraint(fields=('standard_name', 'name'), name='unicity_ingredient_synonym'),
        ),
        migrations.AddConstraint(
            model_name='microorganismsynonym',
            constraint=models.UniqueConstraint(fields=('standard_name', 'name'), name='unicity_microorganism_synonym'),
        ),
        migrations.AddConstraint(
            model_name='plantsynonym',
            constraint=models.UniqueConstraint(fields=('standard_name', 'name'), name='unicity_plant_synonym'),
        ),
        migrations.AddConstraint(
            model_name='substancesynonym',
            constraint=models.UniqueConstraint(fields=('standard_name', 'name'), name='unicity_substance_synonym'),
        ),
    ]
