# Generated by Django 5.1.7 on 2025-10-07 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0184_fill_synonym_types'),
        ('data', '0184_ingredientsynonym_unicity_ingredient_synonym_and_more'),
    ]

    operations = [
    ]
