# Generated by Django 5.1.7 on 2025-10-07 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0185_historicalingredientmaxquantityperpopulationrelation_and_more'),
        ('data', '0185_merge_20251007_1443'),
    ]

    operations = [
    ]
