# Generated by Django 5.1.7 on 2025-10-09 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0186_merge_20251007_1521'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubstanceUnit',
            new_name='Unit',
        ),
    ]
