# Generated by Django 5.1.7 on 2025-10-09 14:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0187_rename_substanceunit_unit'),
    ]

    def set_first_warning(apps, schema_editor):
        Ingredient = apps.get_model("data", "Ingredient")
        Microorganism = apps.get_model("data", "Microorganism")
        Plant = apps.get_model("data", "Plant")
        Substance = apps.get_model("data", "Substance")
        for ingredient_model in [Ingredient, Microorganism, Plant, Substance]:
            for ingredient in ingredient_model.objects.exclude(warning_on_label="").iterator():
                ingredient.warnings_on_label = [ingredient.warning_on_label]
                ingredient.save()

    def reverse_set_first_warning(apps, schema_editor):
        pass

    operations = [
        migrations.AddField(
            model_name='historicalingredient',
            name='warnings_on_label',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None, verbose_name="mention(s) d'avertissement devant figurer sur l'étiquette"),
        ),
        migrations.AddField(
            model_name='historicalmicroorganism',
            name='warnings_on_label',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None, verbose_name="mention(s) d'avertissement devant figurer sur l'étiquette"),
        ),
        migrations.AddField(
            model_name='historicalplant',
            name='warnings_on_label',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None, verbose_name="mention(s) d'avertissement devant figurer sur l'étiquette"),
        ),
        migrations.AddField(
            model_name='historicalsubstance',
            name='warnings_on_label',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None, verbose_name="mention(s) d'avertissement devant figurer sur l'étiquette"),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='warnings_on_label',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None, verbose_name="mention(s) d'avertissement devant figurer sur l'étiquette"),
        ),
        migrations.AddField(
            model_name='microorganism',
            name='warnings_on_label',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None, verbose_name="mention(s) d'avertissement devant figurer sur l'étiquette"),
        ),
        migrations.AddField(
            model_name='plant',
            name='warnings_on_label',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None, verbose_name="mention(s) d'avertissement devant figurer sur l'étiquette"),
        ),
        migrations.AddField(
            model_name='substance',
            name='warnings_on_label',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None, verbose_name="mention(s) d'avertissement devant figurer sur l'étiquette"),
        ),
        migrations.RunPython(set_first_warning, reverse_set_first_warning),

    ]
