# Generated by Django 5.1.7 on 2025-10-09 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0188_historicalingredient_warnings_on_label_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalingredient',
            name='warning_on_label',
        ),
        migrations.RemoveField(
            model_name='historicalmicroorganism',
            name='warning_on_label',
        ),
        migrations.RemoveField(
            model_name='historicalplant',
            name='warning_on_label',
        ),
        migrations.RemoveField(
            model_name='historicalsubstance',
            name='warning_on_label',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='warning_on_label',
        ),
        migrations.RemoveField(
            model_name='microorganism',
            name='warning_on_label',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='warning_on_label',
        ),
        migrations.RemoveField(
            model_name='substance',
            name='warning_on_label',
        ),
    ]
