# Generated by Django 5.2.7 on 2025-10-15 09:55

from django.db import migrations
from simple_history.utils import update_change_reason


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0189_remove_historicalingredient_warning_on_label_and_more'),
    ]

    def fix_article_of_historical_declaration(apps, schema_editor):
        Declaration = apps.get_model('data', 'Declaration')
        for historical_declaration in Declaration.objects.exclude(siccrf_id=None).filter(article='ART_16'):
            if historical_declaration.history.latest('modification_date').article != historical_declaration.history.earliest('modification_date').article :
                historical_declaration.overridden_article = historical_declaration.history.earliest('modification_date').article
                historical_declaration.calculated_article = historical_declaration.history.earliest('modification_date').article
                historical_declaration.save()
                update_change_reason(historical_declaration, "Revert article de l'historique TeleIcare")

    def reverse_fix(apps, schema_editor):
        pass

    operations = [
        migrations.RunPython(fix_article_of_historical_declaration, reverse_fix),

    ]
