# Generated by Django 5.2.7 on 2025-10-17 07:48

import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0190_fix_article_historical_declaration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalingredient',
            name='regulatory_resource_links',
            field=django_jsonform.models.fields.ArrayField(base_field=models.URLField(), blank=True, null=True, size=None, verbose_name='Lien(s) vers les ressources reglementaires'),
        ),
        migrations.AlterField(
            model_name='historicalingredient',
            name='warnings_on_label',
            field=django_jsonform.models.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None, verbose_name="mention(s) d'avertissement devant figurer sur l'étiquette"),
        ),
        migrations.AlterField(
            model_name='historicalmicroorganism',
            name='regulatory_resource_links',
            field=django_jsonform.models.fields.ArrayField(base_field=models.URLField(), blank=True, null=True, size=None, verbose_name='Lien(s) vers les ressources reglementaires'),
        ),
        migrations.AlterField(
            model_name='historicalmicroorganism',
            name='warnings_on_label',
            field=django_jsonform.models.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None, verbose_name="mention(s) d'avertissement devant figurer sur l'étiquette"),
        ),
        migrations.AlterField(
            model_name='historicalplant',
            name='regulatory_resource_links',
            field=django_jsonform.models.fields.ArrayField(base_field=models.URLField(), blank=True, null=True, size=None, verbose_name='Lien(s) vers les ressources reglementaires'),
        ),
        migrations.AlterField(
            model_name='historicalplant',
            name='warnings_on_label',
            field=django_jsonform.models.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None, verbose_name="mention(s) d'avertissement devant figurer sur l'étiquette"),
        ),
        migrations.AlterField(
            model_name='historicalsubstance',
            name='regulatory_resource_links',
            field=django_jsonform.models.fields.ArrayField(base_field=models.URLField(), blank=True, null=True, size=None, verbose_name='Lien(s) vers les ressources reglementaires'),
        ),
        migrations.AlterField(
            model_name='historicalsubstance',
            name='warnings_on_label',
            field=django_jsonform.models.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None, verbose_name="mention(s) d'avertissement devant figurer sur l'étiquette"),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='regulatory_resource_links',
            field=django_jsonform.models.fields.ArrayField(base_field=models.URLField(), blank=True, null=True, size=None, verbose_name='Lien(s) vers les ressources reglementaires'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='warnings_on_label',
            field=django_jsonform.models.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None, verbose_name="mention(s) d'avertissement devant figurer sur l'étiquette"),
        ),
        migrations.AlterField(
            model_name='microorganism',
            name='regulatory_resource_links',
            field=django_jsonform.models.fields.ArrayField(base_field=models.URLField(), blank=True, null=True, size=None, verbose_name='Lien(s) vers les ressources reglementaires'),
        ),
        migrations.AlterField(
            model_name='microorganism',
            name='warnings_on_label',
            field=django_jsonform.models.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None, verbose_name="mention(s) d'avertissement devant figurer sur l'étiquette"),
        ),
        migrations.AlterField(
            model_name='plant',
            name='regulatory_resource_links',
            field=django_jsonform.models.fields.ArrayField(base_field=models.URLField(), blank=True, null=True, size=None, verbose_name='Lien(s) vers les ressources reglementaires'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='warnings_on_label',
            field=django_jsonform.models.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None, verbose_name="mention(s) d'avertissement devant figurer sur l'étiquette"),
        ),
        migrations.AlterField(
            model_name='substance',
            name='regulatory_resource_links',
            field=django_jsonform.models.fields.ArrayField(base_field=models.URLField(), blank=True, null=True, size=None, verbose_name='Lien(s) vers les ressources reglementaires'),
        ),
        migrations.AlterField(
            model_name='substance',
            name='warnings_on_label',
            field=django_jsonform.models.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None, verbose_name="mention(s) d'avertissement devant figurer sur l'étiquette"),
        ),
    ]
