# Generated by Django 5.2.7 on 2025-10-17 14:11

import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0191_alter_historicalingredient_regulatory_resource_links_and_more'),
    ]

    def authorize_parts(apps, schema_editor):
        Part = apps.get_model("data", "Part")
        # IngredientStatus.AUTHORIZED = 1
        Part.objects.filter(is_useful=True).update(status=1)

    def reverse_op(apps, schema_editor):
        pass

    operations = [
        migrations.AddField(
            model_name='historicalpart',
            name='regulatory_resource_links',
            field=django_jsonform.models.fields.ArrayField(base_field=models.URLField(), blank=True, null=True, size=None, verbose_name='Lien(s) vers les ressources reglementaires'),
        ),
        migrations.AddField(
            model_name='historicalpart',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'autorisé'), (2, 'non autorisé'), (3, 'sans objet')], default=None, null=True, verbose_name="statut de l'ingrédient ou substance"),
        ),
        migrations.AddField(
            model_name='historicalpart',
            name='to_be_entered_in_next_decree',
            field=models.BooleanField(default=False, verbose_name="L'ingrédient doit-il être inscrit dans le prochain décret ?"),
        ),
        migrations.AddField(
            model_name='part',
            name='regulatory_resource_links',
            field=django_jsonform.models.fields.ArrayField(base_field=models.URLField(), blank=True, null=True, size=None, verbose_name='Lien(s) vers les ressources reglementaires'),
        ),
        migrations.AddField(
            model_name='part',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'autorisé'), (2, 'non autorisé'), (3, 'sans objet')], default=None, null=True, verbose_name="statut de l'ingrédient ou substance"),
        ),
        migrations.AddField(
            model_name='part',
            name='to_be_entered_in_next_decree',
            field=models.BooleanField(default=False, verbose_name="L'ingrédient doit-il être inscrit dans le prochain décret ?"),
        ),
        migrations.RunPython(authorize_parts, reverse_op),
    ]
