# Generated by Django 5.2.7 on 2025-10-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0191_alter_historicalingredient_regulatory_resource_links_and_more'),
    ]

    def authorize_parts(apps, schema_editor):
        Part = apps.get_model("data", "Part")
        for part in Part.objects.filter(is_useful=True):
            part.status = Part.PartStatus.AUTHORIZED
            part.save()
        # TODO: delete the rest?
        # if I'm deleting the rest, might as well also delete the fields is_useful and must_be_monitored

    def reverse_op(apps, schema_editor):
        # if removing the is_useful field, could replace it based on AUTHORIZED status.
        pass

    operations = [
        migrations.AddField(
            model_name='historicalpart',
            name='status',
            field=models.CharField(blank=True, choices=[('AUTHORIZED', 'Autorisée'), ('NOT_AUTHORIZED', 'Non-autorisée')], max_length=50, verbose_name='statut'),
        ),
        migrations.AddField(
            model_name='part',
            name='status',
            field=models.CharField(blank=True, choices=[('AUTHORIZED', 'Autorisée'), ('NOT_AUTHORIZED', 'Non-autorisée')], max_length=50, verbose_name='statut'),
        ),
        migrations.RunPython(authorize_parts, reverse_op),
    ]
