# Generated by Django 5.2.7 on 2025-10-17 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0192_historicalpart_regulatory_resource_links_and_more'),
    ]

    def delete_unknown_status_parts(apps, schema_editor):
        Part = apps.get_model("data", "Part")
        results = Part.objects.filter(status__isnull=True).delete()
        print(f"{results[0]} Part objects deleted")

    def noop(apps, schema_editor):
        pass

    operations = [
        migrations.RemoveField(
            model_name='historicalpart',
            name='is_useful',
        ),
        migrations.RemoveField(
            model_name='historicalpart',
            name='must_be_monitored',
        ),
        migrations.RemoveField(
            model_name='part',
            name='is_useful',
        ),
        migrations.RemoveField(
            model_name='part',
            name='must_be_monitored',
        ),
        migrations.RunPython(delete_unknown_status_parts, noop),
    ]
