# Generated by Django 5.2.7 on 2025-10-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0193_remove_historicalpart_is_useful_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsubstance',
            name='must_specify_quantity',
            field=models.BooleanField(default=False, verbose_name='spécification de quantité obligatoire lors de la déclaration ?'),
        ),
        migrations.AlterField(
            model_name='substance',
            name='must_specify_quantity',
            field=models.BooleanField(default=False, verbose_name='spécification de quantité obligatoire lors de la déclaration ?'),
        ),
    ]
