# Generated by Django 5.2.7 on 2025-10-22 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0193_remove_historicalpart_is_useful_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpart',
            name='origin_declaration',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='data.declaration', verbose_name='La déclaration qui a demandé la création de cet ingrédient'),
        ),
        migrations.AddField(
            model_name='part',
            name='origin_declaration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.declaration', verbose_name='La déclaration qui a demandé la création de cet ingrédient'),
        ),
    ]
