# Generated by Django 5.2.7 on 2025-10-29 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0193_remove_historicalpart_is_useful_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalingredient',
            name='must_specify_quantity',
            field=models.BooleanField(default=False, verbose_name='spécification de quantité obligatoire lors de la déclaration ?'),
        ),
        migrations.AddField(
            model_name='historicalmicroorganism',
            name='must_specify_quantity',
            field=models.BooleanField(default=False, verbose_name='spécification de quantité obligatoire lors de la déclaration ?'),
        ),
        migrations.AddField(
            model_name='historicalplant',
            name='must_specify_quantity',
            field=models.BooleanField(default=False, verbose_name='spécification de quantité obligatoire lors de la déclaration ?'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='must_specify_quantity',
            field=models.BooleanField(default=False, verbose_name='spécification de quantité obligatoire lors de la déclaration ?'),
        ),
        migrations.AddField(
            model_name='microorganism',
            name='must_specify_quantity',
            field=models.BooleanField(default=False, verbose_name='spécification de quantité obligatoire lors de la déclaration ?'),
        ),
        migrations.AddField(
            model_name='plant',
            name='must_specify_quantity',
            field=models.BooleanField(default=False, verbose_name='spécification de quantité obligatoire lors de la déclaration ?'),
        ),
        migrations.AlterField(
            model_name='historicalsubstance',
            name='must_specify_quantity',
            field=models.BooleanField(default=False, verbose_name='spécification de quantité obligatoire lors de la déclaration ?'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.unit', verbose_name='unité des quantités spécifiées (quantité max, apport de référence)'),
        ),
        migrations.AlterField(
            model_name='microorganism',
            name='unit',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.unit', verbose_name='unité des quantités spécifiées (quantité max, apport de référence)'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='unit',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.unit', verbose_name='unité des quantités spécifiées (quantité max, apport de référence)'),
        ),
        migrations.AlterField(
            model_name='substance',
            name='must_specify_quantity',
            field=models.BooleanField(default=False, verbose_name='spécification de quantité obligatoire lors de la déclaration ?'),
        ),
        migrations.AlterField(
            model_name='substance',
            name='unit',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.unit', verbose_name='unité des quantités spécifiées (quantité max, apport de référence)'),
        ),
    ]
