# Generated by Django 5.2.7 on 2025-10-28 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0194_historicalpart_origin_declaration_and_more'),
        ('data', '0195_alter_snapshot_action'),
    ]

    operations = [
    ]
