# Generated by Django 5.2.7 on 2025-10-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0196_merge_20251028_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalingredient',
            name='revoked_detail',
            field=models.TextField(blank=True, verbose_name="information pour les pros du retrait de l'ingrédient"),
        ),
        migrations.AddField(
            model_name='historicalmicroorganism',
            name='revoked_detail',
            field=models.TextField(blank=True, verbose_name="information pour les pros du retrait de l'ingrédient"),
        ),
        migrations.AddField(
            model_name='historicalpart',
            name='revoked_detail',
            field=models.TextField(blank=True, verbose_name="information pour les pros du retrait de l'ingrédient"),
        ),
        migrations.AddField(
            model_name='historicalplant',
            name='revoked_detail',
            field=models.TextField(blank=True, verbose_name="information pour les pros du retrait de l'ingrédient"),
        ),
        migrations.AddField(
            model_name='historicalsubstance',
            name='revoked_detail',
            field=models.TextField(blank=True, verbose_name="information pour les pros du retrait de l'ingrédient"),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='revoked_detail',
            field=models.TextField(blank=True, verbose_name="information pour les pros du retrait de l'ingrédient"),
        ),
        migrations.AddField(
            model_name='microorganism',
            name='revoked_detail',
            field=models.TextField(blank=True, verbose_name="information pour les pros du retrait de l'ingrédient"),
        ),
        migrations.AddField(
            model_name='part',
            name='revoked_detail',
            field=models.TextField(blank=True, verbose_name="information pour les pros du retrait de l'ingrédient"),
        ),
        migrations.AddField(
            model_name='plant',
            name='revoked_detail',
            field=models.TextField(blank=True, verbose_name="information pour les pros du retrait de l'ingrédient"),
        ),
        migrations.AddField(
            model_name='substance',
            name='revoked_detail',
            field=models.TextField(blank=True, verbose_name="information pour les pros du retrait de l'ingrédient"),
        ),
        migrations.AlterField(
            model_name='historicalingredient',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'autorisé'), (2, 'non autorisé'), (3, 'sans objet'), (99, "retiré par l'administration")], default=None, null=True, verbose_name="statut de l'ingrédient ou substance"),
        ),
        migrations.AlterField(
            model_name='historicalmicroorganism',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'autorisé'), (2, 'non autorisé'), (3, 'sans objet'), (99, "retiré par l'administration")], default=None, null=True, verbose_name="statut de l'ingrédient ou substance"),
        ),
        migrations.AlterField(
            model_name='historicalpart',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'autorisé'), (2, 'non autorisé'), (3, 'sans objet'), (99, "retiré par l'administration")], default=None, null=True, verbose_name="statut de l'ingrédient ou substance"),
        ),
        migrations.AlterField(
            model_name='historicalplant',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'autorisé'), (2, 'non autorisé'), (3, 'sans objet'), (99, "retiré par l'administration")], default=None, null=True, verbose_name="statut de l'ingrédient ou substance"),
        ),
        migrations.AlterField(
            model_name='historicalsubstance',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'autorisé'), (2, 'non autorisé'), (3, 'sans objet'), (99, "retiré par l'administration")], default=None, null=True, verbose_name="statut de l'ingrédient ou substance"),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'autorisé'), (2, 'non autorisé'), (3, 'sans objet'), (99, "retiré par l'administration")], default=None, null=True, verbose_name="statut de l'ingrédient ou substance"),
        ),
        migrations.AlterField(
            model_name='microorganism',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'autorisé'), (2, 'non autorisé'), (3, 'sans objet'), (99, "retiré par l'administration")], default=None, null=True, verbose_name="statut de l'ingrédient ou substance"),
        ),
        migrations.AlterField(
            model_name='part',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'autorisé'), (2, 'non autorisé'), (3, 'sans objet'), (99, "retiré par l'administration")], default=None, null=True, verbose_name="statut de l'ingrédient ou substance"),
        ),
        migrations.AlterField(
            model_name='plant',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'autorisé'), (2, 'non autorisé'), (3, 'sans objet'), (99, "retiré par l'administration")], default=None, null=True, verbose_name="statut de l'ingrédient ou substance"),
        ),
        migrations.AlterField(
            model_name='substance',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'autorisé'), (2, 'non autorisé'), (3, 'sans objet'), (99, "retiré par l'administration")], default=None, null=True, verbose_name="statut de l'ingrédient ou substance"),
        ),
    ]
