# Generated by Django 5.2.7 on 2025-11-03 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0194_alter_historicalsubstance_must_specify_quantity_and_more'),
        ('data', '0197_historicalingredient_revoked_detail_and_more'),
    ]

    operations = [
    ]
