# Generated by Django 5.2.8 on 2025-11-12 14:42

from django.db import migrations
from django.core.paginator import Paginator
from django.db.models import Q

class Migration(migrations.Migration):

    dependencies = [
        ('data', '0198_merge_20251103_1411'),
    ]

    def clean_snapshot_data(apps, schema_editor):
        Snapshot = apps.get_model("data", "Snapshot")
        Declaration = apps.get_model("data", "Declaration")

        queryset = Snapshot.objects.filter(
            declaration__teleicare_declaration_number__isnull=True, 
            status="AUTHORIZED"
        ).filter(
            Q(action="AUTHORIZE_NO_VISA") | Q(action="APPROVE_VISA", post_validation_status="AUTHORIZED")
        ).order_by('id')

        paginator = Paginator(queryset, 1000)
        for page_num in paginator.page_range:
            snapshots_to_save = []
            for snapshot in paginator.page(page_num).object_list:
                snapshot.comment = ""
                snapshot.expiration_days = None
                snapshot.blocking_reasons = None
                snapshots_to_save.append(snapshot)
            Snapshot.objects.bulk_update(snapshots_to_save, ["comment", "expiration_days", "blocking_reasons"])

    def reverse_clean_snapshot_data(apps, schema_editor):
        pass

    operations = [
        migrations.RunPython(clean_snapshot_data, reverse_clean_snapshot_data),
    ]
