# Generated by Django 5.2.8 on 2025-11-17 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0199_remove_approval_comments'),
    ]

    def remove_novel_food_tag_for_authorized_plants(apps, schema_editor):
        Plant = apps.get_model("data", "Plant")
        for plant in Plant.objects.filter(novel_food=True, status=1):
            plant.novel_food = False
            plant.save()
        else:
            pass

    def reverse_remove_novel_food_tag_for_authorized_plants(apps, schema_editor):
        pass

    operations = [
        migrations.RunPython(
            remove_novel_food_tag_for_authorized_plants, reverse_remove_novel_food_tag_for_authorized_plants
        ),

    ]
