# Generated by Django 5.2.8 on 2025-11-20 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0199_remove_approval_comments'),
    ]

    def remove_relation_to_obsolete_substance(apps, schema_editor):
        Substance = apps.get_model("data", "Substance")
        IngredientSubstanceRelation = apps.get_model("data", "IngredientSubstanceRelation")
        PlantSubstanceRelation = apps.get_model("data", "PlantSubstanceRelation")
        MicroorganismSubstanceRelation = apps.get_model("data", "MicroorganismSubstanceRelation")
        for model in [IngredientSubstanceRelation, PlantSubstanceRelation, MicroorganismSubstanceRelation]:
            for ingredient_substance_relation in model.objects.filter(substance__is_obsolete=True):
                ingredient_substance_relation.delete()

    def reverse_remove_relation_to_obsolete_substance(apps, schema_editor):
        pass

    operations = [
        migrations.RunPython(
            remove_relation_to_obsolete_substance, reverse_remove_relation_to_obsolete_substance
        ),
    ]
