# Generated by Django 5.2.7 on 2025-11-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0199_remove_approval_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaration',
            name='revoked_ingredient',
            field=models.JSONField(default=dict, verbose_name="l'ingrédient retiré par l'administration"),
        ),
        migrations.AddField(
            model_name='historicaldeclaration',
            name='revoked_ingredient',
            field=models.JSONField(default=dict, verbose_name="l'ingrédient retiré par l'administration"),
        ),
    ]
