# Generated by Django 5.2.9 on 2025-12-09 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0200_declaration_revoked_ingredient_and_more'),
        ('data', '0200_remove_novel_food_tag_for_authorized_plants'),
    ]

    operations = [
    ]
