# Generated by Django 5.2.8 on 2025-12-02 15:31

import django.db.models.deletion
import django_jsonform.models.fields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0200_remove_novel_food_tag_for_authorized_plants'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aroma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('to_be_entered_in_next_decree', models.BooleanField(default=False, verbose_name="L'ingrédient doit-il être inscrit dans le prochain décret ?")),
                ('regulatory_resource_links', django_jsonform.models.fields.ArrayField(base_field=models.URLField(), blank=True, null=True, size=None, verbose_name='Lien(s) vers les ressources reglementaires')),
                ('revoked_detail', models.TextField(blank=True, verbose_name="information pour les pros du retrait de l'ingrédient")),
                ('siccrf_id', models.IntegerField(blank=True, db_index=True, editable=False, null=True, unique=True, verbose_name='id dans les tables et tables relationnelles SICCRF')),
                ('name', models.TextField(default='', verbose_name='nom')),
                ('is_obsolete', models.BooleanField(default=False, verbose_name='objet obsolète')),
                ('description', models.TextField(blank=True)),
                ('origin_declaration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.declaration', verbose_name='La déclaration qui a demandé la création de cet ingrédient')),
            ],
            options={
                'verbose_name': 'arôme',
            },
        ),
        migrations.CreateModel(
            name='DeclaredAroma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new', models.BooleanField(default=False)),
                ('new_description', models.TextField(blank=True, verbose_name='description')),
                ('first_ocurrence', models.BooleanField(default=False, verbose_name='Est-ce que cet ingrédient a été rajouté en base suite à cette déclaration ?')),
                ('authorization_mode', models.CharField(blank=True, choices=[('FR', 'Utilisable en France'), ('EU', "Autorisé dans un État membre de l'UE ou EEE")], verbose_name="modalité d'autorisation pour un élément ajouté manuellement")),
                ('fr_reason', models.CharField(blank=True, choices=[('TRADITIONAL_USAGE', "Ingrédient bénéficiant d'un historique de consommation selon le catalogue Novel Food ou dont l'utilisation en alimentation humaine est bien établie"), ('NOVEL_FOOD', "L'ingrédient figure sur la liste de l'Union des nouveaux aliments conformément au règlement (UE) 2017/2470"), ('MISSING', "L'ingrédient est autorisé en France mais ne figure pas dans la base de données")], verbose_name="raison de l'ajout manuel")),
                ('fr_details', models.CharField(blank=True, verbose_name="information additionnelle sur l'autorisation en France")),
                ('eu_reference_country', models.CharField(blank=True, choices=[('FR', 'France'), ('DE', 'Allemagne'), ('AT', 'Autriche'), ('BE', 'Belgique'), ('BG', 'Bulgarie'), ('CY', 'Chypre'), ('HR', 'Croatie'), ('DK', 'Danemark'), ('ES', 'Espagne'), ('EE', 'Estonie'), ('FI', 'Finlande'), ('GR', 'Grèce'), ('HU', 'Hongrie'), ('IE', 'Irlande'), ('NI', 'Irlande du Nord'), ('IS', 'Islande'), ('IT', 'Italie'), ('LV', 'Lettonie'), ('LI', 'Liechtenstein'), ('LT', 'Lituanie'), ('LU', 'Luxembourg'), ('MT', 'Malte'), ('NO', 'Norvège'), ('NL', 'Pays-Bas'), ('PL', 'Pologne'), ('PT', 'Portugal'), ('RO', 'Roumanie'), ('SK', 'Slovaquie'), ('SI', 'Slovénie'), ('SE', 'Suède'), ('CZ', 'République Tchèque')], default='FR', verbose_name='pays de source réglementaire')),
                ('eu_legal_source', models.TextField(blank=True, verbose_name="référence du texte réglementaire d'un autre pays européen")),
                ('eu_details', models.TextField(blank=True, verbose_name="information additionnelle sur l'autorisation dans un autre pays européen")),
                ('request_status', models.CharField(choices=[('REQUESTED', 'Ingrédient ajouté à la déclaration par le déclarant'), ('INFORMATION', "En attente de plus d'information"), ('REJECTED', 'Refusé'), ('REPLACED', 'Remplacé par un ingrédient existant')], default='REQUESTED', max_length=50, verbose_name="statut de la demande de l'ajout du nouvel ingrédient")),
                ('request_private_notes', models.TextField(blank=True, verbose_name="notes de l'instruction à destination de l'administration")),
                ('new_name', models.TextField(blank=True, verbose_name='libellé')),
                ('new_type', models.TextField(blank=True, verbose_name="type de l'ingrédient")),
                ('quantity', models.FloatField(blank=True, null=True, verbose_name='quantité par DJR')),
                ('aroma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='data.aroma', verbose_name="arôme ajouté par l'user")),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declared_aromas', to='data.declaration', verbose_name='déclaration')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='data.unit', verbose_name='unité')),
            ],
            options={
                'verbose_name': 'arôme déclaré',
                'verbose_name_plural': 'arômes déclarés',
            },
        ),
        migrations.CreateModel(
            name='HistoricalAromaSynonym',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('creation_date', models.DateTimeField(blank=True, editable=False)),
                ('modification_date', models.DateTimeField(blank=True, editable=False)),
                ('siccrf_id', models.IntegerField(blank=True, db_index=True, editable=False, null=True, verbose_name='id dans les tables et tables relationnelles SICCRF')),
                ('name', models.TextField(verbose_name='nom')),
                ('synonym_type', models.CharField(choices=[('SCIENTIFIC_NAME', 'Nom scientifique'), ('FRENCH_NAME', 'Nom en français'), ('ENGLISH_NAME', 'Nom en anglais')], default='FRENCH_NAME', verbose_name='type de synonyme')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('standard_name', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='data.aroma', verbose_name='nom de référence')),
            ],
            options={
                'verbose_name': "historical synonyme d'arome",
                'verbose_name_plural': "historical synonyme d'aromes",
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDeclaredAroma',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('new', models.BooleanField(default=False)),
                ('new_description', models.TextField(blank=True, verbose_name='description')),
                ('first_ocurrence', models.BooleanField(default=False, verbose_name='Est-ce que cet ingrédient a été rajouté en base suite à cette déclaration ?')),
                ('authorization_mode', models.CharField(blank=True, choices=[('FR', 'Utilisable en France'), ('EU', "Autorisé dans un État membre de l'UE ou EEE")], verbose_name="modalité d'autorisation pour un élément ajouté manuellement")),
                ('fr_reason', models.CharField(blank=True, choices=[('TRADITIONAL_USAGE', "Ingrédient bénéficiant d'un historique de consommation selon le catalogue Novel Food ou dont l'utilisation en alimentation humaine est bien établie"), ('NOVEL_FOOD', "L'ingrédient figure sur la liste de l'Union des nouveaux aliments conformément au règlement (UE) 2017/2470"), ('MISSING', "L'ingrédient est autorisé en France mais ne figure pas dans la base de données")], verbose_name="raison de l'ajout manuel")),
                ('fr_details', models.CharField(blank=True, verbose_name="information additionnelle sur l'autorisation en France")),
                ('eu_reference_country', models.CharField(blank=True, choices=[('FR', 'France'), ('DE', 'Allemagne'), ('AT', 'Autriche'), ('BE', 'Belgique'), ('BG', 'Bulgarie'), ('CY', 'Chypre'), ('HR', 'Croatie'), ('DK', 'Danemark'), ('ES', 'Espagne'), ('EE', 'Estonie'), ('FI', 'Finlande'), ('GR', 'Grèce'), ('HU', 'Hongrie'), ('IE', 'Irlande'), ('NI', 'Irlande du Nord'), ('IS', 'Islande'), ('IT', 'Italie'), ('LV', 'Lettonie'), ('LI', 'Liechtenstein'), ('LT', 'Lituanie'), ('LU', 'Luxembourg'), ('MT', 'Malte'), ('NO', 'Norvège'), ('NL', 'Pays-Bas'), ('PL', 'Pologne'), ('PT', 'Portugal'), ('RO', 'Roumanie'), ('SK', 'Slovaquie'), ('SI', 'Slovénie'), ('SE', 'Suède'), ('CZ', 'République Tchèque')], default='FR', verbose_name='pays de source réglementaire')),
                ('eu_legal_source', models.TextField(blank=True, verbose_name="référence du texte réglementaire d'un autre pays européen")),
                ('eu_details', models.TextField(blank=True, verbose_name="information additionnelle sur l'autorisation dans un autre pays européen")),
                ('request_status', models.CharField(choices=[('REQUESTED', 'Ingrédient ajouté à la déclaration par le déclarant'), ('INFORMATION', "En attente de plus d'information"), ('REJECTED', 'Refusé'), ('REPLACED', 'Remplacé par un ingrédient existant')], default='REQUESTED', max_length=50, verbose_name="statut de la demande de l'ajout du nouvel ingrédient")),
                ('request_private_notes', models.TextField(blank=True, verbose_name="notes de l'instruction à destination de l'administration")),
                ('new_name', models.TextField(blank=True, verbose_name='libellé')),
                ('new_type', models.TextField(blank=True, verbose_name="type de l'ingrédient")),
                ('quantity', models.FloatField(blank=True, null=True, verbose_name='quantité par DJR')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('aroma', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='data.aroma', verbose_name="arôme ajouté par l'user")),
                ('declaration', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='data.declaration', verbose_name='déclaration')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='data.unit', verbose_name='unité')),
            ],
            options={
                'verbose_name': 'historical arôme déclaré',
                'verbose_name_plural': 'historical arômes déclarés',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='AromaSynonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('siccrf_id', models.IntegerField(blank=True, db_index=True, editable=False, null=True, unique=True, verbose_name='id dans les tables et tables relationnelles SICCRF')),
                ('name', models.TextField(verbose_name='nom')),
                ('synonym_type', models.CharField(choices=[('SCIENTIFIC_NAME', 'Nom scientifique'), ('FRENCH_NAME', 'Nom en français'), ('ENGLISH_NAME', 'Nom en anglais')], default='FRENCH_NAME', verbose_name='type de synonyme')),
                ('standard_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.aroma', verbose_name='nom de référence')),
            ],
            options={
                'verbose_name': "synonyme d'arome",
                'constraints': [models.UniqueConstraint(fields=('standard_name', 'name'), name='unicity_aroma_synonym')],
            },
        ),
    ]
