# Generated by Django 5.2.8 on 2025-12-02 10:43

from django.db import migrations
from data.behaviours.time_stampable import suppress_autotime


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0201_aroma_declaredaroma_historicalaromasynonym_and_more'),
    ]

    def set_aromas(apps, schema_editor):
        Ingredient = apps.get_model("data", "Ingredient")
        Aroma = apps.get_model("data", "Aroma")
        AromaSynonym = apps.get_model("data", "AromaSynonym")
        DeclaredAroma = apps.get_model("data", "DeclaredAroma")
        for old_aroma in Ingredient.objects.filter(ingredient_type=3, is_obsolete=False):
            new_aroma = Aroma(name=old_aroma.name, creation_date=old_aroma.creation_date)
            with suppress_autotime(new_aroma, ["creation_date"]):
                new_aroma.save()
            for synonym in old_aroma.ingredientsynonym_set.all():
                AromaSynonym.objects.create(standard_name=new_aroma, name=old_aroma.name)
            for declared_aroma in old_aroma.declaredingredient_set.all():
                DeclaredAroma.objects.create(
                    declaration=declared_aroma.declaration,
                    aroma=new_aroma,
                    new_name=declared_aroma.new_name,
                    authorization_mode=declared_aroma.authorization_mode,
                    fr_reason=declared_aroma.fr_reason,
                    request_status=declared_aroma.request_status,
                )
            # old_aroma.delete() ne pas supprimer tant que le front depend des arômes dans le modèle Ingredient

    def reverse_set_aromas(apps, schema_editor):
        pass

    operations = [
        migrations.RunPython(set_aromas, reverse_set_aromas),
    ]
