# Generated by Django 5.2.9 on 2025-12-24 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0200_remove_relation_to_obsolete_substance'),
        ('data', '0201_merge_20251209_1631'),
    ]

    operations = [
    ]
