# Generated by Django 6.0 on 2026-01-02 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0202_merge_20251224_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substancesynonym',
            name='standard_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.substance', verbose_name='nom de référence'),
        ),
    ]
