# Generated by Django 6.0 on 2026-01-30 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0203_alter_substancesynonym_standard_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsubstance',
            name='nutritional_reference',
        ),
        migrations.RemoveField(
            model_name='substance',
            name='nutritional_reference',
        ),
    ]
