# Generated by Django 6.0 on 2026-02-19 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0203_alter_substancesynonym_standard_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaration',
            name='mandated_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mandated_declarations', to='data.company', verbose_name='entreprise mandataire'),
        ),
    ]
