# Generated by Django 6.0.2 on 2026-03-02 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0204_alter_declaration_mandated_company'),
        ('data', '0204_remove_historicalsubstance_nutritional_reference_and_more'),
    ]

    operations = [
    ]
