# Generated by Django 6.0.5 on 2026-06-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0205_merge_20260302_1032'),
    ]

    def reassign_uk_companies(apps, schema_editor):
        Company = apps.get_model("data", "Company")

        queryset = Company.objects.filter(country="FR", vat__startswith="GB")
        print(f"{queryset.count()} companies to update")
        for company in queryset:
            company.country = "GB"
        Company.objects.bulk_update(queryset, ["country"])

    def reverse_reassign_uk_companies(apps, schema_editor):
        Company = apps.get_model("data", "Company")

        queryset = Company.objects.filter(country="GB", vat__startswith="GB")
        print(f"{queryset.count()} companies to reverse update")
        for company in queryset:
            company.country = "FR"
        # utiliser bulk update pour éviter des problèmes de validation sur d'autres champs
        Company.objects.bulk_update(queryset, ["country"])

    operations = [
        migrations.AlterField(
            model_name='company',
            name='country',
            field=models.CharField(choices=[('GB', 'Grande-Bretagne'), ('FR', 'France'), ('DE', 'Allemagne'), ('AT', 'Autriche'), ('BE', 'Belgique'), ('BG', 'Bulgarie'), ('CY', 'Chypre'), ('HR', 'Croatie'), ('DK', 'Danemark'), ('ES', 'Espagne'), ('EE', 'Estonie'), ('FI', 'Finlande'), ('GR', 'Grèce'), ('HU', 'Hongrie'), ('IE', 'Irlande'), ('NI', 'Irlande du Nord'), ('IS', 'Islande'), ('IT', 'Italie'), ('LV', 'Lettonie'), ('LI', 'Liechtenstein'), ('LT', 'Lituanie'), ('LU', 'Luxembourg'), ('MT', 'Malte'), ('NO', 'Norvège'), ('NL', 'Pays-Bas'), ('PL', 'Pologne'), ('PT', 'Portugal'), ('RO', 'Roumanie'), ('SK', 'Slovaquie'), ('SI', 'Slovénie'), ('SE', 'Suède'), ('CZ', 'République Tchèque')], default='FR', max_length=50, verbose_name='pays'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='country',
            field=models.CharField(choices=[('GB', 'Grande-Bretagne'), ('FR', 'France'), ('DE', 'Allemagne'), ('AT', 'Autriche'), ('BE', 'Belgique'), ('BG', 'Bulgarie'), ('CY', 'Chypre'), ('HR', 'Croatie'), ('DK', 'Danemark'), ('ES', 'Espagne'), ('EE', 'Estonie'), ('FI', 'Finlande'), ('GR', 'Grèce'), ('HU', 'Hongrie'), ('IE', 'Irlande'), ('NI', 'Irlande du Nord'), ('IS', 'Islande'), ('IT', 'Italie'), ('LV', 'Lettonie'), ('LI', 'Liechtenstein'), ('LT', 'Lituanie'), ('LU', 'Luxembourg'), ('MT', 'Malte'), ('NO', 'Norvège'), ('NL', 'Pays-Bas'), ('PL', 'Pologne'), ('PT', 'Portugal'), ('RO', 'Roumanie'), ('SK', 'Slovaquie'), ('SI', 'Slovénie'), ('SE', 'Suède'), ('CZ', 'République Tchèque')], default='FR', max_length=50, verbose_name='pays'),
        ),
        migrations.RunPython(reassign_uk_companies, reverse_reassign_uk_companies),
    ]
