# Generated by Django 6.0.7 on 2026-08-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0206_alter_company_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login_proconnect',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dernière connexion avec ProConnect'),
        ),
    ]
