-- select les entreprises ayant des entreprises clientes
SELECT ICA_ETABLISSEMENT.ETAB_IDENT, ICA_ETABLISSEMENT.ETAB_RAISON_SOCIALE, ICA_ETABLISSEMENT.ETAB_ADRE_VILLE, ICA_ETS_CLIENT.ETAB_CLIENT_SIRET, ICA_ETS_CLIENT.ETAB_CLIENT_RAISON_SOCIALE, ICA_ETS_CLIENT.ETAB_CLIENT_ADRE_VILLE FROM ICA_ETS_CLIENT
INNER JOIN ICA_ETABLISSEMENT
    ON ICA_ETS_CLIENT.ETAB_IDENT = ICA_ETABLISSEMENT.ETAB_IDENT
-- il y en a 93
-- on remarque que les etablissements clients ont forcément un SIRET et pas de n° de TVA intracommunautaire


-- count du nombre de client par entreprise
-- maxi 18
SELECT ICA_ETABLISSEMENT.ETAB_IDENT, ICA_ETABLISSEMENT.ETAB_RAISON_SOCIALE, COUNT(DISTINCT ICA_ETS_CLIENT.ETAB_CLIENT_SIRET) as NB_CLIENT FROM ICA_ETS_CLIENT
JOIN ICA_ETABLISSEMENT
ON ICA_ETS_CLIENT.ETAB_IDENT = ICA_ETABLISSEMENT.ETAB_IDENT
GROUP BY ICA_ETABLISSEMENT.ETAB_IDENT, ICA_ETABLISSEMENT.ETAB_RAISON_SOCIALE
ORDER BY NB_CLIENT DESC



-- count du nombre de mandataires par entreprises
-- 1994 entreprises sont clientes de une ou plusieurs entreprises mandataire
SELECT ICA_ETABLISSEMENT.ETAB_IDENT, ICA_ETABLISSEMENT.ETAB_RAISON_SOCIALE, COUNT(DISTINCT ICA_ETS_MANDATAIRE.ETAB_IDENT_ICA_ETS_MANDATAIRE) as NB_MANDATAIRE FROM ICA_ETS_MANDATAIRE
JOIN ICA_ETABLISSEMENT
ON ICA_ETS_MANDATAIRE.ETAB_IDENT = ICA_ETABLISSEMENT.ETAB_IDENT
GROUP BY ICA_ETABLISSEMENT.ETAB_IDENT, ICA_ETABLISSEMENT.ETAB_RAISON_SOCIALE
ORDER BY NB_MANDATAIRE DESC

-- on remarque que le nombre de mandataires total est différent du nombre d'entreprises ayant des clients
-- la table IA_ETS_CLIENT as-t'elle été délaissée ?


-- count du nombre de client par entreprise mandataire à partir de la table ICA_ETS_MANDATAIRE
-- 191 clients maxi
-- au total 226 entreprises sont mandataires
SELECT ETAB_IDENT_ICA_ETS_MANDATAIRE, COUNT(DISTINCT ETAB_IDENT) AS NB_CLIENT
FROM ICA_ETS_MANDATAIRE
GROUP BY ETAB_IDENT_ICA_ETS_MANDATAIRE
ORDER BY NB_CLIENT DESC

SELECT AVG(NB_CLIENT) FROM (
SELECT ETAB_IDENT_ICA_ETS_MANDATAIRE, COUNT(DISTINCT ETAB_IDENT) AS NB_CLIENT
FROM ICA_ETS_MANDATAIRE
GROUP BY ETAB_IDENT_ICA_ETS_MANDATAIRE
) as T
-- 11

SELECT PERCENTILE_CONT(0.7) WITHIN GROUP (ORDER BY NB_CLIENT)
        OVER () AS MedianCont FROM (
SELECT ETAB_IDENT_ICA_ETS_MANDATAIRE, COUNT(DISTINCT ETAB_IDENT) AS NB_CLIENT
FROM ICA_ETS_MANDATAIRE
GROUP BY ETAB_IDENT_ICA_ETS_MANDATAIRE
) as T
-- 5


-- détail sur ces entreprises super-mandataires
SELECT ETAB_IDENT_ICA_ETS_MANDATAIRE, ICA_ETABLISSEMENT.ETAB_RAISON_SOCIALE, ICA_ETABLISSEMENT.ETAB_ENSEIGNE, COUNT(DISTINCT ICA_ETS_MANDATAIRE.ETAB_IDENT) AS NB_CLIENT
FROM ICA_ETS_MANDATAIRE
JOIN ICA_ETABLISSEMENT
ON ICA_ETABLISSEMENT.ETAB_IDENT = ETAB_IDENT_ICA_ETS_MANDATAIRE
GROUP BY ETAB_IDENT_ICA_ETS_MANDATAIRE, ICA_ETABLISSEMENT.ETAB_RAISON_SOCIALE, ICA_ETABLISSEMENT.ETAB_ENSEIGNE
ORDER BY NB_CLIENT DESC


-- verification de la symétrie de cette relation
SELECT SUM(NB_CLIENT) FROM (
SELECT ETAB_IDENT_ICA_ETS_MANDATAIRE, COUNT(DISTINCT ETAB_IDENT) AS NB_CLIENT
FROM ICA_ETS_MANDATAIRE
GROUP BY ETAB_IDENT_ICA_ETS_MANDATAIRE
) as T
-- 2517

SELECT SUM(NB_MANDATAIRE) FROM (
SELECT ICA_ETABLISSEMENT.ETAB_IDENT, ICA_ETABLISSEMENT.ETAB_RAISON_SOCIALE, COUNT(DISTINCT ICA_ETS_MANDATAIRE.ETAB_IDENT_ICA_ETS_MANDATAIRE) as NB_MANDATAIRE FROM ICA_ETS_MANDATAIRE
JOIN ICA_ETABLISSEMENT
ON ICA_ETS_MANDATAIRE.ETAB_IDENT = ICA_ETABLISSEMENT.ETAB_IDENT
GROUP BY ICA_ETABLISSEMENT.ETAB_IDENT, ICA_ETABLISSEMENT.ETAB_RAISON_SOCIALE
) as T
-- 2517

SELECT count(*) from ICA_ETABLISSEMENT
-- 7209
