# Generated by Django 5.0.2 on 2024-03-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="magiclinktoken",
            name="usage",
            field=models.CharField(
                choices=[("verification-email", "Verify email address")],
                max_length=1024,
            ),
        ),
    ]
