# Generated by Django 5.0.3 on 2024-03-26 13:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0002_alter_magiclinktoken_usage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="magiclinktoken",
            name="created",
        ),
        migrations.RemoveField(
            model_name="magiclinktoken",
            name="modified",
        ),
        migrations.AddField(
            model_name="magiclinktoken",
            name="creation_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="magiclinktoken",
            name="modification_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
