# Generated by Django 5.0.4 on 2024-04-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0003_remove_magiclinktoken_created_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InseeToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(blank=True, null=True, verbose_name="clé")),
                ("expiration", models.DateTimeField()),
            ],
        ),
    ]
