# Generated by Django 5.0.4 on 2024-05-07 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0004_inseetoken"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inseetoken",
            options={
                "verbose_name": "Token Insee",
                "verbose_name_plural": "Token Insee",
            },
        ),
    ]
