# Generated by Django 5.1.4 on 2025-01-14 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0005_alter_inseetoken_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InseeToken',
        ),
    ]
